= گزیده‌های شنیداری
:toc:
:toc-title: فهرست مطالب
:toclevels: 1
:nofooter:

== آینه کلی

audio::media/audio/ayene_kolli.mp3[controls]

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۷۴۵
[.poem]
....
فضول گشته‌ام امروز، جنگ می جویم
منوش نکته مستان که یاوه می گویم

منوش: مشنو (از مصدر نیوشیدن)
یاوه: مجازاً سخن بیهوده و بی معنی، شوخی بی مزه

آینهٔ جان نیست اِلّا رویِ یار
رویِ آن یاری که باشد زآن دیار

گفتم: ای دل آینهٔ کُلّی بجو
رَوْ به دریا، کار بر ناید به جُو

آینهٔ کُلّی: در اینجا اشاره به انسانهای رشد یافته و به کمال رسیده می باشد.

زین طلب بنده به کویِ تو رسید
دردْ، مریم را به خُرمابُن کَشید

خُرمابُن: درخت خرما، نخل

از خدا غير خدا را خواستن
ظن افزوني است و كلي كاستن
....

.قرآن کریم، سوره مريم (۱۹)، آیه ۲۳
[.poem]
....
« فَأَجَاءَهَا الْمَخَاضُ إِلَىٰ جِذْعِ النَّخْلَةِ قَالَتْ يَا لَيْتَنِي مِتُّ قَبْلَ هَٰذَا وَكُنْتُ نَسْيًا مَنْسِيًّا »

« درد زاييدن او را به سوى تنه درخت خرمايى كشانيد. گفت: اى
كاش پيش از اين مرده بودم و از يادها فراموش شده بودم. »
....

[.poem]
....
دیدهٔ تو چون دلم را دیده شد
شد دلِ نادیده، غرقِ دیده شد

آینهٔ کُلّی تو را دیدم اَبَد
دیدم اندر چشمِ تو، من نقشِ خَود

گفتم: آخر خویش را من یافتم
در دو چشمش، راهِ روشن یافتم

گفت وَهمَم: کان خیالِ توست هان
ذاتِ خود را از خیالِ خود بدان

وَهمَ: خیال، پندار، آن قسمت از مغز که تخیّل می کند.

نقش من از چشم تو آواز داد
که منم تو، تو منی در اتحاد
....

== افسانه من ذهنی

audio::media/audio/afsane_man_zehni.mp3[controls]

موانع مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی، که به نظر
من نمی گذارند، من در این لحظه زندگی کنم و اگر آن موانع رفع شوند، زندگی
من شروع می شود.

مسایل مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی که خودشان
را به من به صورت گره ذهنی یا مساله ارائه می کنند و من نمی خواهم یا اصلاً
نمی توانم برای حل آنها کاری کنم.

دشمنان مَنِ ذهنی من: اشخاص و یا وضعیت های ساخته شده به وسیله من ذهنی،
که به نظر من فعالانه در پایین آوردن کیفیت زندگی من یا محروم کردن من از زندگی
می کوشند. من ذهنی برای بقا، از آنها به صورت قطب استفاده می کند و انرژی
مخرب ایجاد میکند.

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شماره ۱۳۴۴
[.poem]
....
دمِ او جان دهدت رو ز نَفَخْتُ بپذیر
کارِ او کُنْ فَیَکُون ‌ست، نه موقوفِ علل

نَفَخْتُ: دمیدم
....

== یابی اندر دید او کل غرض

audio::media/audio/yabi_andar_dide_oo_kolle_gharaz.mp3[controls]

.برنامه ۷۹۷، مولوی، مثنوی، دفتر اول، بیت ۹۲۱
[.poem]
....
دیده ما چون بسی علّت دروست
رو فنا کُن دید خود در دید دوست

دید ما را دید او نِعْمَ الْعِوَض
یابی اندر دید او کل غَرَض
....

== شما مسئول مداومت تعهدتون هستید

audio::media/audio/shoma_masoule_modavemate_taahodetoon_hastid.mp3[controls]

.برنامه ۷۹۷، مولوی، مثنوی، دفتر پنجم، بیت ۱۲۱۱
[.poem]
....
شرع بهرِ دفعِ شَرّ رایی زند
دیو را در شیشهٔ حجّت کند
....

== از میان نردبان نگریختم

audio::media/audio/az_mian_nardeban_nagrikhtam.mp3[controls]

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۶۵۸
[.poem]
....
عاشقم، از عاشقان نگریختم
وز مَصاف ای پهلوان، نگریختم

حمله بردم سوی شیران همچو شیر
همچو روبه از میان نگریختم

قصدِ بامِ آسمان می داشتم
از میانِ نردبان نگریختم

چونکه من دارو بدم هر درد را
از صُداعِ این و آن نگریختم

هیچ دیدی دارو کز دردی گریخت؟
داروَم من، همچنان نگریختم

پیروِ پیغامبران بودم به جان
من ز تهدیدِ خَسان نگریختم

زنده کوشم در شکارِ زندگی
زنده باشم، چون ز جان نگریختم

چشمِ تیراندازش آنگه یافتم
که ز تیرِ خَرکمان نگریختم

زخمِ تیغ و تیرِ من منصور شد
چون که از زخمِ سِنان نگریختم

بحرِ قندم، از تُرُش باکیم نیست
سودمندم، از زیان نگریختم

شمسِ تبریزی چو آمد آشکار
ز آشکارا و نهان نگریختم
....

== آدمى را در رنج و محنت بيافريده‌ايم

audio::media/audio/adami_ra_dar_ranj_o_mehnat_biafaride_im.mp3[controls]

.برنامه ۷۹۷، قرآن کریم، سوره بلد(۹۰)، آیه ۱۲-۱
[.poem]
....
لَا أُقْسِمُ بِهَٰذَا الْبَلَدِ
قسم به اين شهر.

وَأَنْتَ حِلٌّ بِهَٰذَا الْبَلَدِ
و تو در اين شهر سكنا گرفته‌اى.

وَوَالِدٍ وَمَا وَلَدَ
و قسم به پدر و فرزندانى كه پديد آورد.

لَقَدْ خَلَقْنَا الْإِنْسَانَ فِي كَبَدٍ
كه آدمى را در رنج و محنت بيافريده‌ايم.

أَيَحْسَبُ أَنْ لَنْ يَقْدِرَ عَلَيْهِ أَحَدٌ
آيا مى‌پندارد كه كس بر او چيره نگردد؟

يَقُولُ أَهْلَكْتُ مَالًا لُبَدًا
مى‌گويد: مالى فراوان را تباه كردم.

أَيَحْسَبُ أَنْ لَمْ يَرَهُ أَحَدٌ
آيا مى‌پندارد كه كسى او را نديده است؟

أَلَمْ نَجْعَلْ لَهُ عَيْنَيْنِ
آيا براى او دو چشم نيافريده‌ايم؟

وَلِسَانًا وَشَفَتَيْنِ
و يك زبان و دو لب؟

وَهَدَيْنَاهُ النَّجْدَيْنِ
و دو راه پيش پايش ننهاديم؟

فَلَا اقْتَحَمَ الْعَقَبَةَ
و او در آن گذرگاه سخت قدم ننهاد.

وَمَا أَدْرَاكَ مَا الْعَقَبَةُ
و تو چه دانى كه گذرگاه سخت چيست؟
....

== خدا به مرکز همانیده حمله میکنه

audio::media/audio/khoda_be_markaze_hamanide_hamle_mikone.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر دوم، بیت شماره ۱۳۰۰
[.poem]
....
این جهان چون خَس به دستِ بادِ غیب
عاجزی پیشه گرفت و دادِ غیب

عاجزی پیشه گرفت: ناتوانی را پیشه خود ساخته است.
دادِ غیب: قدرت تصرّف عالم غیب.

گه بلندش می‌کند، گاهیش پَست
گه دُرستش می‌کند، گاهی شِکست

گه یَمینش می‌برد، گاهی یَسار
گه گلستانش کند، گاهیش خار

یَمین: دست راست.
یَسار: دست چپ.

دست پنهان و، قلم بین خطْ ‌گُزار
اسب در جَوْلان و، ناپیدا سوار

تیر، پَرّان بین و ناپیدا کمان
جان ها پیدا و پنهان، جانِ جان

تیر را مَشْکَن که آن تیرِ شَهی است
نیست پَرتاوی، ز شَصْت آگهی است

ما رَمَیْتَ اِذْ رَمَیْتَ گُفت حق
کارِ حق بر کارها دارد سَبَق

قرآن کریم، سوره انفال (۸)، آیه ١٧
وَمَا رَمَيْتَ إِذْ رَمَيْتَ وَلَٰكِنَّ اللَّهَ رَمَىٰ
و آنگاه كه تير مى‌انداختى، تو تير نمى‌انداختى، خدا بود كه تير مى‌انداخت

خشمِ خود بشکن، تو مشکن تیر را
چشمِ خشمت خون شمارد شیر را

بوسه دِه بر تیر و پیشِ شاه بَر
تیرِ خونْ‌آلود از خونِ تو تَر

آنچه پیدا عاجز و بسته زبون
وآنچه ناپیدا، چنان تند و حَرون

حرون: سرکش، نافرمان

ما شکاریم، این چنین دامی که راست؟
گُویِ چوگانیم، چُوگانی کجاست؟

چُوگانی: اسبی که مناسب و لایق چوگان بازی باشد، چوگان

وگر به خشم روی صدهزار سال ز من
به‌ عاقبت به من آیی که منتهات منم

می‌دَرَد، می‌دوزد، این خَیّاط کو؟
می‌دمد، می‌سوزد، این نَفّاط کو؟

نَفّاط: ظرف مسین که در آن نفت ریزند، نفت انداز و آتش باز، آتش افروز
....

.مولوی، مثنوی، دفتر سوم، بیت ۱۹۰۶
[.poem]
....
چون قضای حق رضایِ بنده شُد
حُکمِ او را  بندهٔ خواهَنده شُد
....

.مولوی، مثنوی، دفتر دوم، بیت ۲۵۴۴
[.poem]
....
لیک مومن دان که طَوْعاً ساجِدَست
زآنکه جویایِ رضا و قاصِدَست

طَوْعاً: با ميل، با رغبت
ساجد: سجده كننده
....

.مولوی، مثنوی، دفتر دوم، بیت ۵۹۰
[.poem]
....
گر گریزی بر امیدِ راحتی
ز آن طرف هم پیشت آید آفتی

هیچ کُنجی بی دَد و بی دام نیست
جز به خلوت گاهِ حق، آرام نیست
....

== شکر برای طوفان

audio::media/audio/shokr_baraye_toofan.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر سوم، بیت شماره ۱۳۴۷
[.poem]
....
شُکر، طوفان را کنون بگماشتی
واسطهٔ اَطلال را برداشتی

زآنکه اَطلالِ لَئیم و بَد بُدند
نِی ندایی، نِی صدایی می‌زدند

من چنان اَطلال خواهم در خَطاب
کَز صدا چون کوه واگوید جواب

تا مُثنّا بشنوم من نامِ تو
عاشقم بَر نامِ جانْ آرامِ تو
....

.مولوی، دیوان شمس، غزل شمارهٔ ۲۰
[.poem]
....
پیش از تو خامانِ دگر، در جوشِ این دیگِ جهان
بس برطپیدند و نشد، درمان نبود الّا رضا
....

.مولوی، مثنوی، دفتر سوم، بیت شماره ۱۳۱۱
[.poem]
....
هین مکن، کین موجِ طوفانِ بلاست
دست و پا و آشنا، امروز لاست

بادِ قهرست و بلایِ شمع کُش
جز که شمعِ حق نمی‌پاید، خَمُش

گفت: نی، رفتم بَر آن کوهِ بلند
عاصِم ست آن کُه مرا از هر گزند

عاصِم: نگهدارنده، حفظ کننده
....

.قرآن کریم، سوره هود(۱۱)، آیه۴۳
[.poem]
....
« قَالَ سَآوِي إِلَىٰ جَبَلٍ يَعْصِمُنِي مِنَ الْمَاءِ ۚ قَالَ لَا عَاصِمَ الْيَوْمَ مِنْ أَمْرِ اللَّهِ إِلَّا مَنْ رَحِمَ ۚ وَحَالَ بَيْنَهُمَا الْمَوْجُ فَكَانَ مِنَ الْمُغْرَقِينَ »

« گفت: من بر سر كوهى كه مرا از آب نگه دارد، جا خواهم گرفت. گفت: امروز هيچ نگهدارنده‌اى از فرمان خدا نيست مگر كسى را كه بر او رحم آورد. ناگهان موج ميان آن دو حايل گشت و او از غرق‌شدگان بود.»

هین مکن، که کوه کاه است این زمان
جز حبیبِ خویش را ندْهد امان

گفت: من، کی پندِ تو بشنوده‌ام؟
که طمع کردی که من زین دُوده‌ام

دُوده: دودمان، خانواده
....

.قرآن کریم، سوره هود(۱۱)، آیه ۴۵
[.poem]
....
«…إِنَّ ابْنِي مِنْ أَهْلِي…»
«…پسرم از خاندان من بود…»

خوش نیامد گفتِ تو هرگز مرا
من بَرّی‌ام از تو در هر دو سرا

هین مکن بابا که روزِ ناز، نیست
مر خدا را خویشی و انباز نیست

تا کنون کردیّ و، این دَم نازُکی ست
اندرین درگاه، گیرا نازِ کیست؟

لَمْ یَلِدْ لَمْ یُولَدْ است او از قِدَم
نی پدر دارد، نه فرزند و، نه عم

نازُکی: دقیق، خطیر، مهم
قِدَم: ازل
....

.قرآن کریم، سوره اخلاص (۱۱۲)، آیه ۳
[.poem]
....
« لَمْ يَلِدْ وَلَمْ يُولَدْ »
« نه زاده است و نه زاده شده »

نازِ فرزندان کجا خواهد کشید؟
نازِ بابایان کجا خواهد شنید؟

نیستم مولود، پیرا کم بناز
نیستم والد، جوانا کم گُراز

نیستم شوهر، نیَم من شهوتی
ناز را بگذار، اینجا ای سِتی

جز خضوع و بندگیّ و اضطرار
اندرین حضرت ندارد اعتبار

گفت: بابا سال ها این گفته‌‌یی
باز می‌گویی، به جهل آشفته‌یی

گُرازیدن: نازیدن، با ناز و تکبّر راه رفتن
سِتی: مطلق زن، بی بی، بانو
....

== آتش آب توست

audio::media/audio/atash_ab_toost.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر پنجم، بیت شماره ۴۳۳
[.poem]
....
جَوْق‌ْجَوْق و صَفْ صَف از حرص و شِتاب
مُحْتَرِِز ز آتش، گُریزان سویِ آب

لاجَرَم ز آتش برآوردند سر
ِاعْتِبارَالْاِعْتِبار ای بی‌خبر

بانگ می‌زد آتش ای گیجانِ گول
من نِیَ ام آتش، منم چشمهٔ قبول

چشم‌ْبندی کرده‌اند ای بی‌نَظَر
در من آی و هیچ مَگْریز از شَرَر

ای خلیل اینجا شَرار و دود نیست
جز که سِحْر و خُدْعهٔ نمرود نیست

چون خلیلِ حق اگر فرزانه‌ای
آتش آبِ توست و تو پروانه‌ای

جَوْق‌ْجَوْق: دسته دسته، جمع آن اَجْواق است.
مُحْتَرِِز: دوری کننده، پرهیز کننده
اعتباراَلِْاعتبار: عبرت بگیر، عبرت بگیر.
گول: ابله، نادان
شَرار: پاره آتشی که به هوا جهد، جرقه
....

== عواملی که سبب میشود تغییر دادن خود سخت شود و انسان دچار جبر من ذهنی بشود

=== ندیدن ایراد در خود

عدم احساس نیاز به آموزش معنوی، ندیدنِ ایراد در خود و تلاش نکردن برای رفعِ ایراد.

audio::media/audio/nadidane_irad_dar_khod.mp3[controls]

.برنامه ۹۰۳، مولوی، مثنوی، دفتر سوم، بیت ۲۶۷۷
[.poem]
....
انبیا گفتند: در دل علّتی‌ست
که از آن در حق‌شناسی آفتی‌ست

علّت: بیماری، مرض
....

.مولوی، مثنوی، دفتر اول، بیت ۳۲۱۲
[.poem]
....
هر که نقصِ خویش را دید و شناخت
اندر اِستِکمال خود، دواسبه تاخت

زآن نمی‌پَرّد به سویِ ذوالْجَلال
کو گُمانی می‌بَرَد خود را کمال

اِستِکمال: به کمال رسانیدن، کمال خواهی
دو اسبه تاختن: کنایه از شتاب کردن و به شتاب رفتن
....

.مولوی، مثنوی، دفتر پنجم، بیت ۲۰۶۳
[.poem]
....
تا به دیوارِ بلا نآید سَرش
نشنود پندِ دل آن گوشِ کرش
....

.مولوی، مثنوی، دفتر سوم، بیت ۲۹۹۶
[.poem]
....
ساخت موسی قدس در، بابِ صَغیر
تا فرود آرند سر قومِ زَحیر

زآنکه جَبّاران بُدند و سرفراز
دوزخ آن بابِ صغیر است و نیاز

قوم زَحیر: مردم بیمار و آزاردهنده
جَبّار: ستمگر، ظالم
....

.مولوی، مثنوی، دفتر پنجم، بیت ۵۴۴
[.poem]
....
ناز کردن خوش‌تر آید از شِکَر
لیک، کم خایَش، که دارد صد خطر

ایمن‌آباد است آن راهِ نیاز
ترکِ نازش گیر و با آن ره بساز
....

.حافظ، دیوان غزلیات، غزل شمارهٔ ۶۳
[.poem]
....
عاشق که شد که یار به حالش نظر نکرد؟
ای خواجه درد نیست وگرنه طبیب هست
....

=== عدمِ تحمّلِ دردِ هوشیارانه

پوشانیدنِ دردهای خود و بی‌حس کردنِ خود نسبت به دردی که در زیر نهفته است از طریق مشغولیت‌های
بیهوده و کارافزا، و یا پریدن از فکری به فکرِ دیگر، و همینطور عدمِ تحمّلِ دردِ هوشیارانه.

audio::media/audio/adame_tahammole_darde_hoshyarane.mp3[controls]

.مولوی، مثنوی، دفتر دوم، بیت ۲۲۶۴
[.poem]
....
آن بهاران مُضمَرست اندر خزان
در بهارست آن خزان، مگْریز از آن

همرهِ غم باش، با وحشت بساز
می‌طلب در مرگِ خود عُمرِ دراز

آنچه گوید نفسِ تو کاینجا بَدَست
مَشنَوَش چون کارِ او ضد آمده‌ست

تو خلافش کُن که از پیغمبران
این چنین آمد وصیّت در جهان

مُضمَر: پنهان کرده شده، پوشیده
....

.مولوی، دیوان شمس، غزل شمارهٔ ۳۰۹۰
[.poem]
....
ز بهر پختنِ تو آتشی‌ست روحانی
چو پس جَهی چو زنان، خامِ قَلتَبان باشی

قَلتَبان: بی‌ غیرت
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۴۲
[.poem]
....
آن زِ دور آتش نمایَد، چون رَوی نوری بُوَد
همچنان که آتشِ موسی برای ابتلا

اَلصَّلا پروانه جانان قصدِ آن آتش کُنید
چون بلی گفتید اوَّل، دَر رَوید اندر بَلا

چون سَمَنْدَر در میانِ آتشَش باشد مُقام
هرکه دارد در دل و جان، اینچنین شوق و وَلا

پروانه جانان: عاشقان، پروانه صفتان
سَمندَر: جانوری خزنده که گفته اند در آتش نمی‌سوزد
وَلا: محبّت، دوستی
....

.قرآن کریم، سورهٔ طه (۲۰)، آیهٔ ۹
[.poem]
....
«وَهَلْ أَتَاكَ حَدِيثُ مُوسَىٰ.»
«آيا خبرِ موسى به تو رسيده است؟»
....

.قرآن کریم، سورهٔ اعراف (۷)، آیهٔ ۱۷۲
[.poem]
....
«…أَلَسْتُ بِرَبِّكُمْ ۖ قَالُوا بَلَى…»
«…آيا من پروردگارتان نيستم؟…»
....

.مولوی، مثنوی، دفتر سوم، بیت ۴۲۱۸
[.poem]
....
ای برادر من بر آذر چابُکم
من نه آن جانم که گَردم بیش و کم

آذر: آتش
....

.مولوی، مثنوی، دفتر اول، بیت ۳۰۰۲
[.poem]
....
ای برادر، صبر کُن بر دردِ نیش
تا رهی از نیشِ نفسِ گَبرِ خویش

دردِ نیش: كنايه از مجاهده با نفس و رياضت است
....

.مولوی، مثنوی، دفتر اول، بیت ۳۰۰۵
[.poem]
....
چون دلش آموخت شمع‌ْافروختن
آفتاب او را نیارد سوختن

گفت حق در آفتابِ مُنْتَجِم
ذکرِ تَزّاوَر، کَذیٰ عَنْ کَهْفِهِمْ

خار، جمله لطف، چون گُل می‌شود
پیشِ جزوی، کو سویِ کُلّ می‌رود
....

.قرآن کریم، سورهٔ کهف (۱۸)، آیهٔ ۱۷
[.poem]
....
«وَتَرَى الشَّمْسَ إِذَا طَلَعَتْ تَزَاوَرُ عَنْ كَهْفِهِمْ ذَاتَ الْيَمِينِ وَإِذَا غَرَبَتْ
تَقْرِضُهُمْ ذَاتَ الشِّمَالِ وَهُمْ فِي فَجْوَةٍ مِنْهُ…»

«و خورشيد را مى‌بينى كه چون برمى‌آيد، از غارشان به جانبِ
راست ميل مى‌كند و چون غروب كند ايشان را واگذارد و به
چپ گردد. و آنان در صحنهٔ غارند.»
....

=== تغییر از شما باید شروع بشه

دچار جبرِ منِ ذهنی شدن با عدم اعتقاد به این مسئله که می‌توان خود را
تغییر داد و از این دردها رها شد. تصوّرِ اینکه قضا و سرنوشتِ ما در این است
که همیشه این زندگیِ پر درد را ادامه دهیم و راهی برای رهاییِ ما وجود ندارد.

audio::media/audio/taghyir_az_shoma_bayad_shoroo_beshe.mp3[controls]

.مولوی، مثنوی، دفتر اول، بیت ۱۰۶۸
[.poem]
....
هر که مانْد از کاهلی بی‌شُکر و صبر
او همین داند که گیرد پایِ جَبر

هر که جبر آورد، خود رنجور کرد
تا همان رنجوری‌اش، در گور کرد

کاهلی: تنبلی
رنجور: بیمار
....

.مولوی، مثنوی، دفتر پنجم، بیت ۳۱۸۷
[.poem]
....
ترک کن این جبر را که بس تُهی‌ست
تا بدانی سِرِّ سِرِّ جبر چیست

ترک کن این جبرِ جمعِ مَنبَلان
تا خبر یابی از آن جبرِ چو جان

مَنبَل: تنبل، کاهل، بیکار
....

=== عدمِ صدق در این راه

audio::media/audio/adame_sedgh_dar_in_rah.mp3[controls]

.مولوی، مثنوی، دفتر ششم، بیت ۳۵۵
[.poem]
....
چون نبودش تخمِ صدقی کاشته
حق بَرو نسیانِ آن بگماشته

گرچه بر آتش‌زنه‌ی دل می‌زند
آن سِتارَه‌‌ش را کفِ حق می‌کُشد

آتش‌زنه: سنگِ چخماق
....

=== عدم طلب حقیقی

audio::media/audio/adame_talabe_haghighi.mp3[controls]

.مولوی، مثنوی، دفتر سوم، بیت ۹۷۹
[.poem]
....
در طلب زن دایماً تو هردو دست
که طلب در راه، نیکو رهبر است
....

.مولوی، مثنوی، دفتر پنجم، بیت ۲۳۸۵
[.poem]
....
گفت پیغمبر که: بر رزق ای فتا
در فرو بسته‌ست و بر در قفل‌ها

جنبش و آمد شدِ ما و اکتساب
هست مِفتاحی بر آن قفل و حجاب

بی‌کلید، این در گشادن راه نیست
بی‌طلب، نان سنّتِ اَلله نیست

فَتا: همان فتی است به معنیِ جوان، جوانمرد
....

.مولوی، مثنوی، دفتر پنجم، بیت ۱۷۳۴
[.poem]
....
کین طلب در تو گروگانِ خداست
زآنکه هر طالب به مطلوبی سزاست

جهد کن تا این طلب افزون شود
تا دلت زین چاهِ تن بیرون شود
....

== استثنا کنید

audio::media/audio/estesna_konid.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر سوم، بیت ۱۶۳۷
[.poem]
....
مدتی بر نذرِ خود بودش وفا
تا درآمد امتحاناتِ قضا

زین سبب فرمود: استثنا کنید
گر خدا خواهد به پیمان بر زنید

هر زمان دل را دگر مَیلی دهم
هر نَفَس بر دل دگر داغی نهم

کُلُّ اَصْباحٍ لَناٰ شَأْنٌ جَدید
کُلُّ شَیءٍ عَنْ مُرادی لایَحید

در هر بامداد کاری تازه داریم، و هیچ کاری از حیطهٔ مشیت من خارج نمی‌شود.
استثنا کنید: ان‌شاءالله بگویید، اگر خدا بخواهد بگویید.
....

.قرآن کریم، سورهٔ الرحمن (۵۵)، آیهٔ ۲۹
[.poem]
....
يَسْأَلُهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ ۚ كُلَّ يَوْمٍ هُوَ فِي شَأْنٍ.
هر كس كه در آسمانها و زمين است سائل درگاه اوست، و او هر لحظه در كارى جدید است.
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۲۲۷
[.poem]
....
هر لحظه و هر ساعت یک شیوهٔ نو آرد
شیرین‌تر و نادرتر زان شیوه‌ی پیشینش
....

== اگر قبول دارید عمل کنید روی خودتون کار کنید

audio::media/audio/agar_ghabool_darid_amal_konid_roye_khodetoon_kar_konid.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر پنجم، بیت ۱۳۶۵
[.poem]
....
میلِ شهوت، کر کند دل را و کور
تا نماید خر چو یوسف، نار نور

ای بسا سرمستِ نار و نارجو
خویشتن را نورِ مطلق داند او

جز مگر بندهٔ خدا، یا جذبِ حق
با رهش آرَد، بگردانَد ورق

تا بداند کآن خیالِ ناریه
در طریقت نیست اِلّا عاریه

نارِیه: آتشین
عاریه: قرضی
....

== رحمت خدا فقط بستگی به فضاگشایی ما در این لحظه داره نه به گذشتمون

audio::media/audio/rahmate_khoda_faghat_bastegi_be_fazagoshaei_ma_dar_in_lahze_dare_na_be_gozashtemoon.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر دوم، بیت ۳۷۸۵
[.poem]
....
چشمِ او مانده‌ست در جُویِ روان
بی‌خبر از ذوقِ آبِ آسمان

مَرْکبِ هِمّت سویِ اسباب راند
از مُسَبِّب لاجَرَم محروم ماند

آنکه بیند او مُسَبِّب را عیان
کِی نهد دل بر سبب‌هایِ جهان؟
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۱۵۳
[.poem]
....
تو ز طفلی چون سبب‌ها دیده‌يی
در سبب، از جهل بر چفسیده‌‌يی

با سبب‌ها از مُسبِّب غافلی
سویِ این روپوش‌ها ز آن مایلی

چون سبب‌ها رفت، بَر سَر می‌زنی
ربَّنا و ربَّناها می‌کُنی

ربّ می‌گوید: برو سویِ سبب
چون ز صُنعم یاد کردی؟ ای عجب

گفت: زین پس من تو را بینم همه
ننگرم سویِ سبب و آن دَمدَمه

گویدش: رُدُّوا لَعادُوا، کارِ توست
ای تو اندر توبه و میثاق، سُست

چفسیده‌‌يی: چسبیده‌ای
صُنع: آفرینش، آفریدن، عمل، کار، نیکی کردن، احسان
دَمدَمه: شهرت، آوازه، مکر و فریب
رُدُّوا لَعادُوا: اگر آنان به این جهان برگردانده شوند، دوبار به آنچه که از آن نهی شده‌اند، باز گردند.
....

.قرآن كريم، سورهٔ انعام (۶)، آيهٔ ٢٨
[.poem]
....
« بَلْ بَدَا لَهُمْ مَا كَانُوا يُخْفُونَ مِنْ قَبْلُ ۖ وَلَوْ رُدُّوا لَعَادُوا لِمَا نُهُوا عَنْهُ وَإِنَّهُمْ لَكَاذِبُونَ. »

« بلکه آنچه را که زین پیش پوشیده می‌داشتند بر آنان آشکار شود، و اگر آنان بدین جهان باز آورده شوند،
دوباره بدانچه از آن نهی شده اند بازگردند. و البته ایشان‌اند دروغ زنان. »

لیک من آن ننگرم، رحمت کنم
رحمتم پُرّست، بر رحمت تنم

ننگرم عهدِ بَدت، بِدْهم عطا
از کرم، این دَم چو می‌خوانی مرا
....

== رحمت ها به صورت بی مرادی میان

audio::media/audio/rahmat_ha_be_soorate_bi_moradi_miyan.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر پنجم، بیت ۳۶۴۴
[.poem]
....
هست مهمان‌خانه این تَن ای جوان
هر صباحی ضَیفِ نو آید دوان

هین مگو کین مانند اندر گردنم
که هم‌اکنون باز پَرَّد در عَدم

هرچه آید از جهان غَیب‌وَش
در دلت ضَیف است، او را دار خَوش

ضَیف: مهمان
....

.مولوی، مثنوی، دفتر ششم، بیت ١۶۴٣
[.poem]
....
لیک حاضر باش در خود، ای فتیٰ
تا به خانه او بیابد مر تو را

ورنه خِلْعَت را بَرَد او بازپس
که نیابیدم به خانه‌ هیچ‌کس

فَتیٰ: جوان‌مرد، جوان
خِلْعَت: لباس یا پارچه‌ای که خانوادهٔ داماد به عروس یا خانوادهٔ او هدیه می‌دهند، مجازاً هدیه
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۷۳۴
[.poem]
....
چونکه قَبضی آیدت ای راه‌رو
آن صَلاحِ توست، آتَش‌دل مشو

قَبض: گرفتگی، دلتنگی و رنج
آتش‌دل: دلسوخته، ناراحت و پریشان حال
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۶۲
[.poem]
....
قبض دیدی چارهٔ آن قبض کن
زآنکه سَرها جمله می‌رویَد زِ بُن

بسط دیدی، بسطِ خود را آب دِه
چون برآید میوه، با اصحاب دِه
....

.مولوی، مثنوی، دفتر اوّل، بیت ٢۶٧٠
[.poem]
....
حکمِ حق گُسترد بهر ما بِساط
که بگویید از طریقِ اِنبساط

بِساط: هر چیز گستردنی مانند فرش و سفره
....

== خروب

audio::media/audio/kharoob.mp3[controls]

.برنامه ۹۹۷، مولوی، مثنوی، دفتر چهارم، بیت ۱۳۸۳
[.poem]
....
مسجدست آن دل، که جسمش ساجدست
یارِ بَد خَرُّوبِ هر جا مسجدست

یارِ بَد چون رُست در تو مِهرِ او
هین ازو بگریز و کم کن گفت‌وگو

برکَن از بیخش، که گر سَر برزند
مر تو را و مسجدت را برکَنَد

عاشقا، خَرّوبِ تو آمد کژی
همچو طفلان، سویِ کژ چون می‌غژی؟

خَرُّوب: گیاه خَرنُوب که بوته‌ای بیابانی و مرتفع و خاردار است و در هر بنایی بروید آن را ویران می‌کند.
می‌غژی: فعل مضارع از غژیدن، به معنی خزیدن بر شکم مانند حرکت خزندگان و اطفال.
....

.مولوی، مثنوی، دفتر چهارم، بیت ۱۳۷۷
[.poem]
....
گفت: اندر تو چه خاصیّت بُوَد؟
گفت: من رُستَم، مکان ویران شود

رُستَن: روییدن
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۸۵
[.poem]
....
چون چنین وسواس دیدی، زود زود
با خدا گَرد و، درآ اندر سجود
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۸۷
[.poem]
....
آن زمان کِت امتحان مطلوب شد
مسجدِ دینِ تو، پُر خَرُّوب شد
....

.مولوی، مثنوی، دفتر پنجم، بیت ۵۵۰
[.poem]
....
چون زِ زنده مُرده بیرون می‌کُنَد
نَفْسِ زنده سویِ مرگی می‌تَنَد
....

== آینده لازم نیست امتداد گذشته باشه

audio::media/audio/ayande_lazem_nist_emtedad_gozashte_bashe.mp3[controls]

.برنامه ۹۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۶۱۱
[.poem]
....
ز درم راه نباشد، ز سرِ بام و دریچه
سَتَرَ اللهُ عَلَیْنٰا چه عَلالایِ تو دارم

سَتَرَ اللهُ عَلَیْنٰا: خداوند بر ما پوشانید
عَلالا: بانگ و فریاد، هیاهو، سروصدا
....

.مولوی، دیوان شمس، غزل شمارهٔ ۵۸۲
[.poem]
....
خُنُک جانی که بر بامَش همی چوبَک زَنَد امشب
شود همچون سَحَر خندان، عَطایِ بی ‌عدد بیند

چوبَک زدن: پاسبانی کردن، نگهبانی کردن
....

.مولوی، دیوان شمس، غزل شمارهٔ ۷۷۱
[.poem]
....
دل تو مثالِ بام است و، حواسْ ناودان‌ها
تو ز بام آب می‌خور که چو ناودان نماند

جامِ مُباح آمد، هین نوش کُن
بازرَه از غابر و از ماجَرا

مُباح: حلال، جامِ مُباح: شرابِ حلال
غابر: گذشته

خفته از احوال دنیا روز و شب
چون قلم در پنجه تقلیب رب

تقلیب: برگردانیدن، واژگونه کردن

ای عاشق جریده، بر عاشقان گزیده
بگذر ز آفریده، بنگر در آفریدن

جریده: یگانه، تنها

هر لحظه و هر ساعت یک شیؤە نو آرد
شیرینتر و نادرتر زآن شیؤە پیشینش

بر گذشته حسرت آوردن خطاست
باز نآید رفته، یاِد آن هباست

هبا: مخفف هباء به معنی گرد و غبار پراکنده. در اینجا به معنی بیهوده است
....

== شکر کافیه

audio::media/audio/shokr_kafie.mp3[controls]

.برنامه ۹۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۲۵۷
[.poem]
....
صورتِ اقبالِ شکَرریز گفت:
شُکر چو کم نیست، شکایت چرا؟

اقبال: بخت، كنايه از تجلّی خداوند

بادْ تُند است و چراغم اَبْتری
زو بگیرانم چراغِ دیگری

اَبْتَر: ناقص و به دردنخور

لذّتِ بی‌کرانه‌ای‌ست، عشق شده‌ست نام او
قاعده خود شکایت است، ورنه جفا چرا بُوَد؟
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۵۱۷
[.poem]
....
کافیَم، بدْهم تو را من جمله خیر
بی‌سبب، بی‌واسطهٔ یاریِ غیر

کافیَم بی‌نان تو را سیری دهم
بی‌سپاه و لشکرت میری دهم

بی‌بهارت نرگس و نسرین دهم
بی‌کتاب و اوستا تلقین دهم

کافیَم بی‌داروَت درمان کنم
گور را و چاه را میدان کنم
....

== در خودتون و دیگران زندگی رو ببینید

audio::media/audio/dar_khodetoon_va_digaran_zendegi_ro_bebinid.mp3[controls]

.برنامه ۱۰۰۰، مولوی، دیوان شمس، غزل شمارهٔ ۵۱
[.poem]
....
گر تو ملولی ای پدر، جانبِ یارِ من بیا
تا که بهارِ جان‌ها تازه کند دلِ تو را

بویِ سلامِ یارِ من، لَخْلَخهٔ بهارِ من
باغ و گُل و ثِمارِ من، آرَد سویِ جان، صبا

مستی و طُرفه مستی‌ای، هستی و طُرفه هستی‌ای
مُلک و درازدَستی‌ای، نعره‌زنان که: «اَلصَّلا»

پای بکوب و دست زن، دست در آن دو شَسْت زن
پیشِ دو نرگسِ خوشش کُشته نگر دلِ مرا

لَخْلَخه: ترکیبی از عطرها و بوهای خوش
ثِمار: جمعِ ثمر، میوه‌ها
طُرفه: عجیب، شگفت
درازدَستی‌: تجاوز، دست‌اندازی، چشم‌داشت و طمع داشتن
اَلصَّلا: دعوتِ عمومی
شَسْت: قُلّاب ماهیگیری، «دو شَسْت» کنایه از موی جلوی سر است که به دو بخش تقسیم شود و بافته گردد.
....

== ینظر بنورالله

audio::media/audio/yanzoro_benoorollah.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر دوم، بیت ۱۵۶۷
[.poem]
....
شیخ کو یَنْظُر بِنورِالله شد
از نهایت، وز نخست آگاه شد

حدیث
«اِتَّقُوا فَراسَةَ الْمُؤمِنِ فَاَنَّهُ يَنْظُرُ بِنُورِاللهِ.»
«بترسید از زیرکیِ مؤمن که او با نور ِخدا می‌بیند.»
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۵۰۱
[.poem]
....
اوّل و آخِر تویی ما در میان
هیچ هیچی که نیاید در بیان

«همانطور که عظمت بی‌نهایت الهی قابل بیان نیست و باید به آن زنده شویم، ناچیزی ما هم به عنوان من ذهنی
قابل بیان نیست و ارزش بیان ندارد. باید هر چه زودتر آن را انکار کنیم و به او زنده شویم.»
....

.قرآن کریم، سورهٔ حدید (۵۷)، آیهٔ ۳
[.poem]
....
«هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ.»
«اوست اوّل و آخر و ظاهر و باطن، و او به هر چيزى داناست.»
....

== اگر کسی برای خدا باشد خدا هم برای اوست

audio::media/audio/agar_kasi_baraye_khoda_bashad_khoda_ham_baraye_oust.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر اوّل، بیت ۱۹۳۷
[.poem]
....
گفته او را من زبان و چشمِ تو
من حواس و من رضا و خشمِ تو

رُو که بی‌یَسْمَع و بی‌یُبصِر توی
سِر تُوی، چه جایِ صاحب‌سِر تُوی

چون شدی مَنْ کٰانَ‌ لِلَّـه از وَلَه
من تو را باشم،‌ که کٰانَ الله لَه

بی‌یَسْمَع و بی‌یُبصِر: به وسیلهٔ من می‌شنود و به وسیلهٔ من می‌بیند
وَلَه: حیرت
....

.مولوی، مثنوی، دفتر دوم، بیت ١۵٠٢
[.poem]
....
خویش را تسلیم کن بر دامِ مُزد
وانگه از خود بی زِ خود چیزی بدُزد
....

.مولوی، مثنوی، دفتر ششم، بیت ۳۴۹٢
[.poem]
....
دست، کورانه بِحَبْلِ الله زن
جز بر امر و نهیِ یزدانی مَتَن
....

.قرآن کریم، سورهٔ آل عمران (۳)، آیهٔ ۱۰۳
[.poem]
....
وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا...
و همگان دست در ریسمان خدا زنید و پراکنده مشوید...
....

== خدا توبه پذير و مهربان است

audio::media/audio/khoda_tobe_pazir_va_mehraban_ast.mp3[controls]

.برنامه ۱۰۰۰، قرآن کریم، سورهٔ حجرات (۴۹)، آیهٔ ۱۲
[.poem]
....
يَا أَيُّهَا الَّذِينَ آمَنُوا اجْتَنِبُوا كَثِيرًا مِنَ الظَّنِّ إِنَّ بَعْضَ الظَّنِّ إِثْمٌ ۖ وَلَا تَجَسَّسُوا وَلَا يَغْتَبْ
بَعْضُكُمْ بَعْضًا ۚ أَيُحِبُّ أَحَدُكُمْ أَنْ يَأْكُلَ لَحْمَ أَخِيهِ مَيْتًا فَكَرِهْتُمُوهُ ۚ وَاتَّقُوا اللهَ ۚ إِنَّ اللهَ تَوَّابٌ رَحِيمٌ

اى كسانى كه ايمان آورده‌ايد، از گمان فراوان بپرهيزيد.
زيرا پاره‌اى از گمانها در حد گناه است. و در كارهاى پنهانى يكديگر جست و جو مكنيد.
و از يكديگر غيبت مكنيد. آيا هيچ يک از شما دوست دارد كه گوشت برادر مردهٔ خود را بخورد؟
پس آن را ناخوش خواهيد داشت. و از خدا بترسيد، زيرا خدا توبه‌پذير و مهربان است.

چون ز غیبت، وَاکْلِ لَحْمِ مردمان
شصت سالت سیریی نآمد از آن؟

اَکْل: خوردن
لَحْم: گوشت
....

== در این لحظه چاره ای به جز تسلیم و رضا نداریم

audio::media/audio/dar_in_lahze_chare_i_be_joz_taslim_va_reza_nadarim.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر ششم، بیت ۵۷۶
[.poem]
....
ای رفیقان، راهها را بست یار
آهویِ لنگیم و او شیرِ شکار

جز که تسلیم و رضا کو چاره‌ای؟
در کفِ شیرِ نرِ خون‌خواره‌ای

او ندارد خواب و خور، چون آفتاب
روح‌ها را می‌کند بی‌خورد و خواب
....

.قرآن کریم، سورهٔ بقره (۲)، آیهٔ ۲۵۵
[.poem]
....
«اللهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ… .»

«الله خدايى است كه هيچ خدايى جز او نيست. زنده و پاينده است.
نه خواب سبك او را فرا مى‌گيرد و نه خواب سنگين… .»
....

.قرآن کریم، سورهٔ انعام (۶)، آیهٔ ۱۴
[.poem]
....
«… وَهُوَ يُطْعِمُ وَلَا يُطْعَمُ ۗ … .»
«… و مى‌خوراند و به طعامش نياز نيست… .»

که بیا من باش یا همخویِ من
تا ببینی در تجلّی رویِ من

حديث
«تَخَلَّقوا بِأَخلاقِ الله»
«من در باطن كسی تجلی خواهم کرد که خوی الهی بپذیرد
و از خوی و عادت مادی و حیوانی دوری کند.»
....

== درد و چالش سبب فضاگشایی هستن

audio::media/audio/dard_va_chalesh_sabab_fazagoshaei_hastan.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر ششم، بیت ۴۲۹۹
[.poem]
....
درد، دارویِ کهن را نَوْ کند
درد، هر شاخِ ملولی خَوْ کند

کیمیایِ نوکننده، دردهاست
کو ملولی آن‌طرف که درد خاست؟

هین مزن تو از ملولی آهِ سرد
درد جو و، درد جو و، درد، درد

خَوْ کردن: وَجین کردن، هَرَس کردن درخت
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۱۳۷
[.poem]
....
گفت: رُو، هر که غمِ دین برگزید
باقیِ غم‌ها خدا از وی بُرید

حدیث
«مَنْ جَعَلَ الْهُمُومَ هَمًّا وَاحِدًا هَمَّ الْمَعَادِ كَفَاهُ اللَّهُ هَمَّ دُنْيَاهُ
وَمَنْ تَشَعَّبَتْ بِهِ الْهُمُومُ فِي أَحْوَالِ الدُّنْيَا لَمْ يُبَالِ اللَّهُ فِي أَىِّ أَوْدِيَتِهِ هَلَكَ.»

«هر کس غم‌هایش را به غمی واحد محدود کند، خداوند غمهای
دنیوی او را از میان می‌برد. و اگر کسی غم‌های مختلفی داشته باشد،
خداوند به او اعتنایی نمی‌دارد که در کدامین سرزمین هلاک گردد.»
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۳۹۶
[.poem]
....
پس ریاضت را به جان شو مُشتری
چون سپردی تن به خدمت، جان بَری

ور ریاضت آیدت بی‌اختیار
سر بنهْ، شکرانه دِهْ، ای کامیار

چون حقت داد آن ریاضت، شکر کن
تو نکردی، او کشیدت ز‌امرِ کُن

ریاضت: رنج، زحمت
کامیار: کامیاب، آنکه به آرزوی خود رسیده است.
امرِ کُن: فرمانِ «بشُو و می‌شودِ» خداوند.
....

== آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

audio::media/audio/adaab_shenavandegan_va_moridan_angah_ke_sokhanan_hekmat_amiz_az_zaban_sheykh_jari_shavad.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر سوم، بیت ۳۶۰۲
[.poem]
....
آدابُ الْمُسْتَمِعینَ َوالْمُریدینَ عِنْدَ فَیْضِ الْحِکْمَةِ مِنْ لِسانِ الشَّیخ
آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

بر مَلولان، این مکرّر کردن است
نزدِ من عمرِ مکرَّر بُردن است

شمع از برقِ مُکَرَّر بر شود
خاک از تابِ مُکَرَّر زر شود

گر هزاران طالبند و، یک مَلول
از رسالت باز می‌مانَد رسول

این رسولانِ ضمیرِ رازگُو
مُسْتَمع خواهند، اِسرافیل‌خو

نخوتی دارند و، کبری چون شهان
چاکری خواهند از اهلِ جهان

نخوت: تکبر، خودبزرگ‌بینی

تا ادب‌هاشان به جاگَه نآوری
از رسالتْشان چگونه بر خوری؟

بَر خوری: میوه خوری، برخوردار شوی

کی رسانند آن امانت را به تو
تا نباشی پیششان راکع دوتو؟

راکع: رکوع کننده
دوتو: خمیده، دولا

هر ادبْشان کَی همی‌ آید پسند؟
کآمدند ایشان ز ایوانِ بلند

نه گدایانند کز هر خدمتی
از تو دارند ای مزوِّر مِنّتی

لیک با بی‌رغبتی‌ها ای ضمیر
صدقهٔ‌ سلطان بیفشان، وامگیر

اسبِ خود را، ای رسولِ آسمان
در ملولان منگر و، اندر جهان

فرّخ آن تُرکی که استیزه نهد
اسبش اندر خندقِ آتش جهد

تُرک: در اینجا به معنی جنگاور و مجاهد دلاور است.
استیزه نهد: جنگ و جهاد کند، دلاوری و جنگاوری از خود نشان دهد.

گرم گرداند فَرَس را آنچنان
که کند آهنگِ اوجِ آسمان

چشم را از غیر و غیرت دوخته
همچو آتش خشک و، تر را سوخته

گر پشیمانی بر او عیبی کند
آتش اوّل در پشیمانی زند

خود، پشیمانی نروید از عدم
چون ببیند گرمیِ صاحب‌قدم
....

== هرکس سرنوشت خودش رو در این لحظه خودش تعیین میکنه

audio::media/audio/har_kas_sarneveshte_khodesh_ro_dar_in_lahze_khodash_taeen_mikone.mp3[controls]

.مولوی، مثنوی، دفتر پنجم، بیت ۳۱۸۲
[.poem]
....
فعلِ توست این غُصّه‌هایِ دَم‌به‌دَم
این بُوَد معنیِّ قَدْ جَفَّ الْقَلَم

حدیث
جَفَّ الْقَلَمُ بِما أنْتَ لاقٍ
خشك شد قلم به آنچه سزاوار بودی

جَفَّ الْقَلَمُ بِما هُوَ کائنٌ
خشک شد قلم به آنچه بودنی است
....

== نعمت آرد غفلت و شکر انتباه

audio::media/audio/nemat_arad_ghaflat_va_shokr_entebah.mp3[controls]

== جف القلم

audio::media/audio/jaf_al_ghalam.mp3[controls]

== بهترین نیایش صبره

audio::media/audio/behtarin_niyayesh_sabre.mp3[controls]
