= گزیده کتاب‌ها
:toc:
:toc-title!:
:toclevels: 1
:nofooter:

== با پیر بلخ، کاربرد مثنوی در خودشناسی، محمد جعفر مصفا

=== مجنون و ناقه

مجنون سوار بر ناقه می شود تا بسوی لیلی برود. اما چون ناقه هوای دیگر و مقصد دیگری در سر
دارد سالها مجنون را در سرگردانی و تردد مشغول می دارد و او را به لیلی نمی رساند.

[.poem]
....
آنکه او باشد مراقب عقل بود
عقل را سودای لیلی در ربود
....

عقل در انسان، حاکم و مراقب کارساز و راه برنده‌ای است. اما وقتی انسان اسیر «لیلی نفس» شد،
سودای لیلی، این راهبر را دنگ و منگ می کند. شاید لیلی سمبل خواسته‌های تصوری و ایده‌آلی‌ای
باشد که نفس بر انسان دیکته می کند. خواسته‌هایی که چون بت لیلی در ذهن ما نشسته‌اند و چنان
جذبه کور کننده‌ای پیدا کرده‌اند که نمی گذارند هوش و حواسمان بجا باشد.

[.poem]
....
آنکه او باشد مراقب عقل بود
عقل را سودای لیلی در ربود

لیک ناقه بس مراقب بود و چست
چون بدیدی او مهار خویش سست

فهم کردی زو که غافل گشت و دنگ
رو سپس کرده به کُرّه بیدرنگ
....

عوامل و پرسناژهای داستان اینها هستند: مجنون سمبل خواسته‌های آزمندانه انسان یا خود انسان
است. لیلی، موضوع و هدف خاص آن خواسته هاست - که همه سرا‌بگونه و رؤیائی و ایده‌آلی است.
ناقه هم سمبل فکر است. انسان بوسیلهٔ مرکب فکر میخواهد به آرزوهای رؤیائی خود دست یابد
اما فکر مرکب مناسبی برای رسیدن به آن ایده‌آلها نیست - فکر هوای کره‌های خودش را دارد. یعنی
اسیر چیزهائی است که هم اکنون در آنها غوطه‌ور است. مجنون خواسته‌هائی بلند پرواز و ایده‌آلی
دارد ولی فکر یا ناقه اسیر کره‌ها و مشغولیاتی است که او را در خود گرفته‌اند. مجنون با ناقه
در کشمکش است. ناقه یکقدم مجنون را به سوی لیلی می‌برد ولی همینکه مهار خود را سست میبیند
به عقب بر‌می‌گردد و بسوی کره خود میرود. گمان میکنم در این داستان مولوی جریاناتی را ترسیم
می کند که در طریق «سلوک» پیش می آید. می خواهد به «سالک» هشدار بدهد که مواظب فریبها و
بازیهای فکر باش.

[.poem]
....
چون بخود باز آمدی دیدی زجا
کوسپس رفته است بس فرسنگها

در سه روزه ره بدین منوال ها
ماند مجنون در تردد سالها

گفت ای ناقه چو هر دو عاشقیم
ما دو ضد بس همره نالایقیم
....

بعد از سالها تردد، بالاخره مجنون به راهنمائی عقل مفید خویش در می یابد که «‌ناقه
نفس‌» یا عقل جزئی مرکب مناسبی در طریق لیلی‌ ایده‌آلی او نیست و باید او را رها کرد و این
ادراک مقدمه مفیدی است.

[.poem]
....
نیست بر وفق منت مهر و مهار
کرد باید از تو عزلت اختیار
....

اختیار تو در دست من نیست، تو اماره‌ای، تو حاکم بر راه و رابطه‌ای، تو مرا به
میل خودت میبری، نه من ترا. پس تو بدرد من نمی‌خوری.

[.poem]
....
این دو هـمـره یکدگر را راهزن
گمره آن جان کو فرو ناید ز تن

جان زهجر عرش اندر فاقه‌ای
تن ز عشق خاربن چون ناقه‌ای

جان گشاید سوی بالا بالها
در زده تن در زمین چنگالها
....

جان هوای عرش دارد، سودای پرواز ملکوتی دارد؛ اما «‌تن‌» که
پایگاه «‌نفس‌» است و به پستی‌های این جهان خو گرفته و آموخته شده است، همچو
ناقه‌ای پنجه و پوزه در خارهای پست این دنیای خاکی فرو کرده است و نشخوار
پستیها را می کند.

مجنون بعد از این ادراکات عقلی، همت خفته خود را هی میزند، بیدار می کند و با
نهیب بر سر این مرکب ابتر و کژ‌رو از آن فرود می آید می گوید:

[.poem]
....
تا تو با من باشی ای مرده وطن
بسی زلیلی دور مانده جان من

راه نزدیک و بماندم سخت دیر
سیر گشتم زین سواری سیر سیر!
....

از دست فکر اماره کارد باستخوانش رسیده، وخامت آنرا درک کرده و از آن فرود
می آید. لب مطلب مورد نظر ما از اینجا به بعد است:

[.poem]
....
آنچنان افکند خود را سخت زیر
که مخلخل گشت جان آن دلیر

چون چنان افکند خود را از زیر و پست
از قضا آن لحظه پایش هم شکست

پای را بر بست و گفتا گو شوم
در خم چوگانش غلطان میروم

عشق مولی کی کم از لیلی بود!
گوی گشتن بهر او اولی بود
....

مولوی در این قسمت از داستان چند تغییر اساسی می دهد و چند موضوع جدید را
وارد میکند. اولاً هنگام فرود آمدن از ناقه پای مجنون می شکند، ثانیاً برای
حرکت میگوید باید «‌گوی» گشت، ثالثاً در این مرحله عشق لیلی تبدیل به عشق مولی
میگردد. این تغییرات قابل تأمل است. می گویند وقتی مجنون به لیلی میرسد یک
حالت بورشدگی پیدا می کند و می گوید لیلائی که من در جستجویش بودم این نیست، من،
لیلای لیلا رو می‌خواهم.

لیلائی که مجنون به او رسیده یا میخواهد برسد، لیلای تجسم فکر و عقل خود اوست؛
حاصل یک ترسیم ذهنی است - مثل هدفها و خواسته‌هائی که بصورت ایده‌آل در
کارگاه «هویت فکری» ترسیم می گردد‌؛ و وقتی انسان به آنها دست مییابد احساس میکند
چیزی که به آن رسیده آن نبوده که او می خواسته است. اما «لیلای لیلا» چیز دیگری
است. چیزی است ورای فکر و ترسیم ذهنی انسان.

هنگام فرود آمدن از ناقه پای مجنون میشکند. ببینیم با آوردن «پا» می خواهد چه
گفته باشد. مجنون ابتدا سوار بر «ناقه نفس» است و در اختیار آن – یعنی در اختیار عقل
جزئی، مجازی و توهمی. عقل جزئی حاکم بر اوست و او را می‌برد. بعد عقل مفید و
واقعی او بجا می‌آید و این حقیقت را درک می کند که ناقه نفس یا عقل جزئی
نمیتواند او را به ایده‌آل های او برساند. این ناقه او را در تردد نگه میدارد و
دور خودش می چرخاند. بنابراین از عقل نفس آلود یا ناقه فرود می آید. ولی اینهم
مقدمه یک حرکت و مقصد دیگر است. مجنون تا وقتی سوار بر «ناقه نفس» است اسیر
اوهام و پندارهای ایده‌آلی خویش است، و بنابراین ترسیم او از همه چیز تحت تأثیر
آن اوهام است. اما همین که خود را از چنگال چنان عقلی خارج می‌سازد همه چیز
برایش کیفیت دیگری پیدا می‌کند. مجنون تا زمانی که اسیر نفس است و اوهام برخاسته
از نفس، کور و منگش کرده است، به عشق لیلی می اندیشد و به دنبال آن می رود. اما
وقتی از اسارت نفس، یعنی از اسارت عقل جزئی آزاد شد، عشق برایش کیفیت دیگری
می‌یابد - عشق لیلا به عشق مولی تبدیل میگردد.

و همزمان با این تغییر این حقیقت را هم در می‌یابد که در طریق چنان عشقی
یعنی عشق مولی، «پا» یک وسیلۀ غیر مفید و نامناسب است. در طریق آن عشق باید «گوی» گشت. «پا» سمبل
عقل مفید است و وسیله مناسبی است در طریق امور مادی زندگی.

[.poem]
....
پای را بر بست و گفتا گو شوم
در خم چوگانش غلطان میروم
....

پا نمیتواند ابزار حرکت به سوی عشق مولائی و الهی باشد. در این راه باید «گوی» گشت.
گوی سمبل تفویض است، کیفیتی است که در آن تمام خواسته‌ها و تعلقات
تشکیل دهندۀ «نفس» خود را تفویض و تسلیم به عشق الله می کنند. گوی سمبل بی
شکلی است؛ کیفیت ابزار و وسیله رفتن و پیمودن را - مثل پا – ندارد. در حرکت
گوی تلاش و جست و خیز وجود ندارد، بلکه بوسیله چوگان رانده می شود - یعنی
نمی رود بلکه برده می‌شود. سر تیزی و زیرکی حرکت‌های ذهنی و عقلی در آن
نیست؛ و خلاصه سمبل نخواستن و وسیله بی وسیله‌ای است برای اتصال به کیفیت
های ورای شکل، ورای توصیف، ورای تعین و ورای بعد و عدد.

'''

=== دژ ذاتُ‌الصُّوَر

داستانی مربوط به سه‌شه‌زاده که پدرشان آنها را از رفتن به قلعه‌ای بنام قلعه ذاتُ‌الصُّوَر یا دژ هوش‌ربا
برحذر می‌دارد. می‌گوید به هر جا دلتان می‌خواهد بروید، اما:

[.poem]
....
الله الله زآن دِزِ ذاتُ‌الصُّوَر
دُور باشید و بترسید از خطر

رو و پشتِ برج‌هاش و سقف و پست
جمله تمثال و نگار و صورت است
....

یک تذکر حاشیه‌ای: بسیار کم پیش می‌آید که مولوی مطلبی یا
کلمه‌ای را نسنجیده و بدون توجه دقیق و عمیق به معنای آن به‌کار برد. در
عین آنکه در یک زمینه برای الفاظ و کلمات شأن و منزلتی قائل نیست،
می‌داند که در زمینهٔ دیگر، یعنی به عنوان ابزار ارتباط، هر کلمه دارای ارزش و
کاربرد خاصی است و باید با دقت به کار گرفته شود. وقتی می‌گوید «الله زان
دژ ذات‌الصور»، می‌خواهد عمق و وخامتی را که در حصار نقش‌ها و
صورت‌ها نهفته است برساند. می‌گوید: «الله الله»؛ یعنی الحذر الحذر از خطر
آن قلعه! زندگی جز آن قلعه و حصار هیچ رنج و مسئله و خطری ندارد. رنج
زندگی تنها در قلعهٔ نقش‌ها و صورت‌ها و الفاظ است.

با بیان «رو و پشت و برج‌ها و سقف و پست» می‌خواهد این معنا را
برساند که «قلعهٔ نفس» چنان ترا در تصاویر فرو می‌برد که هیچ راه و منفذی به
خارج نداری. به هر سویش بنگری و به هر گوشه‌اش بروی تنها نقش و
صورت می‌بینی. این حصار زندانی است که دیوارهایش را نقش و صورت
تشکیل می‌دهد.

باری، شه‌زادگان وسوسه می‌شوند و علیرغم هشدار و تأکید پدر، به
قلعه می‌روند و آن را چنین می‌یابند:

[.poem]
....
اندر آن قلعهٔ خوش ذات‌الصور
پنج در در بحر و پنجی سوی بر

پنج از آن چون حس به سوی رنگ و بو
پنج از آن چون حس باطن رازجو
....

می‌گوید «قلعهٔ خوش ذات‌الصور» ـ و منظورش از «خوش»، کیفیت مست
کننده و لذت‌های سطحی و بی‌مغزی است که در حرکت‌ها و بازی‌های
«نفس» وجود دارد ـ لذت‌هایی که انسان را مسحور و مفتون می‌کند.
می‌گوید این قلعه (در اینجا «قلعه» را به معنای وجود کلی انسان بگیریم)
دارای ده در است که پنج در نمایندهٔ پنج حس نفسانی، بری و خشک این
دنیایی است، و پنج حس باطنی و پاک و معنوی که به بحر گشوده می‌شود.
می‌دانیم که «بحر» را سمبل اصالت، پاکی، عمق و شکوه می‌داند.

شه‌زادگان بعد از ورود به قلعه اسیر و سرمست نقش‌های آن می‌گردند:
«می‌شدند از سو بسو خوش بی‌قرار» ـ مثل من و تو که از صبح تا شب
کارمان این است که با دل‌هره و بی‌قراری در لابلای نقش‌ها و تصاویر
می‌پلکیم و از این نقش به آن نقش و از این خیال خوش به آن خیال خوش
می‌رویم، غافل از اینکه این نقش‌ها و صورت‌ها و لذت‌های شیرین و رنگین
«ریگ آب عمر ما» هستند.
گمان نمی‌کنم در مثنوی مسئله‌ای به وخامت نقش‌ها، صورت‌ها،
تصاویر و الفاظ مطرح شده باشد. بارها روی این مسئله بنیادی تکیه کرده و
کوشیده است تا ما را متوجه عمق و وخامت آن گرداند:

[.poem]
....
زین قدح‌های صور کم باش مست
تا نگردی بت‌تراش و بت‌پرست

از قدح‌های صور بگذر، مایست
باده در جام است لیک از جام نیست

آدما معنی د‌لبندم بجوی
ترک قشر و صورت گندم بگوی
....

باده در جام هست، ولی نه از جام است و نه از جنس جام. پس ظرف و جام را
بگذار، ترک قشر و صورت را بگوی و معنی هستی را دریاب. «کف بهل
وز دیده در دریانگر». لفظ‌ها و توصیف‌ها بمنزله کف و حباب دریا هستند و
ما مست همین لفظ‌ها، صورت‌ها و توصیف‌ها هستیم. از آن‌ها بتّی به نام
«خود» تراشیده‌ایم و به پرستش آن نشسته‌ایم.

شه‌زادگان در قلعهٔ صورت‌ها و نقش‌ها به سیر و سرمستی مشغولند تا
این که به صورتی برمی‌خورند ورای همهٔ صورت‌ها. این صورت، صورت
حقیقت است (نه خود حقیقت). عشق آن بجانشان می‌افتد و خود را از
دست می‌دهند.

[.poem]
....
عشق صورت در دل شه‌زادگان
چون خلش می‌کرد مانند سنان
....

و به جستجو و تفحص می‌افتند تا ببینند صاحب آن صورت کیست. در
تفحص خود به «شیخی بصیر» برمی‌خورند.

[.poem]
....
بعد بسیار تفحص در مسیر
کشف کرد آن راز را شیخی بصیر

گفت نقشِ رشگ پرورین است این
صورتِ شه‌زاده چین است این
....

بعد از اشارهٔ «شیخ بصیر»، هر سه برادر از قلعه خارج می‌شوند و به
جستجوی صاحب تصویر روانهٔ بلاد چین می‌گردند.

بنظرم در همین جا باید معنای «شیخ بصیر» را توضیح بدهیم. مولوی
«شیخ بصیر» را سمبل و نمایندهٔ عقل مفید، عقل خردمند و راهبر می‌گیرد،
و آن را در مقابل «شیخ واصل ناشده» (که سمبل عقل جزئی و مخرب است) به
کار می‌برد. داستان مفصلی دارد که شاید به آن بپردازیم. در آن داستان
«ده» و روستا را از نظر محدودیت، سمبل عقل جزئی می‌گیرد و آن را مترادف
با آدمی می‌داند که ذهنش باز نیست، بلکه در حصار ذهنیت خودش آنکادره
است. می‌گوید:

[.poem]
....
ده مرو، ده مرد را احمق کند
عقل را بی‌نور و بی‌رونق کند

ده چه باشد؟ شیخ واصل ناشده
دست در تقلید و در حجت زده
....

«شیخ واصل ناشده» عقل جزئی، تیره و کوری است که حقیقت را ندیده
است، وصل به حقیقت نیست، بلکه ارتباطش با همه چیز از طریق تقلید،
استدلال و حجت‌آوری است. حرف‌های منطقی، مستدل و شسته‌رفته‌ای
می‌زند، ولی «از قیاسی گوید آن را، نه از عیان».
اولین کار مفید «شیخ بصیر» یا عقل مفید این است که به هوای صورت
شه‌زاده چین، بچه‌ها را از «قلعهٔ نفس» خارج می‌کند و در خارج از قلعه آن‌ها را
به جستجو وامی‌دارد.
خواستن، طلب و جستجوی مفیدی که مولوی بدان اشاره می‌کند و آن
را مقدمهٔ وصول به حقیقت می‌داند، چنین جستجویی است ـ جستجویی که
با عقل مفید یا به اشارهٔ «شیخ بصیر» و در خارج از قلعهٔ توصیف‌ها و نقش‌ها
صورت می‌گیرد. جستجو با عقل جزئی در داخل قلعه است، ولی
جستجوی با عقل مفید در بیرون از قلعه. «صورت شه‌زادهٔ چین»، صورت
است، اما سوای همهٔ صورت‌هایی است که شه‌زادگان در قلعه می‌دیدند و
اسیر و سرمست آنها بوده‌اند. و این صورت، یعنی صورت حقیقت است که
آنها را از قلعه بیرون می‌کشد.

اگر بخواهیم موضوع را غیر سمبلیک نگاه کنیم شاید بتوان مرحلهٔ
خارج شدن از قلعه و روانه شدن سه برادر را بسوی چین مترادف با مرحلهٔ
ادراک عقلی دانست. هر سه برادر به مرحلهٔ ادراک عقلی رسیده‌اند، اما فقط
یکی از آنها است که می‌گوید «هر چه باداباد!» و می‌رود تا سرانجام به
حقیقت متصل می‌گردد.

پس از خروج از قلعه، برادران روانهٔ بلاد چین می‌شوند و در آنجا مدتی
سرگردان می‌مانند تا صبر برادر بزرگ‌تر لبریز می‌شود و علیرغم منع دو برادر
دیگر عازم دربار سلطان می‌شود.

[.poem]
....
من علم اکنون به صحرا می‌زنم
یا سراندازی و یا روی صنم
....

می‌گوید هر چه باداباد؛و با کیفیتی که انسان واقعاً از درون شعله‌ور
می‌شود، با کیفیتی از خود بیخود ـ یعنی کیفیتی که حساب‌های عقلی را
هم کنار می‌گذارد و همه چیز را در معشوق می‌بیند ـ خویش را به دربار
سلطان می‌رساند.

وقتی بچه‌ها به چین می‌رسند و سراغ صاحب صورت را می‌گیرند
می‌بینند هیچ‌کس از چنان صورتی خبر ندارد. اصلاً انگار یک وضعیتی
هست که صحبت کردن از صورت دختر پادشاه چین ممنوع است؛ یا چنان
است که گویی سلطان اصلاً فرزندی ندارد. و جالب این است که خود شه‌زاده
هم وقتی به ملاقات سلطان می‌رسد صورت را فراموش می‌کند و نمی‌داند
برای چه منظوری آمده است. وقتی عشق شعله‌ور می‌شود هر گونه «خود
اشعاری» را می‌شوید و از ذهن پاک می‌کند.

شه‌زاده در دربار سلطان اثری از صورت نمی‌یابد. در آنجا با
خود سلطان ملاقات می‌کند. و سلطان خود حقیقت است. انسان بعد از
ملاقات حقیقت متصل به آن می‌گردد و با آن یکی می‌شود ـ و این اتصال
زمانی پیش می‌آید که صورت را از یاد می‌برد.

[.poem]
....
صورت معشوق زو شد در نهفت
رفت و شد با معنی معشوق جفت
....

داستان دو برادر دیگر، و این که چه می‌شوند، در مثنوی مبهم و ناگفته مانده
است. شاید آن‌ها هم عاقبت به شکلی از حقیقت بهره‌ور می‌شوند. زیرا در
هر حال از قلعهٔ «ذات الصور» یا «قلعهٔ نفس» خارج شده‌اند.

مولوی می‌گوید شه‌زاده حرکت خود را با انگیزهٔ صورت و در
جستجوی صورت آغاز می‌کند، ولی وقتی به دور و بر حقیقت نزدیک
می‌شود، صورت را از یاد می‌برد. چنان محو پرتو حقیقت سلطان می‌گردد
که نمی‌تواند به صورت بیندیشد. شعری که قبلاً خواندیم:

[.poem]
....
تا بدریا سیر اسب و زین بود
بعد از آنت مرکب چوبین بود

آن خمُوشی مرکب چوبین بود
بحریانرا خامشی تلقین بود
....

از متن همین داستان است. و مولوی آن را بعد از واقعه‌ای آورده که در آن
شه‌زاده صورت را بکلی فراموش می‌کند و محو جمال حقیقت می‌گردد.
فراموش کردن صورت با سکوت ذهن پیش می‌آید. در سکوت، حجاب
برداشته می‌شود و اتصال به حقیقت صورت می‌گیرد. تا نزدیک شدن به
حقیقت، عقل راهنما است؛ اما برای اتصال واقعی هر گونه حرکت عقلی ابتر
است. گمان می‌کنم تم اصلی این داستان هم شبیه داستان مجنون و ناقه
است.

'''

[.poem]
....
بفکن از من حمل ناهموار را
تا ببینم روضهٔ انوار را
....

خدایا ما رو کمک کن تا این «حمل ناهموار»، این بار کج و نا‌هنجار و پرادبار را از کول ذهن خود
برداریم و به وسعت هستی پرنور متصل گردیم!
