= گزیده‌های نوشتاری
:nofooter:

.برنامه ۹۹۷، مولوی، دیوان شمس، غزل شماره ۱۶۱۱
[.poem]
....
ز درم راه نباشد، ز سرِ بام و دریچه
سَتَرَالله عَلَیْنٰا چه علالایِ تو دارم

سَتَرَالله عَلَیْنٰا: خداوند بر ما پوشانید
علالا: بانگ و فریاد، هیاهو، سر و صدا
....

نذارید من ذهنیتون مانع سازی بکنه از اینکه گذشته من اینطور بوده و در گذشته
این کارهای بد رو کردم و این دردها رو ایجاد کردم و امکان رهایی وجود نداره.
نه. میگه خداوند اینها رو پوشانید. چنان پوشانید مثل اینکه اینها رو شما اصلا انجام ندادید.
زندگی رحمت اندر رحمته و این رحمت بستگی به کارهای گذشته شما نداره. اگر از در راه نیست،
من از طریق بام و دریچه میرم به بالای بام و علالای تو رو میکنم. فضا رو باز میکنم تا از طریق تو
حرف بزنم. درسته که ذهنم اجازه نمیده و هی به من تلقین میکنه که تو این کار رو کردی، اون کار
رو کردی، گذشته تو اینطوری بوده. ما باید از گذشته و ماجرا بیرون بپریم. شما نباید از چیزهایی
که ذهنتون نشون میده مانع ذهنی درست کنید و فضا رو باز نکنید یا جلوی پیشرفت خودتون رو بگیرید.

'''

.برنامه ۷۲۰، مولوی، دیوان شمس، غزل شماره ۵۸۲
[.poem]
....
پیشِ ما فَرج و گلو باشد خیال
لاجَرَم هر دَم نماید جان جمال

فَرج: شرمگاه، آلت تناسلی مرد یا زن
گلو: خورد و خوراک
....

پیش ما فرج و گلو خیاله، فکره. یعنی اهمیتی برای ما نداره. ما باهاش هم هویت نیستیم.
بنابراین هر لحظه خدا جمالش رو به ما نشون میده. یعنی من به اون زنده ام.
برای اینکه این نیازهای بیرونی مرکز من نیست. توجه کنید فرج و گلو نماد تمام چیزهایی
است که ما باهاشون هم هویتیم از جمله باورها، چیزهای فیزیکی نظیر پول.
همه چیزهای که در بیرون توجه ما رو می بلعن. جسم ما، زیبایی ما، روابط ما.
