= گزیده برنامه ها

== آتش آب توست

.برنامه ۸۰۳، مولوی، مثنوی، دفتر پنجم، بیت شماره ۴۳۳
[.poem]
....
جَوْق‌ْجَوْق و صَفْ صَف از حرص و شِتاب
مُحْتَرِِز ز آتش، گُریزان سویِ آب

لاجَرَم ز آتش برآوردند سر
ِاعْتِبارَالْاِعْتِبار ای بی‌خبر

بانگ می‌زد آتش ای گیجانِ گول
من نِیَ ام آتش، منم چشمهٔ قبول

چشم‌ْبندی کرده‌اند ای بی‌نَظَر
در من آی و هیچ مَگْریز از شَرَر

ای خلیل اینجا شَرار و دود نیست
جز که سِحْر و خُدْعهٔ نمرود نیست

چون خلیلِ حق اگر فرزانه‌ای
آتش آبِ توست و تو پروانه‌ای

جَوْق‌ْجَوْق: دسته دسته، جمع آن اَجْواق است.
مُحْتَرِِز: دوری کننده، پرهیز کننده
اعتباراَلِْاعتبار: عبرت بگیر، عبرت بگیر.
گول: ابله، نادان
شَرار: پاره آتشی که به هوا جهد، جرقه
....

== آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر سوم، بیت ۳۶۰۲
[.poem]
....
آدابُ الْمُسْتَمِعینَ َوالْمُریدینَ عِنْدَ فَیْضِ الْحِکْمَةِ مِنْ لِسانِ الشَّیخ
آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

بر مَلولان، این مکرّر کردن است
نزدِ من عمرِ مکرَّر بُردن است

شمع از برقِ مُکَرَّر بر شود
خاک از تابِ مُکَرَّر زر شود

گر هزاران طالبند و، یک مَلول
از رسالت باز می‌مانَد رسول

این رسولانِ ضمیرِ رازگُو
مُسْتَمع خواهند، اِسرافیل‌خو

نخوتی دارند و، کبری چون شهان
چاکری خواهند از اهلِ جهان

نخوت: تکبر، خودبزرگ‌بینی

تا ادب‌هاشان به جاگَه نآوری
از رسالتْشان چگونه بر خوری؟

بَر خوری: میوه خوری، برخوردار شوی

کی رسانند آن امانت را به تو
تا نباشی پیششان راکع دوتو؟

راکع: رکوع کننده
دوتو: خمیده، دولا

هر ادبْشان کَی همی‌ آید پسند؟
کآمدند ایشان ز ایوانِ بلند

نه گدایانند کز هر خدمتی
از تو دارند ای مزوِّر مِنّتی

لیک با بی‌رغبتی‌ها ای ضمیر
صدقهٔ‌ سلطان بیفشان، وامگیر

اسبِ خود را، ای رسولِ آسمان
در ملولان منگر و، اندر جهان

فرّخ آن تُرکی که استیزه نهد
اسبش اندر خندقِ آتش جهد

تُرک: در اینجا به معنی جنگاور و مجاهد دلاور است.
استیزه نهد: جنگ و جهاد کند، دلاوری و جنگاوری از خود نشان دهد.

گرم گرداند فَرَس را آنچنان
که کند آهنگِ اوجِ آسمان

چشم را از غیر و غیرت دوخته
همچو آتش خشک و، تر را سوخته

گر پشیمانی بر او عیبی کند
آتش اوّل در پشیمانی زند

خود، پشیمانی نروید از عدم
چون ببیند گرمیِ صاحب‌قدم
....

== آدمى را در رنج و محنت بيافريده ايم

.قرآن کریم، سوره بلد (۹۰)، آیه ۱۲-۱
[.poem]
....
لَا أُقْسِمُ بِهَٰذَا الْبَلَدِ
قسم به اين شهر.

وَأَنْتَ حِلٌّ بِهَٰذَا الْبَلَدِ
و تو در اين شهر سكنا گرفته‌اى.

وَوَالِدٍ وَمَا وَلَدَ
و قسم به پدر و فرزندانى كه پديد آورد.

لَقَدْ خَلَقْنَا الْإِنْسَانَ فِي كَبَدٍ
كه آدمى را در رنج و محنت بيافريده‌ايم.

أَيَحْسَبُ أَنْ لَنْ يَقْدِرَ عَلَيْهِ أَحَدٌ
آيا مى‌پندارد كه كس بر او چيره نگردد؟

يَقُولُ أَهْلَكْتُ مَالًا لُبَدًا
مى‌گويد: مالى فراوان را تباه كردم.

أَيَحْسَبُ أَنْ لَمْ يَرَهُ أَحَدٌ
آيا مى‌پندارد كه كسى او را نديده است؟

أَلَمْ نَجْعَلْ لَهُ عَيْنَيْنِ
آيا براى او دو چشم نيافريده‌ايم؟

وَلِسَانًا وَشَفَتَيْنِ
و يك زبان و دو لب؟

وَهَدَيْنَاهُ النَّجْدَيْنِ
و دو راه پيش پايش ننهاديم؟

فَلَا اقْتَحَمَ الْعَقَبَةَ
و او در آن گذرگاه سخت قدم ننهاد.

وَمَا أَدْرَاكَ مَا الْعَقَبَةُ
و تو چه دانى كه گذرگاه سخت چيست؟
....

== آینده لازم نیست امتداد گذشته باشه

.برنامه ۹۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۶۱۱
[.poem]
....
ز درم راه نباشد، ز سرِ بام و دریچه
سَتَرَ اللهُ عَلَیْنٰا چه عَلالایِ تو دارم

سَتَرَ اللهُ عَلَیْنٰا: خداوند بر ما پوشانید
عَلالا: بانگ و فریاد، هیاهو، سروصدا
....

.مولوی، دیوان شمس، غزل شمارهٔ ۵۸۲
[.poem]
....
خُنُک جانی که بر بامَش همی چوبَک زَنَد امشب
شود همچون سَحَر خندان، عَطایِ بی ‌عدد بیند

چوبَک زدن: پاسبانی کردن، نگهبانی کردن
....

.مولوی، دیوان شمس، غزل شمارهٔ ۷۷۱
[.poem]
....
دل تو مثالِ بام است و، حواسْ ناودان‌ها
تو ز بام آب می‌خور که چو ناودان نماند

جامِ مُباح آمد، هین نوش کُن
بازرَه از غابر و از ماجَرا

مُباح: حلال، جامِ مُباح: شرابِ حلال
غابر: گذشته

خفته از احوال دنیا روز و شب
چون قلم در پنجه تقلیب رب

تقلیب: برگردانیدن، واژگونه کردن

ای عاشق جریده، بر عاشقان گزیده
بگذر ز آفریده، بنگر در آفریدن

جریده: یگانه، تنها

هر لحظه و هر ساعت یک شیؤە نو آرد
شیرینتر و نادرتر زآن شیؤە پیشینش

بر گذشته حسرت آوردن خطاست
باز نآید رفته، یاِد آن هباست

هبا: مخفف هباء به معنی گرد و غبار پراکنده. در اینجا به معنی بیهوده است
....

== از میان نردبان نگریزم

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۶۵۸
[.poem]
....
عاشقم، از عاشقان نگریختم
وز مَصاف ای پهلوان، نگریختم

حمله بردم سوی شیران همچو شیر
همچو روبه از میان نگریختم

قصدِ بامِ آسمان می داشتم
از میانِ نردبان نگریختم

چونکه من دارو بدم هر درد را
از صُداعِ این و آن نگریختم

هیچ دیدی دارو کز دردی گریخت؟
داروَم من، همچنان نگریختم

پیروِ پیغامبران بودم به جان
من ز تهدیدِ خَسان نگریختم

زنده کوشم در شکارِ زندگی
زنده باشم، چون ز جان نگریختم

چشمِ تیراندازش آنگه یافتم
که ز تیرِ خَرکمان نگریختم

زخمِ تیغ و تیرِ من منصور شد
چون که از زخمِ سِنان نگریختم

بحرِ قندم، از تُرُش باکیم نیست
سودمندم، از زیان نگریختم

شمسِ تبریزی چو آمد آشکار
ز آشکارا و نهان نگریختم
....

== استثنا کنید

.برنامه ۹۸۲، مولوی، مثنوی، دفتر سوم، بیت ۱۶۳۷
[.poem]
....
مدتی بر نذرِ خود بودش وفا
تا درآمد امتحاناتِ قضا

زین سبب فرمود: استثنا کنید
گر خدا خواهد به پیمان بر زنید

هر زمان دل را دگر مَیلی دهم
هر نَفَس بر دل دگر داغی نهم

کُلُّ اَصْباحٍ لَناٰ شَأْنٌ جَدید
کُلُّ شَیءٍ عَنْ مُرادی لایَحید

در هر بامداد کاری تازه داریم، و هیچ کاری از حیطهٔ مشیت من خارج نمی‌شود.
استثنا کنید: ان‌شاءالله بگویید، اگر خدا بخواهد بگویید.
....

.قرآن کریم، سورهٔ الرحمن (۵۵)، آیهٔ ۲۹
[.poem]
....
يَسْأَلُهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ ۚ كُلَّ يَوْمٍ هُوَ فِي شَأْنٍ.
هر كس كه در آسمانها و زمين است سائل درگاه اوست، و او هر لحظه در كارى جدید است.
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۲۲۷
[.poem]
....
هر لحظه و هر ساعت یک شیوهٔ نو آرد
شیرین‌تر و نادرتر زان شیوه‌ی پیشینش
....

== افسانه من ذهنی

موانع مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی، که به نظر
من نمی گذارند، من در این لحظه زندگی کنم و اگر آن موانع رفع شوند، زندگی
من شروع می شود.

مسایل مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی که خودشان
را به من به صورت گره ذهنی یا مساله ارائه می کنند و من نمی خواهم یا اصلاً
نمی توانم برای حل آنها کاری کنم.

دشمنان مَنِ ذهنی من: اشخاص و یا وضعیت های ساخته شده به وسیله من ذهنی،
که به نظر من فعالانه در پایین آوردن کیفیت زندگی من یا محروم کردن من از زندگی
می کوشند. من ذهنی برای بقا، از آنها به صورت قطب استفاده می کند و انرژی
مخرب ایجاد میکند.

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شماره ۱۳۴۴
[.poem]
....
دمِ او جان دهدت رو ز نَفَخْتُ بپذیر
کارِ او کُنْ فَیَکُون ‌ست، نه موقوفِ علل

نَفَخْتُ: دمیدم
....

== اگر قبول دارید عمل کنید روی خودتون کار کنید

.برنامه ۹۸۲، مولوی، مثنوی، دفتر پنجم، بیت ۱۳۶۵
[.poem]
....
میلِ شهوت، کر کند دل را و کور
تا نماید خر چو یوسف، نار نور

ای بسا سرمستِ نار و نارجو
خویشتن را نورِ مطلق داند او

جز مگر بندهٔ خدا، یا جذبِ حق
با رهش آرَد، بگردانَد ورق

تا بداند کآن خیالِ ناریه
در طریقت نیست اِلّا عاریه

نارِیه: آتشین
عاریه: قرضی
....

== اگر کسی برای خدا باشد خدا هم برای اوست

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر اوّل، بیت ۱۹۳۷
[.poem]
....
گفته او را من زبان و چشمِ تو
من حواس و من رضا و خشمِ تو

رُو که بی‌یَسْمَع و بی‌یُبصِر توی
سِر تُوی، چه جایِ صاحب‌سِر تُوی

چون شدی مَنْ کٰانَ‌ لِلَّـه از وَلَه
من تو را باشم،‌ که کٰانَ الله لَه

بی‌یَسْمَع و بی‌یُبصِر: به وسیلهٔ من می‌شنود و به وسیلهٔ من می‌بیند
وَلَه: حیرت
....

.مولوی، مثنوی، دفتر دوم، بیت ١۵٠٢
[.poem]
....
خویش را تسلیم کن بر دامِ مُزد
وانگه از خود بی زِ خود چیزی بدُزد
....

.مولوی، مثنوی، دفتر ششم، بیت ۳۴۹٢
[.poem]
....
دست، کورانه بِحَبْلِ الله زن
جز بر امر و نهیِ یزدانی مَتَن
....

.قرآن کریم، سورهٔ آل عمران (۳)، آیهٔ ۱۰۳
[.poem]
....
وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا...
و همگان دست در ریسمان خدا زنید و پراکنده مشوید...
....

== جف القلم - هرکس سرنوشت خودش رو در این لحظه خودش تعیین میکنه

.مولوی، مثنوی، دفتر پنجم، بیت ۳۱۸۲
[.poem]
....
فعلِ توست این غُصّه‌هایِ دَم‌به‌دَم
این بُوَد معنیِّ قَدْ جَفَّ الْقَلَم

حدیث
جَفَّ الْقَلَمُ بِما أنْتَ لاقٍ
خشك شد قلم به آنچه سزاوار بودی

جَفَّ الْقَلَمُ بِما هُوَ کائنٌ
خشک شد قلم به آنچه بودنی است
....
