= گزیده برنامه ها

== آتش آب توست

.برنامه ۸۰۳، مولوی، مثنوی، دفتر پنجم، بیت شماره ۴۳۳
[.poem]
....
جَوْق‌ْجَوْق و صَفْ صَف از حرص و شِتاب
مُحْتَرِِز ز آتش، گُریزان سویِ آب

لاجَرَم ز آتش برآوردند سر
ِاعْتِبارَالْاِعْتِبار ای بی‌خبر

بانگ می‌زد آتش ای گیجانِ گول
من نِیَ ام آتش، منم چشمهٔ قبول

چشم‌ْبندی کرده‌اند ای بی‌نَظَر
در من آی و هیچ مَگْریز از شَرَر

ای خلیل اینجا شَرار و دود نیست
جز که سِحْر و خُدْعهٔ نمرود نیست

چون خلیلِ حق اگر فرزانه‌ای
آتش آبِ توست و تو پروانه‌ای

جَوْق‌ْجَوْق: دسته دسته، جمع آن اَجْواق است.
مُحْتَرِِز: دوری کننده، پرهیز کننده
اعتباراَلِْاعتبار: عبرت بگیر، عبرت بگیر.
گول: ابله، نادان
شَرار: پاره آتشی که به هوا جهد، جرقه
....

== آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر سوم، بیت ۳۶۰۲
[.poem]
....
آدابُ الْمُسْتَمِعینَ َوالْمُریدینَ عِنْدَ فَیْضِ الْحِکْمَةِ مِنْ لِسانِ الشَّیخ
آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

بر مَلولان، این مکرّر کردن است
نزدِ من عمرِ مکرَّر بُردن است

شمع از برقِ مُکَرَّر بر شود
خاک از تابِ مُکَرَّر زر شود

گر هزاران طالبند و، یک مَلول
از رسالت باز می‌مانَد رسول

این رسولانِ ضمیرِ رازگُو
مُسْتَمع خواهند، اِسرافیل‌خو

نخوتی دارند و، کبری چون شهان
چاکری خواهند از اهلِ جهان

نخوت: تکبر، خودبزرگ‌بینی

تا ادب‌هاشان به جاگَه نآوری
از رسالتْشان چگونه بر خوری؟

بَر خوری: میوه خوری، برخوردار شوی

کی رسانند آن امانت را به تو
تا نباشی پیششان راکع دوتو؟

راکع: رکوع کننده
دوتو: خمیده، دولا

هر ادبْشان کَی همی‌ آید پسند؟
کآمدند ایشان ز ایوانِ بلند

نه گدایانند کز هر خدمتی
از تو دارند ای مزوِّر مِنّتی

لیک با بی‌رغبتی‌ها ای ضمیر
صدقهٔ‌ سلطان بیفشان، وامگیر

اسبِ خود را، ای رسولِ آسمان
در ملولان منگر و، اندر جهان

فرّخ آن تُرکی که استیزه نهد
اسبش اندر خندقِ آتش جهد

تُرک: در اینجا به معنی جنگاور و مجاهد دلاور است.
استیزه نهد: جنگ و جهاد کند، دلاوری و جنگاوری از خود نشان دهد.

گرم گرداند فَرَس را آنچنان
که کند آهنگِ اوجِ آسمان

چشم را از غیر و غیرت دوخته
همچو آتش خشک و، تر را سوخته

گر پشیمانی بر او عیبی کند
آتش اوّل در پشیمانی زند

خود، پشیمانی نروید از عدم
چون ببیند گرمیِ صاحب‌قدم
....