= گزیده کتاب ها

== با پیر بلخ، کاربرد مثنوی در خودشناسی، محمد جعفر مصفا

مجنون سوار بر ناقه می شود تا بسوی لیلی برود. اما چون ناقه هوای دیگر و مقصد دیگری در سر
دارد سالها مجنون را در سرگردانی و تردد مشغول می دارد و او را به لیلی نمی رساند.

[.poem]
....
آنکه او باشد مراقب عقل بود
عقل را سودای لیلی در ربود
....

عقل در انسان، حاکم و مراقب کارساز و راه برنده‌ای است. اما وقتی انسان اسیر «لیلی نفس» شد،
سودای لیلی، این راهبر را دنگ و منگ می کند. شاید لیلی سمبل خواسته‌های تصوری و ایده‌آلی‌ای
باشد که نفس بر انسان دیکته می کند. خواسته‌هایی که چون بت لیلی در ذهن ما نشسته‌اند و چنان
جذبه کور کننده‌ای پیدا کرده‌اند که نمی گذارند هوش و حواسمان بجا باشد.

[.poem]
....
آنکه او باشد مراقب عقل بود
عقل را سودای لیلی در ربود

لیک ناقه بس مراقب بود و چست
چون بدیدی او مهار خویش سست

فهم کردی زو که غافل گشت و دنگ
رو سپس کرده به کُرّه بیدرنگ
....

عوامل و پرسناژهای داستان اینها هستند: مجنون سمبل خواسته‌های آزمندانه انسان یا خود انسان
است. لیلی، موضوع و هدف خاص آن خواسته هاست - که همه سرا‌بگونه و رؤیائی و ایده‌آلی است.
ناقه هم سمبل فکر است. انسان بوسیلهٔ مرکب فکر میخواهد به آرزوهای رؤیائی خود دست یابد
اما فکر مرکب مناسبی برای رسیدن به آن ایده‌آلها نیست - فکر هوای کره‌های خودش را دارد. یعنی
اسیر چیزهائی است که هم اکنون در آنها غوطه‌ور است. مجنون خواسته‌هائی بلند پرواز و ایده‌آلی
دارد ولی فکر یا ناقه اسیر کره‌ها و مشغولیاتی است که او را در خود گرفته‌اند. مجنون با ناقه
در کشمکش است. ناقه یکقدم مجنون را به سوی لیلی می‌برد ولی همینکه مهار خود را سست میبیند
به عقب بر‌می‌گردد و بسوی کره خود میرود. گمان میکنم در این داستان مولوی جریاناتی را ترسیم
می کند که در طریق «سلوک» پیش می آید. می خواهد به «سالک» هشدار بدهد که مواظب فریبها و
بازیهای فکر باش.

[.poem]
....
چون بخود باز آمدی دیدی زجا
کوسپس رفته است بس فرسنگها

در سه روزه ره بدین منوال ها
ماند مجنون در تردد سالها

گفت ای ناقه چو هر دو عاشقیم
ما دو ضد بس همره نالایقیم
....

بعد از سالها تردد، بالاخره مجنون به راهنمائی عقل مفید خویش در می یابد که «‌ناقه
نفس‌» یا عقل جزئی مرکب مناسبی در طریق لیلی‌ ایده‌آلی او نیست و باید او را رها کرد و این
ادراک مقدمه مفیدی است.

[.poem]
....
نیست بر وفق منت مهر و مهار
کرد باید از تو عزلت اختیار
....

اختیار تو در دست من نیست، تو اماره‌ای، تو حاکم بر راه و رابطه‌ای، تو مرا به
میل خودت میبری، نه من ترا. پس تو بدرد من نمی‌خوری.

[.poem]
....
این دو هـمـره یکدگر را راهزن
گمره آن جان کو فرو ناید ز تن

جان زهجر عرش اندر فاقه‌ای
تن ز عشق خاربن چون ناقه‌ای

جان گشاید سوی بالا بالها
در زده تن در زمین چنگالها
....

جان هوای عرش دارد، سودای پرواز ملکوتی دارد؛ اما «‌تن‌» که
پایگاه «‌نفس‌» است و به پستی‌های این جهان خو گرفته و آموخته شده است، همچو
ناقه‌ای پنجه و پوزه در خارهای پست این دنیای خاکی فرو کرده است و نشخوار
پستیها را می کند.

مجنون بعد از این ادراکات عقلی، همت خفته خود را هی میزند، بیدار می کند و با
نهیب بر سر این مرکب ابتر و کژ‌رو از آن فرود می آید می گوید:

[.poem]
....
تا تو با من باشی ای مرده وطن
بسی زلیلی دور مانده جان من

راه نزدیک و بماندم سخت دیر
سیر گشتم زین سواری سیر سیر!
....

از دست فکر اماره کارد باستخوانش رسیده، وخامت آنرا درک کرده و از آن فرود
می آید. لب مطلب مورد نظر ما از اینجا به بعد است:

[.poem]
....
آنچنان افکند خود را سخت زیر
که مخلخل گشت جان آن دلیر

چون چنان افکند خود را از زیر و پست
از قضا آن لحظه پایش هم شکست

پای را بر بست و گفتا گو شوم
در خم چوگانش غلطان میروم

عشق مولی کی کم از لیلی بود!
گوی گشتن بهر او اولی بود
....

مولوی در این قسمت از داستان چند تغییر اساسی می دهد و چند موضوع جدید را
وارد میکند. اولاً هنگام فرود آمدن از ناقه پای مجنون می شکند، ثانیاً برای
حرکت میگوید باید «‌گوی» گشت، ثالثاً در این مرحله عشق لیلی تبدیل به عشق مولی
میگردد. این تغییرات قابل تأمل است. می گویند وقتی مجنون به لیلی میرسد یک
حالت بورشدگی پیدا می کند و می گوید لیلائی که من در جستجویش بودم این نیست، من،
لیلای لیلا رو می‌خواهم.

لیلائی که مجنون به او رسیده یا میخواهد برسد، لیلای تجسم فکر و عقل خود اوست؛
حاصل یک ترسیم ذهنی است - مثل هدفها و خواسته‌هائی که بصورت ایده‌آل در
کارگاه «هویت فکری» ترسیم می گردد‌؛ و وقتی انسان به آنها دست مییابد احساس میکند
چیزی که به آن رسیده آن نبوده که او می خواسته است. اما «لیلای لیلا» چیز دیگری
است. چیزی است ورای فکر و ترسیم ذهنی انسان.

هنگام فرود آمدن از ناقه پای مجنون میشکند. ببینیم با آوردن «پا» می خواهد چه
گفته باشد. مجنون ابتدا سوار بر «ناقه نفس» است و در اختیار آن – یعنی در اختیار عقل
جزئی، مجازی و توهمی. عقل جزئی حاکم بر اوست و او را می‌برد. بعد عقل مفید و
واقعی او بجا می‌آید و این حقیقت را درک می کند که ناقه نفس یا عقل جزئی
نمیتواند او را به ایده‌آل های او برساند. این ناقه او را در تردد نگه میدارد و
دور خودش می چرخاند. بنابراین از عقل نفس آلود یا ناقه فرود می آید. ولی اینهم
مقدمه یک حرکت و مقصد دیگر است. مجنون تا وقتی سوار بر «ناقه نفس» است اسیر
اوهام و پندارهای ایده‌آلی خویش است، و بنابراین ترسیم او از همه چیز تحت تأثیر
آن اوهام است. اما همین که خود را از چنگال چنان عقلی خارج می‌سازد همه چیز
برایش کیفیت دیگری پیدا می‌کند. مجنون تا زمانی که اسیر نفس است و اوهام برخاسته
از نفس، کور و منگش کرده است، به عشق لیلی می اندیشد و به دنبال آن می رود. اما
وقتی از اسارت نفس، یعنی از اسارت عقل جزئی آزاد شد، عشق برایش کیفیت دیگری
می‌یابد - عشق لیلا به عشق مولی تبدیل میگردد.

و همزمان با این تغییر این حقیقت را هم در می‌یابد که در طریق چنان عشقی
یعنی عشق مولی، «پا» یک وسیلۀ غیر مفید و نامناسب است. در طریق آن عشق باید «گوی» گشت. «پا» سمبل
عقل مفید است و وسیله مناسبی است در طریق امور مادی زندگی.

[.poem]
....
پای را بر بست و گفتا گو شوم
در خم چوگانش غلطان میروم
....

پا نمیتواند ابزار حرکت به سوی عشق مولائی و الهی باشد. در این راه باید «گوی» گشت.
گوی سمبل تفویض است، کیفیتی است که در آن تمام خواسته‌ها و تعلقات
تشکیل دهندۀ «نفس» خود را تفویض و تسلیم به عشق الله می کنند. گوی سمبل بی
شکلی است؛ کیفیت ابزار و وسیله رفتن و پیمودن را - مثل پا – ندارد. در حرکت
گوی تلاش و جست و خیز وجود ندارد، بلکه بوسیله چوگان رانده می شود - یعنی
نمی رود بلکه برده می‌شود. سر تیزی و زیرکی حرکت‌های ذهنی و عقلی در آن
نیست؛ و خلاصه سمبل نخواستن و وسیله بی وسیله‌ای است برای اتصال به کیفیت
های ورای شکل، ورای توصیف، ورای تعین و ورای بعد و عدد.
