= گزیده کتاب ها

== با پیر بلخ، کاربرد مثنوی در خودشناسی، محمد جعفر مصفا

مجنون سوار بر ناقه می شود تا بسوی لیلی برود. اما چون ناقه هوای دیگر و مقصد دیگری در سر
دارد سالها مجنون را در سرگردانی و تردد مشغول می دارد و او را به لیلی نمی رساند.

[.poem]
....
آنکه او باشد مراقب عقل بود
عقل را سودای لیلی در ربود
....

عقل در انسان حاکم و مراقب کارساز و راه برنده ای است. اما وقتی انسان اسیر « لیلی نفس » شد،
سودای لیلی این راهبر را دنگ و منگ می کند. شاید لیلی سمبل خواسته‌های تصوری و ایده‌آلی‌ای
باشد که نفس بر انسان دیکته می کند. خواسته‌هایی که چون بت لیلی در ذهن ما نشسته اند و چنان
جذبه کور کننده‌ای پیدا کرده‌اند که نمی گذارند هوش و حواسمان بجا باشد.

[.poem]
....
آنکه او باشد مراقب عقل بود
عقل را سودای لیلی در ربود

لیک ناقه بس مراقب بود و چست
چون بدیدی او مهار خویش سست

فهم کردی زو که غافل گشت و دنگ
رو سپس کرده به کُرّه بیدرنگ
....

عوامل و پرسناژهای داستان اینها هستند: مجنون سمبل خواسته های آزمندانه انسان یا خود انسان
است. لیلی، موضوع و هدف خاص آن خواسته هاست - که همه سرا بگونه و رؤیائی و ایده آلی است.
ناقه هم سمبل فکر است. انسان بوسیلهٔ مرکب فکر میخواهد به آرزوهای رؤیائی خود دست یابد
اما فکر مرکب مناسبی برای رسیدن به آن ایده‌آلها نیست - فکر هوای کره‌های خودش را دارد. یعنی
اسیر چیزهائی است که هم اکنون در آنها غوطه‌ور است. مجنون خواسته‌هائی بلند پرواز و ایده‌آلی
دارد ولی فکر یا ناقه اسیر کره‌ها و مشغولیاتی است که او را در خود گرفته‌اند. مجنون با ناقه
در کشمکش است. ناقه یکقدم مجنون را به سوی لیلی می‌برد ولی همینکه مهار خود را سست میبیند
به عقب بر‌می گردد و بسوی کره خود میرود. گمان میکنم در این داستان مولوی جریاناتی را ترسیم
می کند که در طریق «سلوک» پیش می آید. می خواهد به «سالک» هشدار بدهد که مواظب فریبها و
بازیهای فکر باش.

[.poem]
....
چون بخود باز آمدی دیدی زجا
کوسپس رفته است بس فرسنگها

در سه روزه ره بدین منوال ها
ماند مجنون در تردد سالها

گفت ای ناقه چو هر دو عاشقیم
ما دو ضد بس همره نالایقیم
....

بعد از سالها تردد، بالاخره مجنون به راهنمائی عقل مفید خویش در می یابد که « ناقه
نفس » یا عقل جزئی مرکب مناسبی در طریق لیلی‌ ایده‌آلی او نیست و باید او را رها کرد و این
ادراک مقدمه مفیدی است.

[.poem]
....
نیست بر وفق منت مهر و مهار
کرد باید از تو عزلت اختیار
....
