= برنامه ۱۰۰۰
:toc:
:toc-title!:
:nofooter:

== در خودتون و دیگران زندگی رو ببینید

audio::/media/audio/1000/dar_khodetoon_va_digaran_zendegi_ro_bebinid.mp3[controls]

.برنامه ۱۰۰۰، مولوی، دیوان شمس، غزل شمارهٔ ۵۱
[.poem]
....
گر تو ملولی ای پدر، جانبِ یارِ من بیا
تا که بهارِ جان‌ها تازه کند دلِ تو را

بویِ سلامِ یارِ من، لَخْلَخهٔ بهارِ من
باغ و گُل و ثِمارِ من، آرَد سویِ جان، صبا

مستی و طُرفه مستی‌ای، هستی و طُرفه هستی‌ای
مُلک و درازدَستی‌ای، نعره‌زنان که: «اَلصَّلا»

پای بکوب و دست زن، دست در آن دو شَسْت زن
پیشِ دو نرگسِ خوشش کُشته نگر دلِ مرا

لَخْلَخه: ترکیبی از عطرها و بوهای خوش
ثِمار: جمعِ ثمر، میوه‌ها
طُرفه: عجیب، شگفت
درازدَستی‌: تجاوز، دست‌اندازی، چشم‌داشت و طمع داشتن
اَلصَّلا: دعوتِ عمومی
شَسْت: قُلّاب ماهیگیری، «دو شَسْت» کنایه از موی جلوی سر است که به دو بخش تقسیم شود و بافته گردد.
....

== ینظر بنورالله

audio::/media/audio/1000/yanzoro_benoorollah.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر دوم، بیت ۱۵۶۷
[.poem]
....
شیخ کو یَنْظُر بِنورِالله شد
از نهایت، وز نخست آگاه شد

حدیث
«اِتَّقُوا فَراسَةَ الْمُؤمِنِ فَاَنَّهُ يَنْظُرُ بِنُورِاللهِ.»
«بترسید از زیرکیِ مؤمن که او با نور ِخدا می‌بیند.»
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۵۰۱
[.poem]
....
اوّل و آخِر تویی ما در میان
هیچ هیچی که نیاید در بیان

«همانطور که عظمت بی‌نهایت الهی قابل بیان نیست و باید به آن زنده شویم، ناچیزی ما هم به عنوان من ذهنی
قابل بیان نیست و ارزش بیان ندارد. باید هر چه زودتر آن را انکار کنیم و به او زنده شویم.»
....

.قرآن کریم، سورهٔ حدید (۵۷)، آیهٔ ۳
[.poem]
....
«هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ.»
«اوست اوّل و آخر و ظاهر و باطن، و او به هر چيزى داناست.»
....

== اگر کسی برای خدا باشد خدا هم برای اوست

audio::/media/audio/1000/agar_kasi_baraye_khoda_bashad_khoda_ham_baraye_oust.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر اوّل، بیت ۱۹۳۷
[.poem]
....
گفته او را من زبان و چشمِ تو
من حواس و من رضا و خشمِ تو

رُو که بی‌یَسْمَع و بی‌یُبصِر توی
سِر تُوی، چه جایِ صاحب‌سِر تُوی

چون شدی مَنْ کٰانَ‌ لِلَّـه از وَلَه
من تو را باشم،‌ که کٰانَ الله لَه

بی‌یَسْمَع و بی‌یُبصِر: به وسیلهٔ من می‌شنود و به وسیلهٔ من می‌بیند
وَلَه: حیرت
....

.مولوی، مثنوی، دفتر دوم، بیت ١۵٠٢
[.poem]
....
خویش را تسلیم کن بر دامِ مُزد
وانگه از خود بی زِ خود چیزی بدُزد
....

.مولوی، مثنوی، دفتر ششم، بیت ۳۴۹٢
[.poem]
....
دست، کورانه بِحَبْلِ الله زن
جز بر امر و نهیِ یزدانی مَتَن
....

.قرآن کریم، سورهٔ آل عمران (۳)، آیهٔ ۱۰۳
[.poem]
....
وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا...
و همگان دست در ریسمان خدا زنید و پراکنده مشوید...
....

== خدا توبه پذير و مهربان است

audio::/media/audio/1000/khoda_tobe_pazir_va_mehraban_ast.mp3[controls]

.برنامه ۱۰۰۰، قرآن کریم، سورهٔ حجرات (۴۹)، آیهٔ ۱۲
[.poem]
....
يَا أَيُّهَا الَّذِينَ آمَنُوا اجْتَنِبُوا كَثِيرًا مِنَ الظَّنِّ إِنَّ بَعْضَ الظَّنِّ إِثْمٌ ۖ وَلَا تَجَسَّسُوا وَلَا يَغْتَبْ
بَعْضُكُمْ بَعْضًا ۚ أَيُحِبُّ أَحَدُكُمْ أَنْ يَأْكُلَ لَحْمَ أَخِيهِ مَيْتًا فَكَرِهْتُمُوهُ ۚ وَاتَّقُوا اللهَ ۚ إِنَّ اللهَ تَوَّابٌ رَحِيمٌ

اى كسانى كه ايمان آورده‌ايد، از گمان فراوان بپرهيزيد.
زيرا پاره‌اى از گمانها در حد گناه است. و در كارهاى پنهانى يكديگر جست و جو مكنيد.
و از يكديگر غيبت مكنيد. آيا هيچ يک از شما دوست دارد كه گوشت برادر مردهٔ خود را بخورد؟
پس آن را ناخوش خواهيد داشت. و از خدا بترسيد، زيرا خدا توبه‌پذير و مهربان است.

چون ز غیبت، وَاکْلِ لَحْمِ مردمان
شصت سالت سیریی نآمد از آن؟

اَکْل: خوردن
لَحْم: گوشت
....

== در این لحظه چاره ای به جز تسلیم و رضا نداریم

audio::/media/audio/1000/dar_in_lahze_chare_i_be_joz_taslim_va_reza_nadarim.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر ششم، بیت ۵۷۶
[.poem]
....
ای رفیقان، راهها را بست یار
آهویِ لنگیم و او شیرِ شکار

جز که تسلیم و رضا کو چاره‌ای؟
در کفِ شیرِ نرِ خون‌خواره‌ای

او ندارد خواب و خور، چون آفتاب
روح‌ها را می‌کند بی‌خورد و خواب
....

.قرآن کریم، سورهٔ بقره (۲)، آیهٔ ۲۵۵
[.poem]
....
«اللهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ… .»

«الله خدايى است كه هيچ خدايى جز او نيست. زنده و پاينده است.
نه خواب سبك او را فرا مى‌گيرد و نه خواب سنگين… .»
....

.قرآن کریم، سورهٔ انعام (۶)، آیهٔ ۱۴
[.poem]
....
«… وَهُوَ يُطْعِمُ وَلَا يُطْعَمُ ۗ … .»
«… و مى‌خوراند و به طعامش نياز نيست… .»

که بیا من باش یا همخویِ من
تا ببینی در تجلّی رویِ من

حديث
«تَخَلَّقوا بِأَخلاقِ الله»
«من در باطن كسی تجلی خواهم کرد که خوی الهی بپذیرد
و از خوی و عادت مادی و حیوانی دوری کند.»
....

== درد و چالش سبب فضاگشایی هستن

audio::/media/audio/1000/dard_va_chalesh_sabab_fazagoshaei_hastan.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر ششم، بیت ۴۲۹۹
[.poem]
....
درد، دارویِ کهن را نَوْ کند
درد، هر شاخِ ملولی خَوْ کند

کیمیایِ نوکننده، دردهاست
کو ملولی آن‌طرف که درد خاست؟

هین مزن تو از ملولی آهِ سرد
درد جو و، درد جو و، درد، درد

خَوْ کردن: وَجین کردن، هَرَس کردن درخت
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۱۳۷
[.poem]
....
گفت: رُو، هر که غمِ دین برگزید
باقیِ غم‌ها خدا از وی بُرید

حدیث
«مَنْ جَعَلَ الْهُمُومَ هَمًّا وَاحِدًا هَمَّ الْمَعَادِ كَفَاهُ اللَّهُ هَمَّ دُنْيَاهُ
وَمَنْ تَشَعَّبَتْ بِهِ الْهُمُومُ فِي أَحْوَالِ الدُّنْيَا لَمْ يُبَالِ اللَّهُ فِي أَىِّ أَوْدِيَتِهِ هَلَكَ.»

«هر کس غم‌هایش را به غمی واحد محدود کند، خداوند غمهای
دنیوی او را از میان می‌برد. و اگر کسی غم‌های مختلفی داشته باشد،
خداوند به او اعتنایی نمی‌دارد که در کدامین سرزمین هلاک گردد.»
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۳۹۶
[.poem]
....
پس ریاضت را به جان شو مُشتری
چون سپردی تن به خدمت، جان بَری

ور ریاضت آیدت بی‌اختیار
سر بنهْ، شکرانه دِهْ، ای کامیار

چون حقت داد آن ریاضت، شکر کن
تو نکردی، او کشیدت ز‌امرِ کُن

ریاضت: رنج، زحمت
کامیار: کامیاب، آنکه به آرزوی خود رسیده است.
امرِ کُن: فرمانِ «بشُو و می‌شودِ» خداوند.
....

== آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

audio::/media/audio/1000/adaab_shenavandegan_va_moridan_angah_ke_sokhanan_hekmat_amiz_az_zaban_sheykh_jari_shavad.mp3[controls]

.برنامه ۱۰۰۰، مولوی، مثنوی، دفتر سوم، بیت ۳۶۰۲
[.poem]
....
آدابُ الْمُسْتَمِعینَ َوالْمُریدینَ عِنْدَ فَیْضِ الْحِکْمَةِ مِنْ لِسانِ الشَّیخ
آداب شنوندگان و مریدان، آنگاه که سخنان حکمت‌آمیز از زبان شیخ جاری شود

بر مَلولان، این مکرّر کردن است
نزدِ من عمرِ مکرَّر بُردن است

شمع از برقِ مُکَرَّر بر شود
خاک از تابِ مُکَرَّر زر شود

گر هزاران طالبند و، یک مَلول
از رسالت باز می‌مانَد رسول

این رسولانِ ضمیرِ رازگُو
مُسْتَمع خواهند، اِسرافیل‌خو

نخوتی دارند و، کبری چون شهان
چاکری خواهند از اهلِ جهان

نخوت: تکبر، خودبزرگ‌بینی

تا ادب‌هاشان به جاگَه نآوری
از رسالتْشان چگونه بر خوری؟

بَر خوری: میوه خوری، برخوردار شوی

کی رسانند آن امانت را به تو
تا نباشی پیششان راکع دوتو؟

راکع: رکوع کننده
دوتو: خمیده، دولا

هر ادبْشان کَی همی‌ آید پسند؟
کآمدند ایشان ز ایوانِ بلند

نه گدایانند کز هر خدمتی
از تو دارند ای مزوِّر مِنّتی

لیک با بی‌رغبتی‌ها ای ضمیر
صدقهٔ‌ سلطان بیفشان، وامگیر

اسبِ خود را، ای رسولِ آسمان
در ملولان منگر و، اندر جهان

فرّخ آن تُرکی که استیزه نهد
اسبش اندر خندقِ آتش جهد

تُرک: در اینجا به معنی جنگاور و مجاهد دلاور است.
استیزه نهد: جنگ و جهاد کند، دلاوری و جنگاوری از خود نشان دهد.

گرم گرداند فَرَس را آنچنان
که کند آهنگِ اوجِ آسمان

چشم را از غیر و غیرت دوخته
همچو آتش خشک و، تر را سوخته

گر پشیمانی بر او عیبی کند
آتش اوّل در پشیمانی زند

خود، پشیمانی نروید از عدم
چون ببیند گرمیِ صاحب‌قدم
....
