= برنامه ۷۹۷
:toc:
:toc-title!:
:nofooter:

== آینه کلی

audio::/media/audio/797/ayene_kolli.mp3[controls]

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۷۴۵
[.poem]
....
فضول گشته‌ام امروز، جنگ می جویم
منوش نکته مستان که یاوه می گویم

منوش: مشنو (از مصدر نیوشیدن)
یاوه: مجازاً سخن بیهوده و بی معنی، شوخی بی مزه

آینهٔ جان نیست اِلّا رویِ یار
رویِ آن یاری که باشد زآن دیار

گفتم: ای دل آینهٔ کُلّی بجو
رَوْ به دریا، کار بر ناید به جُو

آینهٔ کُلّی: در اینجا اشاره به انسانهای رشد یافته و به کمال رسیده می باشد.

زین طلب بنده به کویِ تو رسید
دردْ، مریم را به خُرمابُن کَشید

خُرمابُن: درخت خرما، نخل

از خدا غير خدا را خواستن
ظن افزوني است و كلي كاستن
....

.قرآن کریم، سوره مريم (۱۹)، آیه ۲۳
[.poem]
....
« فَأَجَاءَهَا الْمَخَاضُ إِلَىٰ جِذْعِ النَّخْلَةِ قَالَتْ يَا لَيْتَنِي مِتُّ قَبْلَ هَٰذَا وَكُنْتُ نَسْيًا مَنْسِيًّا »

« درد زاييدن او را به سوى تنه درخت خرمايى كشانيد. گفت: اى كاش پيش از اين مرده بودم و از يادها فراموش شده بودم. »
....

[.poem]
....
دیدهٔ تو چون دلم را دیده شد
شد دلِ نادیده، غرقِ دیده شد

آینهٔ کُلّی تو را دیدم اَبَد
دیدم اندر چشمِ تو، من نقشِ خَود

گفتم: آخر خویش را من یافتم
در دو چشمش، راهِ روشن یافتم

گفت وَهمَم: کان خیالِ توست هان
ذاتِ خود را از خیالِ خود بدان

وَهمَ: خیال، پندار، آن قسمت از مغز که تخیّل می کند.

نقش من از چشم تو آواز داد
که منم تو، تو منی در اتحاد
....

== افسانه من ذهنی

audio::/media/audio/797/afsane_man_zehni.mp3[controls]

موانع مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی، که به نظر
من نمی گذارند، من در این لحظه زندگی کنم و اگر آن موانع رفع شوند، زندگی
من شروع می شود.

مسایل مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی که خودشان
را به من به صورت گره ذهنی یا مساله ارائه می کنند و من نمی خواهم یا اصلاً
نمی توانم برای حل آنها کاری کنم.

دشمنان مَنِ ذهنی من: اشخاص و یا وضعیت های ساخته شده به وسیله من ذهنی،
که به نظر من فعالانه در پایین آوردن کیفیت زندگی من یا محروم کردن من از زندگی
می کوشند. من ذهنی برای بقا، از آنها به صورت قطب استفاده می کند و انرژی
مخرب ایجاد میکند.

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شماره ۱۳۴۴
[.poem]
....
دمِ او جان دهدت رو ز نَفَخْتُ بپذیر
کارِ او کُنْ فَیَکُون ‌ست، نه موقوفِ علل

نَفَخْتُ: دمیدم
....

== یابی اندر دید او کل غرض

audio::/media/audio/797/yabi_andar_dide_oo_kolle_gharaz.mp3[controls]

.برنامه ۷۹۷، مولوی، مثنوی، دفتر اول، بیت ۹۲۱
[.poem]
....
دیده ما چون بسی علّت دروست
رو فنا کُن دید خود در دید دوست

دید ما را دید او نِعْمَ الْعِوَض
یابی اندر دید او کل غَرَض
....

== شما مسئول مداومت تعهدتون هستید

audio::/media/audio/797/shoma_masoule_modavemate_taahodetoon_hastid.mp3[controls]

.برنامه ۷۹۷، مولوی، مثنوی، دفتر پنجم، بیت ۱۲۱۱
[.poem]
....
شرع بهرِ دفعِ شَرّ رایی زند
دیو را در شیشهٔ حجّت کند
....

== از میان نردبان نگریختم

audio::/media/audio/797/az_mian_nardeban_nagrikhtam.mp3[controls]

.برنامه ۷۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۶۵۸
[.poem]
....
عاشقم، از عاشقان نگریختم
وز مَصاف ای پهلوان، نگریختم

حمله بردم سوی شیران همچو شیر
همچو روبه از میان نگریختم

قصدِ بامِ آسمان می داشتم
از میانِ نردبان نگریختم

چونکه من دارو بدم هر درد را
از صُداعِ این و آن نگریختم

هیچ دیدی دارو کز دردی گریخت؟
داروَم من، همچنان نگریختم

پیروِ پیغامبران بودم به جان
من ز تهدیدِ خَسان نگریختم

زنده کوشم در شکارِ زندگی
زنده باشم، چون ز جان نگریختم

چشمِ تیراندازش آنگه یافتم
که ز تیرِ خَرکمان نگریختم

زخمِ تیغ و تیرِ من منصور شد
چون که از زخمِ سِنان نگریختم

بحرِ قندم، از تُرُش باکیم نیست
سودمندم، از زیان نگریختم

شمسِ تبریزی چو آمد آشکار
ز آشکارا و نهان نگریختم
....

== آدمى را در رنج و محنت بيافريده‌ايم

audio::/media/audio/797/adami_ra_dar_ranj_o_mehnat_biafaride_im.mp3[controls]

.برنامه ۷۹۷، قرآن کریم، سوره بلد(۹۰)، آیه ۱۲-۱
[.poem]
....
لَا أُقْسِمُ بِهَٰذَا الْبَلَدِ
قسم به اين شهر.

وَأَنْتَ حِلٌّ بِهَٰذَا الْبَلَدِ
و تو در اين شهر سكنا گرفته‌اى.

وَوَالِدٍ وَمَا وَلَدَ
و قسم به پدر و فرزندانى كه پديد آورد.

لَقَدْ خَلَقْنَا الْإِنْسَانَ فِي كَبَدٍ
كه آدمى را در رنج و محنت بيافريده‌ايم.

أَيَحْسَبُ أَنْ لَنْ يَقْدِرَ عَلَيْهِ أَحَدٌ
آيا مى‌پندارد كه كس بر او چيره نگردد؟

يَقُولُ أَهْلَكْتُ مَالًا لُبَدًا
مى‌گويد: مالى فراوان را تباه كردم.

أَيَحْسَبُ أَنْ لَمْ يَرَهُ أَحَدٌ
آيا مى‌پندارد كه كسى او را نديده است؟

أَلَمْ نَجْعَلْ لَهُ عَيْنَيْنِ
آيا براى او دو چشم نيافريده‌ايم؟

وَلِسَانًا وَشَفَتَيْنِ
و يك زبان و دو لب؟

وَهَدَيْنَاهُ النَّجْدَيْنِ
و دو راه پيش پايش ننهاديم؟

فَلَا اقْتَحَمَ الْعَقَبَةَ
و او در آن گذرگاه سخت قدم ننهاد.

وَمَا أَدْرَاكَ مَا الْعَقَبَةُ
و تو چه دانى كه گذرگاه سخت چيست؟
....

== نعمت آرد غفلت و شکر انتباه

audio::/media/audio/797/nemat_arad_ghaflat_va_shokr_entebah.mp3[controls]

== اگر تو عاشقی غم را رها کن

audio::/media/audio/797/agar_to_asheghi_gham_ra_raha_kon.mp3[controls]
