= برنامه ۸۰۳
:toc:
:toc-title!:
:nofooter:

== خدا به مرکز همانیده حمله میکنه

audio::/media/audio/803/khoda_be_markaze_hamanide_hamle_mikone.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر دوم، بیت شماره ۱۳۰۰
[.poem]
....
این جهان چون خَس به دستِ بادِ غیب
عاجزی پیشه گرفت و دادِ غیب

عاجزی پیشه گرفت: ناتوانی را پیشه خود ساخته است.
دادِ غیب: قدرت تصرّف عالم غیب.

گه بلندش می‌کند، گاهیش پَست
گه دُرستش می‌کند، گاهی شِکست

گه یَمینش می‌برد، گاهی یَسار
گه گلستانش کند، گاهیش خار

یَمین: دست راست.
یَسار: دست چپ.

دست پنهان و، قلم بین خطْ ‌گُزار
اسب در جَوْلان و، ناپیدا سوار

تیر، پَرّان بین و ناپیدا کمان
جان ها پیدا و پنهان، جانِ جان

تیر را مَشْکَن که آن تیرِ شَهی است
نیست پَرتاوی، ز شَصْت آگهی است

ما رَمَیْتَ اِذْ رَمَیْتَ گُفت حق
کارِ حق بر کارها دارد سَبَق

قرآن کریم، سوره انفال (۸)، آیه ١٧
وَمَا رَمَيْتَ إِذْ رَمَيْتَ وَلَٰكِنَّ اللَّهَ رَمَىٰ
و آنگاه كه تير مى‌انداختى، تو تير نمى‌انداختى، خدا بود كه تير مى‌انداخت

خشمِ خود بشکن، تو مشکن تیر را
چشمِ خشمت خون شمارد شیر را

بوسه دِه بر تیر و پیشِ شاه بَر
تیرِ خونْ‌آلود از خونِ تو تَر

آنچه پیدا عاجز و بسته زبون
وآنچه ناپیدا، چنان تند و حَرون

حرون: سرکش، نافرمان

ما شکاریم، این چنین دامی که راست؟
گُویِ چوگانیم، چُوگانی کجاست؟

چُوگانی: اسبی که مناسب و لایق چوگان بازی باشد، چوگان

وگر به خشم روی صدهزار سال ز من
به‌ عاقبت به من آیی که منتهات منم

می‌دَرَد، می‌دوزد، این خَیّاط کو؟
می‌دمد، می‌سوزد، این نَفّاط کو؟

نَفّاط: ظرف مسین که در آن نفت ریزند، نفت انداز و آتش باز، آتش افروز
....

.مولوی، مثنوی، دفتر سوم، بیت ۱۹۰۶
[.poem]
....
چون قضای حق رضایِ بنده شُد
حُکمِ او را  بندهٔ خواهَنده شُد
....

.مولوی، مثنوی، دفتر دوم، بیت ۲۵۴۴
[.poem]
....
لیک مومن دان که طَوْعاً ساجِدَست
زآنکه جویایِ رضا و قاصِدَست

طَوْعاً: با ميل، با رغبت
ساجد: سجده كننده
....

.مولوی، مثنوی، دفتر دوم، بیت ۵۹۰
[.poem]
....
گر گریزی بر امیدِ راحتی
ز آن طرف هم پیشت آید آفتی

هیچ کُنجی بی دَد و بی دام نیست
جز به خلوت گاهِ حق، آرام نیست
....

== شکر برای طوفان

audio::/media/audio/803/shokr_baraye_toofan.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر سوم، بیت شماره ۱۳۴۷
[.poem]
....
شُکر، طوفان را کنون بگماشتی
واسطهٔ اَطلال را برداشتی

زآنکه اَطلالِ لَئیم و بَد بُدند
نِی ندایی، نِی صدایی می‌زدند

من چنان اَطلال خواهم در خَطاب
کَز صدا چون کوه واگوید جواب

تا مُثنّا بشنوم من نامِ تو
عاشقم بَر نامِ جانْ آرامِ تو
....

.مولوی، دیوان شمس، غزل شمارهٔ ۲۰
[.poem]
....
پیش از تو خامانِ دگر، در جوشِ این دیگِ جهان
بس برطپیدند و نشد، درمان نبود الّا رضا
....

.مولوی، مثنوی، دفتر سوم، بیت شماره ۱۳۱۱
[.poem]
....
هین مکن، کین موجِ طوفانِ بلاست
دست و پا و آشنا، امروز لاست

بادِ قهرست و بلایِ شمع کُش
جز که شمعِ حق نمی‌پاید، خَمُش

گفت: نی، رفتم بَر آن کوهِ بلند
عاصِم ست آن کُه مرا از هر گزند

عاصِم: نگهدارنده، حفظ کننده
....

.قرآن کریم، سوره هود(۱۱)، آیه۴۳
[.poem]
....
« قَالَ سَآوِي إِلَىٰ جَبَلٍ يَعْصِمُنِي مِنَ الْمَاءِ ۚ قَالَ لَا عَاصِمَ الْيَوْمَ مِنْ أَمْرِ اللَّهِ إِلَّا مَنْ رَحِمَ ۚ وَحَالَ بَيْنَهُمَا الْمَوْجُ فَكَانَ مِنَ الْمُغْرَقِينَ »

« گفت: من بر سر كوهى كه مرا از آب نگه دارد، جا خواهم گرفت. گفت: امروز هيچ نگهدارنده‌اى از فرمان خدا نيست مگر كسى را كه بر او رحم آورد. ناگهان موج ميان آن دو حايل گشت و او از غرق‌شدگان بود.»

هین مکن، که کوه کاه است این زمان
جز حبیبِ خویش را ندْهد امان

گفت: من، کی پندِ تو بشنوده‌ام؟
که طمع کردی که من زین دُوده‌ام

دُوده: دودمان، خانواده
....

.قرآن کریم، سوره هود(۱۱)، آیه ۴۵
[.poem]
....
«…إِنَّ ابْنِي مِنْ أَهْلِي…»
«…پسرم از خاندان من بود…»

خوش نیامد گفتِ تو هرگز مرا
من بَرّی‌ام از تو در هر دو سرا

هین مکن بابا که روزِ ناز، نیست
مر خدا را خویشی و انباز نیست

تا کنون کردیّ و، این دَم نازُکی ست
اندرین درگاه، گیرا نازِ کیست؟

لَمْ یَلِدْ لَمْ یُولَدْ است او از قِدَم
نی پدر دارد، نه فرزند و، نه عم

نازُکی: دقیق، خطیر، مهم
قِدَم: ازل
....

.قرآن کریم، سوره اخلاص (۱۱۲)، آیه ۳
[.poem]
....
« لَمْ يَلِدْ وَلَمْ يُولَدْ »
« نه زاده است و نه زاده شده »

نازِ فرزندان کجا خواهد کشید؟
نازِ بابایان کجا خواهد شنید؟

نیستم مولود، پیرا کم بناز
نیستم والد، جوانا کم گُراز

نیستم شوهر، نیَم من شهوتی
ناز را بگذار، اینجا ای سِتی

جز خضوع و بندگیّ و اضطرار
اندرین حضرت ندارد اعتبار

گفت: بابا سال ها این گفته‌‌یی
باز می‌گویی، به جهل آشفته‌یی

گُرازیدن: نازیدن، با ناز و تکبّر راه رفتن
سِتی: مطلق زن، بی بی، بانو
....

== آتش آب توست

audio::/media/audio/803/atash_ab_toost.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر پنجم، بیت شماره ۴۳۳
[.poem]
....
جَوْق‌ْجَوْق و صَفْ صَف از حرص و شِتاب
مُحْتَرِِز ز آتش، گُریزان سویِ آب

لاجَرَم ز آتش برآوردند سر
ِاعْتِبارَالْاِعْتِبار ای بی‌خبر

بانگ می‌زد آتش ای گیجانِ گول
من نِیَ ام آتش، منم چشمهٔ قبول

چشم‌ْبندی کرده‌اند ای بی‌نَظَر
در من آی و هیچ مَگْریز از شَرَر

ای خلیل اینجا شَرار و دود نیست
جز که سِحْر و خُدْعهٔ نمرود نیست

چون خلیلِ حق اگر فرزانه‌ای
آتش آبِ توست و تو پروانه‌ای

جَوْق‌ْجَوْق: دسته دسته، جمع آن اَجْواق است.
مُحْتَرِِز: دوری کننده، پرهیز کننده
اعتباراَلِْاعتبار: عبرت بگیر، عبرت بگیر.
گول: ابله، نادان
شَرار: پاره آتشی که به هوا جهد، جرقه
....

== فروشوندگان را دوست ندارم

audio::/media/audio/803/foroushavandegan_ra_doost_nadaram.mp3[controls]

.برنامه ۸۰۳، مولوی، مثنوی، دفتر سوم، بیت شماره ۱۴۲۷
[.poem]
....
عاشقِ حالی، نه عاشق بر مَنی
بر امیدِ حال بر من می‌تَنی

از خدا غير خدا را خواستن
ظن افزوني است و كلي كاستن

آنکه یک دَم کم، دمی کامل بود
نیست معبود خلیل، آفِل بود

وآنکه آفِل باشد و گه آن و این
نیست دلبر، لا اُحِبُّ الْآفِلین
....

.قرآن کریم، سوره انعام(۶)، آیه ۷۵،۷۶
[.poem]
....
« وَكَذَٰلِكَ نُرِي إِبْرَاهِيمَ مَلَكُوتَ السَّمَاوَاتِ وَالْأَرْضِ وَلِيَكُونَ مِنَ الْمُوقِنِينَ » (۷۵)
«بدین سان به ابراهیم ملکوت آسمانها و زمین را نشان دادیم تا از اهل یقین گردد.»

« فَلَمَّا جَنَّ عَلَيْهِ اللَّيْلُ رَأَىٰ كَوْكَبًا ۖ قَالَ هَٰذَا رَبِّي ۖ فَلَمَّا أَفَلَ قَالَ لَا أُحِبُّ الْآفِلِينَ» (۷۶)
«چون شب او را فرو گرفت، ستاره ای دید. گفت: این است پروردگار من. چون فروشد، گفت: فروشوندگان را دوست ندارم.»
....
