= برنامه ۹۰۳
:toc:
:toc-title!:
:nofooter:

== عواملی که سبب میشود تغییر دادن خود سخت شود و انسان دچار جبر من ذهنی بشود

=== ندیدن ایراد در خود

عدم احساس نیاز به آموزش معنوی، ندیدنِ ایراد در خود و تلاش نکردن برای رفعِ ایراد.

audio::/media/audio/903/nadidane_irad_dar_khod.mp3[controls]

.برنامه ۹۰۳، مولوی، مثنوی، دفتر سوم، بیت ۲۶۷۷
[.poem]
....
انبیا گفتند: در دل علّتی‌ست
که از آن در حق‌شناسی آفتی‌ست

علّت: بیماری، مرض
....

.مولوی، مثنوی، دفتر اول، بیت ۳۲۱۲
[.poem]
....
هر که نقصِ خویش را دید و شناخت
اندر اِستِکمال خود، دواسبه تاخت

زآن نمی‌پَرّد به سویِ ذوالْجَلال
کو گُمانی می‌بَرَد خود را کمال

اِستِکمال: به کمال رسانیدن، کمال خواهی
دو اسبه تاختن: کنایه از شتاب کردن و به شتاب رفتن
....

.مولوی، مثنوی، دفتر پنجم، بیت ۲۰۶۳
[.poem]
....
تا به دیوارِ بلا نآید سَرش
نشنود پندِ دل آن گوشِ کرش
....

.مولوی، مثنوی، دفتر سوم، بیت ۲۹۹۶
[.poem]
....
ساخت موسی قدس در، بابِ صَغیر
تا فرود آرند سر قومِ زَحیر

زآنکه جَبّاران بُدند و سرفراز
دوزخ آن بابِ صغیر است و نیاز

قوم زَحیر: مردم بیمار و آزاردهنده
جَبّار: ستمگر، ظالم
....

.مولوی، مثنوی، دفتر پنجم، بیت ۵۴۴
[.poem]
....
ناز کردن خوش‌تر آید از شِکَر
لیک، کم خایَش، که دارد صد خطر

ایمن‌آباد است آن راهِ نیاز
ترکِ نازش گیر و با آن ره بساز
....

.حافظ، دیوان غزلیات، غزل شمارهٔ ۶۳
[.poem]
....
عاشق که شد که یار به حالش نظر نکرد؟
ای خواجه درد نیست وگرنه طبیب هست
....

=== عدمِ تحمّلِ دردِ هوشیارانه

پوشانیدنِ دردهای خود و بی‌حس کردنِ خود نسبت به دردی که در زیر نهفته است از طریق مشغولیت‌های
بیهوده و کارافزا، و یا پریدن از فکری به فکرِ دیگر، و همینطور عدمِ تحمّلِ دردِ هوشیارانه.

audio::/media/audio/903/adame_tahammole_darde_hoshyarane.mp3[controls]

.مولوی، مثنوی، دفتر دوم، بیت ۲۲۶۴
[.poem]
....
آن بهاران مُضمَرست اندر خزان
در بهارست آن خزان، مگْریز از آن

همرهِ غم باش، با وحشت بساز
می‌طلب در مرگِ خود عُمرِ دراز

آنچه گوید نفسِ تو کاینجا بَدَست
مَشنَوَش چون کارِ او ضد آمده‌ست

تو خلافش کُن که از پیغمبران
این چنین آمد وصیّت در جهان

مُضمَر: پنهان کرده شده، پوشیده
....

.مولوی، دیوان شمس، غزل شمارهٔ ۳۰۹۰
[.poem]
....
ز بهر پختنِ تو آتشی‌ست روحانی
چو پس جَهی چو زنان، خامِ قَلتَبان باشی

قَلتَبان: بی‌ غیرت
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۴۲
[.poem]
....
آن زِ دور آتش نمایَد، چون رَوی نوری بُوَد
همچنان که آتشِ موسی برای ابتلا

اَلصَّلا پروانه جانان قصدِ آن آتش کُنید
چون بلی گفتید اوَّل، دَر رَوید اندر بَلا

چون سَمَنْدَر در میانِ آتشَش باشد مُقام
هرکه دارد در دل و جان، اینچنین شوق و وَلا

پروانه جانان: عاشقان، پروانه صفتان
سَمندَر: جانوری خزنده که گفته اند در آتش نمی‌سوزد
وَلا: محبّت، دوستی
....

.قرآن کریم، سورهٔ طه (۲۰)، آیهٔ ۹
[.poem]
....
«وَهَلْ أَتَاكَ حَدِيثُ مُوسَىٰ.»
«آيا خبرِ موسى به تو رسيده است؟»
....

.قرآن کریم، سورهٔ اعراف (۷)، آیهٔ ۱۷۲
[.poem]
....
«…أَلَسْتُ بِرَبِّكُمْ ۖ قَالُوا بَلَى…»
«…آيا من پروردگارتان نيستم؟…»
....

.مولوی، مثنوی، دفتر سوم، بیت ۴۲۱۸
[.poem]
....
ای برادر من بر آذر چابُکم
من نه آن جانم که گَردم بیش و کم

آذر: آتش
....

.مولوی، مثنوی، دفتر اول، بیت ۳۰۰۲
[.poem]
....
ای برادر، صبر کُن بر دردِ نیش
تا رهی از نیشِ نفسِ گَبرِ خویش

دردِ نیش: كنايه از مجاهده با نفس و رياضت است
....

.مولوی، مثنوی، دفتر اول، بیت ۳۰۰۵
[.poem]
....
چون دلش آموخت شمع‌ْافروختن
آفتاب او را نیارد سوختن

گفت حق در آفتابِ مُنْتَجِم
ذکرِ تَزّاوَر، کَذیٰ عَنْ کَهْفِهِمْ

خار، جمله لطف، چون گُل می‌شود
پیشِ جزوی، کو سویِ کُلّ می‌رود
....

.قرآن کریم، سورهٔ کهف (۱۸)، آیهٔ ۱۷
[.poem]
....
«وَتَرَى الشَّمْسَ إِذَا طَلَعَتْ تَزَاوَرُ عَنْ كَهْفِهِمْ ذَاتَ الْيَمِينِ وَإِذَا غَرَبَتْ
تَقْرِضُهُمْ ذَاتَ الشِّمَالِ وَهُمْ فِي فَجْوَةٍ مِنْهُ…»

«و خورشيد را مى‌بينى كه چون برمى‌آيد، از غارشان به جانبِ
راست ميل مى‌كند و چون غروب كند ايشان را واگذارد و به
چپ گردد. و آنان در صحنهٔ غارند.»
....

=== تغییر از شما باید شروع بشه

دچار جبرِ منِ ذهنی شدن با عدم اعتقاد به این مسئله که می‌توان خود را
تغییر داد و از این دردها رها شد. تصوّرِ اینکه قضا و سرنوشتِ ما در این است
که همیشه این زندگیِ پر درد را ادامه دهیم و راهی برای رهاییِ ما وجود ندارد.

audio::/media/audio/903/taghyir_az_shoma_bayad_shoroo_beshe.mp3[controls]

.مولوی، مثنوی، دفتر اول، بیت ۱۰۶۸
[.poem]
....
هر که مانْد از کاهلی بی‌شُکر و صبر
او همین داند که گیرد پایِ جَبر

هر که جبر آورد، خود رنجور کرد
تا همان رنجوری‌اش، در گور کرد

کاهلی: تنبلی
رنجور: بیمار
....

.مولوی، مثنوی، دفتر پنجم، بیت ۳۱۸۷
[.poem]
....
ترک کن این جبر را که بس تُهی‌ست
تا بدانی سِرِّ سِرِّ جبر چیست

ترک کن این جبرِ جمعِ مَنبَلان
تا خبر یابی از آن جبرِ چو جان

مَنبَل: تنبل، کاهل، بیکار
....

=== عدمِ صدق در این راه

audio::/media/audio/903/adame_sedgh_dar_in_rah.mp3[controls]

.مولوی، مثنوی، دفتر ششم، بیت ۳۵۵
[.poem]
....
چون نبودش تخمِ صدقی کاشته
حق بَرو نسیانِ آن بگماشته

گرچه بر آتش‌زنه‌ی دل می‌زند
آن سِتارَه‌‌ش را کفِ حق می‌کُشد

آتش‌زنه: سنگِ چخماق
....

=== عدم طلب حقیقی

audio::/media/audio/903/adame_talabe_haghighi.mp3[controls]

.مولوی، مثنوی، دفتر سوم، بیت ۹۷۹
[.poem]
....
در طلب زن دایماً تو هردو دست
که طلب در راه، نیکو رهبر است
....

.مولوی، مثنوی، دفتر پنجم، بیت ۲۳۸۵
[.poem]
....
گفت پیغمبر که: بر رزق ای فتا
در فرو بسته‌ست و بر در قفل‌ها

جنبش و آمد شدِ ما و اکتساب
هست مِفتاحی بر آن قفل و حجاب

بی‌کلید، این در گشادن راه نیست
بی‌طلب، نان سنّتِ اَلله نیست

فَتا: همان فتی است به معنیِ جوان، جوانمرد
....

.مولوی، مثنوی، دفتر پنجم، بیت ۱۷۳۴
[.poem]
....
کین طلب در تو گروگانِ خداست
زآنکه هر طالب به مطلوبی سزاست

جهد کن تا این طلب افزون شود
تا دلت زین چاهِ تن بیرون شود
....
