= برنامه ۹۸۲
:toc:
:toc-title!:
:nofooter:

== استثنا کنید

audio::/media/audio/982/estesna_konid.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر سوم، بیت ۱۶۳۷
[.poem]
....
مدتی بر نذرِ خود بودش وفا
تا درآمد امتحاناتِ قضا

زین سبب فرمود: استثنا کنید
گر خدا خواهد به پیمان بر زنید

هر زمان دل را دگر مَیلی دهم
هر نَفَس بر دل دگر داغی نهم

کُلُّ اَصْباحٍ لَناٰ شَأْنٌ جَدید
کُلُّ شَیءٍ عَنْ مُرادی لایَحید

در هر بامداد کاری تازه داریم، و هیچ کاری از حیطهٔ مشیت من خارج نمی‌شود.
استثنا کنید: ان‌شاءالله بگویید، اگر خدا بخواهد بگویید.
....

.قرآن کریم، سورهٔ الرحمن (۵۵)، آیهٔ ۲۹
[.poem]
....
يَسْأَلُهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ ۚ كُلَّ يَوْمٍ هُوَ فِي شَأْنٍ.
هر كس كه در آسمانها و زمين است سائل درگاه اوست، و او هر لحظه در كارى جدید است.
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۲۲۷
[.poem]
....
هر لحظه و هر ساعت یک شیوهٔ نو آرد
شیرین‌تر و نادرتر زان شیوه‌ی پیشینش
....

== اگر قبول دارید عمل کنید روی خودتون کار کنید

audio::/media/audio/982/agar_ghabool_darid_amal_konid_roye_khodetoon_kar_konid.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر پنجم، بیت ۱۳۶۵
[.poem]
....
میلِ شهوت، کر کند دل را و کور
تا نماید خر چو یوسف، نار نور

ای بسا سرمستِ نار و نارجو
خویشتن را نورِ مطلق داند او

جز مگر بندهٔ خدا، یا جذبِ حق
با رهش آرَد، بگردانَد ورق

تا بداند کآن خیالِ ناریه
در طریقت نیست اِلّا عاریه

نارِیه: آتشین
عاریه: قرضی
....

== رحمت خدا فقط بستگی به فضاگشایی ما در این لحظه داره نه به گذشتمون

audio::/media/audio/982/rahmate_khoda_faghat_bastegi_be_fazagoshaei_ma_dar_in_lahze_dare_na_be_gozashtemoon.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر دوم، بیت ۳۷۸۵
[.poem]
....
چشمِ او مانده‌ست در جُویِ روان
بی‌خبر از ذوقِ آبِ آسمان

مَرْکبِ هِمّت سویِ اسباب راند
از مُسَبِّب لاجَرَم محروم ماند

آنکه بیند او مُسَبِّب را عیان
کِی نهد دل بر سبب‌هایِ جهان؟
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۱۵۳
[.poem]
....
تو ز طفلی چون سبب‌ها دیده‌يی
در سبب، از جهل بر چفسیده‌‌يی

با سبب‌ها از مُسبِّب غافلی
سویِ این روپوش‌ها ز آن مایلی

چون سبب‌ها رفت، بَر سَر می‌زنی
ربَّنا و ربَّناها می‌کُنی

ربّ می‌گوید: برو سویِ سبب
چون ز صُنعم یاد کردی؟ ای عجب

گفت: زین پس من تو را بینم همه
ننگرم سویِ سبب و آن دَمدَمه

گویدش: رُدُّوا لَعادُوا، کارِ توست
ای تو اندر توبه و میثاق، سُست

چفسیده‌‌يی: چسبیده‌ای
صُنع: آفرینش، آفریدن، عمل، کار، نیکی کردن، احسان
دَمدَمه: شهرت، آوازه، مکر و فریب
رُدُّوا لَعادُوا: اگر آنان به این جهان برگردانده شوند، دوبار به آنچه که از آن نهی شده‌اند، باز گردند.
....

.قرآن كريم، سورهٔ انعام (۶)، آيهٔ ٢٨
[.poem]
....
« بَلْ بَدَا لَهُمْ مَا كَانُوا يُخْفُونَ مِنْ قَبْلُ ۖ وَلَوْ رُدُّوا لَعَادُوا لِمَا نُهُوا عَنْهُ وَإِنَّهُمْ لَكَاذِبُونَ. »

« بلکه آنچه را که زین پیش پوشیده می‌داشتند بر آنان آشکار شود، و اگر آنان بدین جهان باز آورده شوند،
دوباره بدانچه از آن نهی شده اند بازگردند. و البته ایشان‌اند دروغ زنان. »

لیک من آن ننگرم، رحمت کنم
رحمتم پُرّست، بر رحمت تنم

ننگرم عهدِ بَدت، بِدْهم عطا
از کرم، این دَم چو می‌خوانی مرا
....

== رحمت ها به صورت بی مرادی میان

audio::/media/audio/982/rahmat_ha_be_soorate_bi_moradi_miyan.mp3[controls]

.برنامه ۹۸۲، مولوی، مثنوی، دفتر پنجم، بیت ۳۶۴۴
[.poem]
....
هست مهمان‌خانه این تَن ای جوان
هر صباحی ضَیفِ نو آید دوان

هین مگو کین مانند اندر گردنم
که هم‌اکنون باز پَرَّد در عَدم

هرچه آید از جهان غَیب‌وَش
در دلت ضَیف است، او را دار خَوش

ضَیف: مهمان
....

.مولوی، مثنوی، دفتر ششم، بیت ١۶۴٣
[.poem]
....
لیک حاضر باش در خود، ای فتیٰ
تا به خانه او بیابد مر تو را

ورنه خِلْعَت را بَرَد او بازپس
که نیابیدم به خانه‌ هیچ‌کس

فَتیٰ: جوان‌مرد، جوان
خِلْعَت: لباس یا پارچه‌ای که خانوادهٔ داماد به عروس یا خانوادهٔ او هدیه می‌دهند، مجازاً هدیه
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۷۳۴
[.poem]
....
چونکه قَبضی آیدت ای راه‌رو
آن صَلاحِ توست، آتَش‌دل مشو

قَبض: گرفتگی، دلتنگی و رنج
آتش‌دل: دلسوخته، ناراحت و پریشان حال
....

.مولوی، مثنوی، دفتر سوم، بیت ۳۶۲
[.poem]
....
قبض دیدی چارهٔ آن قبض کن
زآنکه سَرها جمله می‌رویَد زِ بُن

بسط دیدی، بسطِ خود را آب دِه
چون برآید میوه، با اصحاب دِه
....

.مولوی، مثنوی، دفتر اوّل، بیت ٢۶٧٠
[.poem]
....
حکمِ حق گُسترد بهر ما بِساط
که بگویید از طریقِ اِنبساط

بِساط: هر چیز گستردنی مانند فرش و سفره
....
