= برنامه ۹۹۷
:toc:
:toc-title!:
:nofooter:

== خروب

audio::/media/audio/997/kharoob.mp3[controls]

.برنامه ۹۹۷، مولوی، مثنوی، دفتر چهارم، بیت ۱۳۸۳
[.poem]
....
مسجدست آن دل، که جسمش ساجدست
یارِ بَد خَرُّوبِ هر جا مسجدست

یارِ بَد چون رُست در تو مِهرِ او
هین ازو بگریز و کم کن گفت‌وگو

برکَن از بیخش، که گر سَر برزند
مر تو را و مسجدت را برکَنَد

عاشقا، خَرّوبِ تو آمد کژی
همچو طفلان، سویِ کژ چون می‌غژی؟

خَرُّوب: گیاه خَرنُوب که بوته‌ای بیابانی و مرتفع و خاردار است و در هر بنایی بروید آن را ویران می‌کند.
می‌غژی: فعل مضارع از غژیدن، به معنی خزیدن بر شکم مانند حرکت خزندگان و اطفال.
....

.مولوی، مثنوی، دفتر چهارم، بیت ۱۳۷۷
[.poem]
....
گفت: اندر تو چه خاصیّت بُوَد؟
گفت: من رُستَم، مکان ویران شود

رُستَن: روییدن
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۸۵
[.poem]
....
چون چنین وسواس دیدی، زود زود
با خدا گَرد و، درآ اندر سجود
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۸۷
[.poem]
....
آن زمان کِت امتحان مطلوب شد
مسجدِ دینِ تو، پُر خَرُّوب شد
....

.مولوی، مثنوی، دفتر پنجم، بیت ۵۵۰
[.poem]
....
چون زِ زنده مُرده بیرون می‌کُنَد
نَفْسِ زنده سویِ مرگی می‌تَنَد
....

== آینده لازم نیست امتداد گذشته باشه

audio::/media/audio/997/ayande_lazem_nist_emtedad_gozashte_bashe.mp3[controls]

.برنامه ۹۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۱۶۱۱
[.poem]
....
ز درم راه نباشد، ز سرِ بام و دریچه
سَتَرَ اللهُ عَلَیْنٰا چه عَلالایِ تو دارم

سَتَرَ اللهُ عَلَیْنٰا: خداوند بر ما پوشانید
عَلالا: بانگ و فریاد، هیاهو، سروصدا
....

.مولوی، دیوان شمس، غزل شمارهٔ ۵۸۲
[.poem]
....
خُنُک جانی که بر بامَش همی چوبَک زَنَد امشب
شود همچون سَحَر خندان، عَطایِ بی ‌عدد بیند

چوبَک زدن: پاسبانی کردن، نگهبانی کردن
....

.مولوی، دیوان شمس، غزل شمارهٔ ۷۷۱
[.poem]
....
دل تو مثالِ بام است و، حواسْ ناودان‌ها
تو ز بام آب می‌خور که چو ناودان نماند

جامِ مُباح آمد، هین نوش کُن
بازرَه از غابر و از ماجَرا

مُباح: حلال، جامِ مُباح: شرابِ حلال
غابر: گذشته

خفته از احوال دنیا روز و شب
چون قلم در پنجه تقلیب رب

تقلیب: برگردانیدن، واژگونه کردن

ای عاشق جریده، بر عاشقان گزیده
بگذر ز آفریده، بنگر در آفریدن

جریده: یگانه، تنها

هر لحظه و هر ساعت یک شیؤە نو آرد
شیرینتر و نادرتر زآن شیؤە پیشینش

بر گذشته حسرت آوردن خطاست
باز نآید رفته، یاِد آن هباست

هبا: مخفف هباء به معنی گرد و غبار پراکنده. در اینجا به معنی بیهوده است
....

== شکر کافیه

audio::/media/audio/997/shokr_kafie.mp3[controls]

.برنامه ۹۹۷، مولوی، دیوان شمس، غزل شمارهٔ ۲۵۷
[.poem]
....
صورتِ اقبالِ شکَرریز گفت:
شُکر چو کم نیست، شکایت چرا؟

اقبال: بخت، كنايه از تجلّی خداوند

بادْ تُند است و چراغم اَبْتری
زو بگیرانم چراغِ دیگری

اَبْتَر: ناقص و به دردنخور

لذّتِ بی‌کرانه‌ای‌ست، عشق شده‌ست نام او
قاعده خود شکایت است، ورنه جفا چرا بُوَد؟
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۵۱۷
[.poem]
....
کافیَم، بدْهم تو را من جمله خیر
بی‌سبب، بی‌واسطهٔ یاریِ غیر

کافیَم بی‌نان تو را سیری دهم
بی‌سپاه و لشکرت میری دهم

بی‌بهارت نرگس و نسرین دهم
بی‌کتاب و اوستا تلقین دهم

کافیَم بی‌داروَت درمان کنم
گور را و چاه را میدان کنم
....

== هر گونه غم در جهان بیجاست و توهم ذهنه

audio::/media/audio/997/har_goone_gham_dar_jahan_bijast_va_tohame_zehne.mp3[controls]

.برنامه ۹۹۷، مولوی، مثنوی، دفتر پنجم، بیت ۱۴۶۳
[.poem]
....
مشتریِّ ماست اللهُ‌اشْتَریٰ
از غمِ هر مشتری هین برتر آ

کسی که فرموده است: خداوند می‌خرد، مشتری ماست.
به هوش باش، از غم مشتریانِ فاقد اعتبار بالاتر بیا.
....
