= برنامه ۱۸۴
:toc:
:toc-title!:
:nofooter:

== هشیاری ناظر، نماینده زندگی، اصل ما، کل، میدونه چه کار باید بکنه، ما رو راهنمایی میکنه، زندگی ما رو هدایت میکنه

=== لا مکان

audio::/media/audio/184/la_makan.mp3[controls]

.مولوی، دیوان شمس، شماره ۸۴۵
[.poem]
....
مرغی که ناگهانی در دام ما درآمد
بشکست دام‌ها را بر لامکان برآمد
....

=== لا کردن

audio::/media/audio/184/la_kardan.mp3[controls]

.مولوی، دیوان شمس، شماره ۸۴۵
[.poem]
....
از باده گزافی شد صاف صاف صافی
وز درد هر دو عالم جوشید و بر سر آمد
....

.مولوی، دیوان شمس، شماره ۸۳۱
[.poem]
....
لا شویم از کل شیی هالک
چون هلاک و آفت اندر شیء رسد

هر کی او ناچیز شد او چیز شد
هر کی مرد از کبر او در حی رسد
....

=== لا اله الا الله

audio::/media/audio/184/la_elah_ella_allah.mp3[controls]

.مولوی، دیوان شمس، شماره ۸۴۵
[.poem]
....
جان را چو شست از گل معراج برشد آن دل
آن جا چو کرد منزل آن جاش خوشتر آمد
....

.مثنوی معنوی، دفتر اول، بخش ۱۴۳
[.poem]
....
کل شیء هالک جز وجه او
چون نه‌ای در وجه او هستی مجو

هر که اندر وجه ما باشد فنا
کل شیء هالک نبود جزا

زانک در الاست او از لا گذشت
هر که در الاست او فانی نگشت

هر که بر در او من و ما می‌زند
رد بابست او و بر لا می‌تند
....

.سنایی
[.poem]
....
تا به جاروب لا نروبی راه
نرسی در سرای الّا الله
....

=== الله اکبر

audio::/media/audio/184/allaho_akbar.mp3[controls]

.مولوی، دیوان شمس، شماره ۸۴۵
[.poem]
....
در عالم طراوت او یافت بس حلاوت
وز وصف لاله رویان رویش مزعفر آمد

زان ماه هر که ماند وین نقش را نخواند
در نقش دین بماند والله که کافر آمد

ز اوصاف خود گذشتم وز خود برهنه گشتم
زیرا برهنگان را خورشید زیور آمد

الله اکبر تو خوش نیست با سر تو
این سر چو گشت قربان الله اکبر آمد

هر جان باملالت دورست از این جلالت
چون عشق با ملولی کشتی و لنگر آمد

ای شمس حق تبریز دل پیش آفتابت
در کم زنی مطلق از ذره کمتر آمد
....

=== محدودیت این لحظه رو چنان میپذیریم درست مثل اینکه خودمون انتخاب کردیم

audio::/media/audio/184/mahdoodiyate_in_lahze_ro_chenan_mipazirim_dorost_mesle_inke_khodemoon_entekhab_kardim.mp3[controls]
