= برنامه ۵۰۰
:toc:
:toc-title!:
:nofooter:

== هر چه شهوانیست بندد چشم و گوش

audio::/media/audio/500/har_che_shahvanist_bandad_cheshm_va_goosh.mp3[controls]

.مولوی، مثنوی، دفتر چهارم، بیت ۳۶۱۱
[.poem]
....
که تو آن هوشی و باقی هوش‌پوش
خویشتن را گم مکن یاوه مکوش

دانک هر شهوت چو خَمرست و چو بَنگ
پردهٔ هوشست وعاقل زوست دَنگ

خمر تنها نیست سرمستی هوش
هر چه شهوانیست بندد چشم و گوش
....

.مولوی، دیوان شمس، غزل شماره ۱۶۷۰
[.poem]
....
ما به خرمنگاه جان بازآمدیم
جانب شه همچو شهباز آمدیم

سیر گشتیم از غریبی و فراق
سوی اصل و سوی آغاز آمدیم

وارهیدیم از گدایی و نیاز
پای کوبان جانب ناز آمدیم
....

== گزیده اشعار

.مولوی، دیوان شمس، غزل شماره ۱۴۷۳
[.poem]
....
بیایید بیایید به گلزار بگردیم
بر این نقطه اقبال چو پرگار بگردیم
....

.مولوی، دیوان شمس، غزل شماره ۶۰۹
[.poem]
....
بر هر چه همی‌لرزی می‌دان که همان ارزی
زین روی دل عاشق از عرش فزون باشد
....

.مولوی، مثنوی، دفتر دوم، بیت ۳۱۰۶
[.poem]
....
دوزخ و جنت همه اجزای اوست
هرچه اندیشی تو او بالای اوست
....

[.poem]
....
دیده ای خواهم که باشد شه شناس
تا شناسد شاه را در هر لباس
منسوب به مولانا

مرد می‌باید که باشد شه شناس
گر ببیند شاه را در صد لباس
عطار، منطق الطیر
....
