= برنامه ۷۹۷
:toc:
:toc-title!:
:nofooter:

== آینه کلی

audio::/media/audio/797/ayene_kolli.mp3[controls]

.مولوی، دیوان شمس، غزل شمارهٔ ۱۷۴۵
[.poem]
....
فضول گشته‌ام امروز، جنگ می جویم
منوش نکته مستان که یاوه می گویم

منوش: مشنو (از مصدر نیوشیدن)
یاوه: مجازاً سخن بیهوده و بی معنی، شوخی بی مزه

آینهٔ جان نیست اِلّا رویِ یار
رویِ آن یاری که باشد زآن دیار

گفتم: ای دل آینهٔ کُلّی بجو
رَوْ به دریا، کار بر ناید به جُو

آینهٔ کُلّی: در اینجا اشاره به انسانهای رشد یافته و به کمال رسیده می باشد.

زین طلب بنده به کویِ تو رسید
دردْ، مریم را به خُرمابُن کَشید

خُرمابُن: درخت خرما، نخل

از خدا غير خدا را خواستن
ظن افزوني است و كلي كاستن
....

.قرآن کریم، سوره مريم (۱۹)، آیه ۲۳
[.poem]
....
« فَأَجَاءَهَا الْمَخَاضُ إِلَىٰ جِذْعِ النَّخْلَةِ قَالَتْ يَا لَيْتَنِي مِتُّ قَبْلَ هَٰذَا وَكُنْتُ نَسْيًا مَنْسِيًّا »

« درد زاييدن او را به سوى تنه درخت خرمايى كشانيد. گفت: اى كاش پيش از اين مرده بودم و از يادها فراموش شده بودم. »
....

[.poem]
....
دیدهٔ تو چون دلم را دیده شد
شد دلِ نادیده، غرقِ دیده شد

آینهٔ کُلّی تو را دیدم اَبَد
دیدم اندر چشمِ تو، من نقشِ خَود

گفتم: آخر خویش را من یافتم
در دو چشمش، راهِ روشن یافتم

گفت وَهمَم: کان خیالِ توست هان
ذاتِ خود را از خیالِ خود بدان

وَهمَ: خیال، پندار، آن قسمت از مغز که تخیّل می کند.

نقش من از چشم تو آواز داد
که منم تو، تو منی در اتحاد
....

== افسانه من ذهنی

audio::/media/audio/797/afsane_man_zehni.mp3[controls]

موانع مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی، که به نظر
من نمی گذارند، من در این لحظه زندگی کنم و اگر آن موانع رفع شوند، زندگی
من شروع می شود.

مسایل مَنِ ذهنی من: وضعیت های ساخته شده به وسیله من ذهنی که خودشان
را به من به صورت گره ذهنی یا مساله ارائه می کنند و من نمی خواهم یا اصلاً
نمی توانم برای حل آنها کاری کنم.

دشمنان مَنِ ذهنی من: اشخاص و یا وضعیت های ساخته شده به وسیله من ذهنی،
که به نظر من فعالانه در پایین آوردن کیفیت زندگی من یا محروم کردن من از زندگی
می کوشند. من ذهنی برای بقا، از آنها به صورت قطب استفاده می کند و انرژی
مخرب ایجاد میکند.

.مولوی، دیوان شمس، غزل شماره ۱۳۴۴
[.poem]
....
دمِ او جان دهدت رو ز نَفَخْتُ بپذیر
کارِ او کُنْ فَیَکُون ‌ست، نه موقوفِ علل

نَفَخْتُ: دمیدم
....

== یابی اندر دید او کل غرض

audio::/media/audio/797/yabi_andar_dide_oo_kolle_gharaz.mp3[controls]

.مولوی، مثنوی، دفتر اول، بیت ۹۲۱
[.poem]
....
دیده ما چون بسی علّت دروست
رو فنا کُن دید خود در دید دوست

دید ما را دید او نِعْمَ الْعِوَض
یابی اندر دید او کل غَرَض
....

== شما مسئول مداومت تعهدتون هستید

audio::/media/audio/797/shoma_masoule_modavemate_taahodetoon_hastid.mp3[controls]

.مولوی، مثنوی، دفتر پنجم، بیت ۱۲۱۱
[.poem]
....
شرع بهرِ دفعِ شَرّ رایی زند
دیو را در شیشهٔ حجّت کند
....

== از میان نردبان نگریختم

audio::/media/audio/797/az_mian_nardeban_nagrikhtam.mp3[controls]

.مولوی، دیوان شمس، غزل شمارهٔ ۱۶۵۸
[.poem]
....
عاشقم، از عاشقان نگریختم
وز مَصاف ای پهلوان، نگریختم

حمله بردم سوی شیران همچو شیر
همچو روبه از میان نگریختم

قصدِ بامِ آسمان می داشتم
از میانِ نردبان نگریختم

چونکه من دارو بدم هر درد را
از صُداعِ این و آن نگریختم

هیچ دیدی دارو کز دردی گریخت؟
داروَم من، همچنان نگریختم

پیروِ پیغامبران بودم به جان
من ز تهدیدِ خَسان نگریختم

زنده کوشم در شکارِ زندگی
زنده باشم، چون ز جان نگریختم

چشمِ تیراندازش آنگه یافتم
که ز تیرِ خَرکمان نگریختم

زخمِ تیغ و تیرِ من منصور شد
چون که از زخمِ سِنان نگریختم

بحرِ قندم، از تُرُش باکیم نیست
سودمندم، از زیان نگریختم

شمسِ تبریزی چو آمد آشکار
ز آشکارا و نهان نگریختم
....

== یک لحظه نیست که خدا نخواد به ما کمک کنه

audio::/media/audio/797/yek_lahze_nist_ke_khoda_nakhad_be_ma_komak_kone.mp3[controls]

.مولوی، دیوان شمس، غزل شمارهٔ ۱۷۴۵
[.poem]
....
لگن نهاد خیالش به چشمهء چشمم
بهانه کرد کز این آب جامه می شویم

بگفتمش که: به خونابه جامه چون شویی؟
بگفت: خون همه زان سوست و من از این سویم

به سویِ تو همه خون است و سویِ من همه آب
نه قبطیم، که در این نیل موسوی خویم
....

.مولوی، مثنوی، دفتر اول، بخش ۷۶
[.poem]
....
حق قدم بر وی نهد از لامکان
آنگه او ساکن شود از کُنْ فَکان
....

.مولوی، مثنوی، دفتر اول، سطر شماره ۲۴۶۶
[.poem]
....
پیش چوگانهای حکم کن فکان
می‌دویم اندر مکان و لامکان
....

== آدمى را در رنج و محنت بيافريده‌ايم

audio::/media/audio/797/adami_ra_dar_ranj_o_mehnat_biafaride_im.mp3[controls]

.قرآن کریم، سوره بلد(۹۰)، آیه ۱۲-۱
[.poem]
....
لَا أُقْسِمُ بِهَٰذَا الْبَلَدِ
قسم به اين شهر.

وَأَنْتَ حِلٌّ بِهَٰذَا الْبَلَدِ
و تو در اين شهر سكنا گرفته‌اى.

وَوَالِدٍ وَمَا وَلَدَ
و قسم به پدر و فرزندانى كه پديد آورد.

لَقَدْ خَلَقْنَا الْإِنْسَانَ فِي كَبَدٍ
كه آدمى را در رنج و محنت بيافريده‌ايم.

أَيَحْسَبُ أَنْ لَنْ يَقْدِرَ عَلَيْهِ أَحَدٌ
آيا مى‌پندارد كه كس بر او چيره نگردد؟

يَقُولُ أَهْلَكْتُ مَالًا لُبَدًا
مى‌گويد: مالى فراوان را تباه كردم.

أَيَحْسَبُ أَنْ لَمْ يَرَهُ أَحَدٌ
آيا مى‌پندارد كه كسى او را نديده است؟

أَلَمْ نَجْعَلْ لَهُ عَيْنَيْنِ
آيا براى او دو چشم نيافريده‌ايم؟

وَلِسَانًا وَشَفَتَيْنِ
و يك زبان و دو لب؟

وَهَدَيْنَاهُ النَّجْدَيْنِ
و دو راه پيش پايش ننهاديم؟

فَلَا اقْتَحَمَ الْعَقَبَةَ
و او در آن گذرگاه سخت قدم ننهاد.

وَمَا أَدْرَاكَ مَا الْعَقَبَةُ
و تو چه دانى كه گذرگاه سخت چيست؟
....

== بر صدف آید ضرر نی بر گوهر

audio::/media/audio/797/bar_sadaf_ayad_zarar_ney_bar_gohar.mp3[controls]

.مولوی، مثنوی، دفتر اول، بیت ۳۴۹۶
[.poem]
....
کس نیابد بر دلِ ایشان ظَفَر
بر صدف آید ضرر، نَی بر گُهَر
....

== چون نباشد قوتی پرهیز به

audio::/media/audio/797/chon_nabashad_ghovati_parhiz_beh.mp3[controls]

.مولوی، مثنوی، دفتر ششم، بیت ۴۹۶
[.poem]
....
چون نباشد قوّتی، پرهیز بِهْ
در فرارِ لایُطاق آسان بِجِه
....

== تا نمیری نیست جان کندن تمام

audio::/media/audio/797/ta_namiri_nist_jan_kandan_tamam.mp3[controls]

.مولوی، مثنوی، دفتر ششم، بیت ۷۲۴
[.poem]
....
تا نمیری، نیست جان کندن تمام
بی‌کمالِ نردبان نآیی به بام
....

== نعمت آرد غفلت و شکر انتباه

audio::/media/audio/797/nemat_arad_ghaflat_va_shokr_entebah.mp3[controls]

.مولوی، مثنوی، دفتر سوم، بیت ۲۸۹۷
[.poem]
....
نعمت آرد غفلت و، شُکر انتباه
صیدِ نعمت کن به دامِ شُکرِ شاه
....

== مرغ غافل می خورد دانه ز دام

audio::/media/audio/797/morghe_ghafel_mikhorad_dane_ze_daam.mp3[controls]

.مولوی، مثنوی، دفتر پنجم، بیت ۱۴۱۲
[.poem]
....
مرغِ غافل می‌خورد دانه ز دام
همچو اندر دامِ دنیا، این عوام
....

== دانه کمتر خور مکن چندین رفو

audio::/media/audio/797/dane_kamtar_khor_makon_chandin_rofoo.mp3[controls]

.مولوی، مثنوی، دفتر پنجم، بیت ۱۴۰۷
[.poem]
....
دانه کمتر خور، مکن چندین رفو
چون کُلُوا خواندی، بخوان لٰاتُسْرِفُوا
....

== صبر و خاموشی جذوب رحمت است

audio::/media/audio/797/sabr_va_khamooshi_jazoobe_rahmat_ast.mp3[controls]

.مولوی، مثنوی، دفتر سوم، بیت ۲۷۲۵
[.poem]
....
صبر و خاموشی جَذوبِ رحمت است
وین نشان جُستن، نشانِ علّت است
....

== اگر تو عاشقی غم را رها کن

audio::/media/audio/797/agar_to_asheghi_gham_ra_raha_kon.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۱۹۰۵
[.poem]
....
اگر تو عاشقی غم را رها کن
عروسی بین و ماتم را رها کن
....

== هست با هر خوب یک لالای زشت

audio::/media/audio/797/hast_ba_har_khoob_yek_lalaye_zesht.mp3[controls]

.مولوی، مثنوی، دفتر دوم، بیت ۳۱۴۷
[.poem]
....
صبر چون پولِ صِراط آن سو، بهشت
هست با هر خوب، یک لالایِ زشت
....

== ره آسمان درون است پر عشق را بجنان

audio::/media/audio/797/rahe_aseman_daroon_ast_pare_eshgh_ra_bejonban.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۷۷۱
[.poem]
....
ره آسمان درونست پر عشق را بجنبان
پر عشق چون قوی شد غم نردبان نماند
....

== هیچ طبیبی ندهد بی مرضی حب و دوا

audio::/media/audio/797/hich_tabibi_nadahad_bi_marazi_hobb_va_dava.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۱۴۰۰
[.poem]
....
هیچ طبیبی ندهد بی مرضی حب و دوا
من همگی درد شوم تا که به درمان برسم
....

== مباش در قفسی و کناره بامی

audio::/media/audio/797/mabash_dar_ghafasi_va_kenare_bami.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۳۰۵۸
[.poem]
....
به باغ بلبلِ مستم، صَفیرِ من بشنو
مباش در قفسی و کناره بامی
....

== احتما کن احتما ز اندیشه ها

audio::/media/audio/797/ehtema_kon_ehtema_ze_andishe_ha.mp3[controls]

.مولوی، مثنوی، دفتر اول، بیت ۲۹۰۹
[.poem]
....
اِحْتِما کن، اِحْتِما ز اندیشه‌ها
فکر، شیر و گور و، دلها بیشه‌ها
....

== هر چیز که در جستن آنی، آنی

audio::/media/audio/797/har_chiz_ke_dar_jostane_ani_ani.mp3[controls]

.مولوی، دیوان شمس، رباعی شمارهٔ ۱۸۱۵
[.poem]
....
این نکتهٔ رمز اگر بدانی دانی
هر چیز که در جستن آنی آنی
....

== کار مرا چو او کند کار دگر چرا کنم؟

audio::/media/audio/797/kare_mara_cho_oo_konad_kare_degar_chera_konam.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۱۴۰۴
[.poem]
....
کار مرا چو او کند کار دگر چرا کنم
چونک چشیدم از لبش یاد شکر چرا کنم
....

== کار او کن فیکون است نه موقوف علل

audio::/media/audio/797/kare_oo_kon_fa_yakoon_ast_na_moghoofe_elal.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۱۳۴۴
[.poem]
....
دمِ او جان دهدت رو ز نَفَخْتُ بپذیر
کارِ او کُنْ فَیَکُون ست، نه موقوفِ علل
....

== جمله خشم از کبر خیزد واز تکبر پاک شو

audio::/media/audio/797/jomle_khashm_az_kebr_khizad_va_az_takabbor_pak_sho.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۲۱۹۸
[.poem]
....
جمله خشم از کبر خیزد از تکبر پاک شو
گر نخواهی کبر را رو بی تکبر خاک شو
....

== هر چند مفلسم نپذیرم عقیق خرد

audio::/media/audio/797/har_chand_moflesam_napaziram_aghighe_khord.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۴۴۱
[.poem]
....
هر چند مُفلِسم، نپذیرم عَقیقِ خُرد
کانِ عَقیقِ نادرِ ارزانم آرزوست
....

== باغ که بی تو سبز شد دی بدهد سزای او

audio::/media/audio/797/bagh_ke_bi_to_sabz_shod_dey_bedahad_sezaye_oo.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۱۸۳۳
[.poem]
....
باغ که بی تو سبز شد دی بدهد سزای او
جان که جز از تو زنده شد نیست وی از شمار جان
....

== رحمت حق آب بود، جز که به پستی نرود

audio::/media/audio/797/rahmate_hagh_ab_bood_joz_ke_be_pasti_naravad.mp3[controls]

.مولوی، دیوان شمس، غزل شماره ۱۴۰۰
[.poem]
....
رحمت حق آب بود جز که به پستی نرود
خاکی و مرحوم شوم تا بر رحمان برسم
....

== این جهان دامست و دانه‌ ش آرزو

audio::/media/audio/797/in_jahan_daam_ast_va_dane_ash_arezoo.mp3[controls]

.مولوی، مثنوی، دفتر ششم، بیت ۳۷۸
[.poem]
....
این جهان دامست و دانه‌ش آرزو
در گریز از دام‌ها، روی آر، زُو
....
