= برنامه ۸۷۳
:toc:
:toc-title!:
:nofooter:

== یفعل الله ما یشاء

audio::/media/audio/873/yafalo_allaho_ma_yasha.mp3[controls]

.مولوی، مثنوی، دفتر دوم، بیت ۱۶۱۹
[.poem]
....
حاکم است و یَفْعَلُ الله مایَشا
او ز عینِ دَرد انگیزد دوا
....

.قرآن کریم، سوره آل عمران(۳)، آیه ۴۰
[.poem]
....
قَالَ رَبِّ أَنَّىٰ يَكُونُ لِي غُلَامٌ وَقَدْ بَلَغَنِيَ الْكِبَرُ وَامْرَأَتِي عَاقِرٌ ۖ قَالَ كَذَٰلِكَ اللَّهُ يَفْعَلُ مَا يَشَاءُ.

گفت: اى پروردگار من، چگونه مرا پسرى باشد، در حالى كه به پيرى رسيده‌ام و زنم نازاست؟ گفت: بدان سان كه خدا هر چه بخواهد مى كند.
....

.قرآن کریم، سوره ابراهیم(۱۴)، آیه ۲۷
[.poem]
....
يُثَبِّتُ اللَّهُ الَّذِينَ آمَنُوا بِالْقَوْلِ الثَّابِتِ فِي الْحَيَاةِ الدُّنْيَا وَفِي الْآخِرَةِ ۖ وَيُضِلُّ اللَّهُ الظَّالِمِينَ ۚ وَيَفْعَلُ اللَّهُ مَا يَشَاءُ

خدا مؤمنان را به سبب اعتقاد استوارشان در دنيا و آخرت پايدار مى‌دارد. و ظالمان را گمراه مى‌سازد و هر چه خواهد همان مى‌كند.
....

.قرآن کریم، سوره حج(۲۲)، آیه ۱۸
[.poem]
....
أَلَمْ تَرَ أَنَّ اللَّهَ يَسْجُدُ لَهُ مَنْ فِي السَّمَاوَاتِ وَمَنْ فِي الْأَرْضِ وَالشَّمْسُ وَالْقَمَرُ وَالنُّجُومُ وَالْجِبَالُ وَالشَّجَرُ وَالدَّوَابُّ وَكَثِيرٌ مِنَ النَّاسِ ۖ وَكَثِيرٌ حَقَّ عَلَيْهِ الْعَذَابُ ۗ وَمَنْ يُهِنِ اللَّهُ فَمَا لَهُ مِنْ مُكْرِمٍ ۚ إِنَّ اللَّهَ يَفْعَلُ مَا يَشَاءُ

آيا نديده‌اى كه هر كس در آسمانها و هر كس كه در زمين است و آفتاب و ماه و ستارگان و كوهها و درختان و جنبندگان و بسيارى از مردم خدا را سجده مى‌كنند؟ و بر بسيارى عذاب محقق شده و هر كه را خدا خوار سازد، هيچ كس گراميش نمى‌دارد. زيرا خدا هر چه بخواهد همان مى‌كند.
....

.مولوی، مثنوی، دفتر دوم، بیت ۱۶۲۵
[.poem]
....
چار طبع و علّتِ اُولی نیَم
در تصرّف دایماً من باقیَم

کارِ من بی علّت است و مستقیم
هست تقدیرم نه علّت، ای سَقیم

عادتِ خود را بگردانم به وقت
این غبار از پیش، بنشانم به وقت
....

.مولوی، مثنوی، دفتر ششم، بیت ۲۷۵۹
[.poem]
....
این عجب نَبْوَد که کور افتد به چاه
بُوالْعَجَب افتادنِ بینایِ راه

این قضا را گونه گون تصریفهاست
چشمْ‌بندش یَفْعَلُ‌الله مایَشاست

تصریف: تغییر
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۸
[.poem]
....
گفتم که « ز آتشهایِ دل، بر روی مَفرَشهای دل
می غَلْت در سودایِ دل تا بحرِ یَفْعَل ما یَشا»؟
....

.مولوی، دیوان شمس، غزل شمارهٔ ۲۸
[.poem]
....
زین رنگ ها مُفْرَد شود، در خُنبِ عیسی در رَوَد
در «صِبْغَةَ الله» رُو نهد تا «یَفْعَلُ اللَه مایَشا»

خنب عیسی: یکی از معجزات عیسی(ع) که اگر جامه صد رنگ را
در خم می انداختند، سفید و سیاه بر می آمد.
....

.قرآن کریم، سوره بقره(۲)، آیه ۱۳۸
[.poem]
....
صِبْغَةَ اللَّهِ ۖ وَمَنْ أَحْسَنُ مِنَ اللَّهِ صِبْغَةً ۖ وَنَحْنُ لَهُ عَابِدُونَ

رنگ خدا [را بگیرید و به رنگ خدایی درآیید.] و چه کسی نکو رنگتر از خداوند است؟! [ مسلماً هیچکس ] و ماییم پرستندگان او
....
