= برنامه ۸۷۳
:!toc:
:nofooter:

.مولوی، دیوان شمس، غزل شمارهٔ ۳۹
[.poem]
....
آه که آن صدرِ سرا، می‌ندهد بار، مرا
می‌نکند مَحرمِ جان، مَحرمِ اسرار، مرا

صدرِ سرا: سَرور و خواجهٔ خانه
بار: اجازه ورود و درآمدن پیش کسی
....

.مولوی، دیوان شمس، غزل شمارهٔ ۳۰۱۳
[.poem]
....
یار در آخر زمان کرد طَرب سازیی
باطن او ِجدِّ ِجد، ظاهر او بازیی
....

خداوند از طریق ما و خودش میخواد شادی کنه. منظور از زمان، زمان روانشناختی (گذشته و
آینده) است. آخر زمان، پایان زمان روانشناختی هست که انسان از گذشته و آینده جمع میشه
و در این لحظه ابدی حاضر میشه. این خیزش از درون ما صورت میگیره. آخر زمان در واقع ظهور
خداوند است از درون ما به صورت ما که میخواد شادی کنه (کرد طرب سازی).

باطن او که همون صدر سراست، جد جد هست. ظاهر او که همون اتفاق این لحظه هست بازیه. جدی
گرفتن اتفاق این لحظه منشا همه اشتباهات ماست. اتفاق این لحظه برای من ذهنی جدیه و صدر
سرا، باطن ما که خداوند هست شوخیه. ما هم مشابه خداوند باید به این صدر سرا، این باطن،
این فضای گشوده شده یا فضاگشایی توجه کنیم و اون رو جدی بگیریم.
اتفاق این لحظه هر چی هست بازیه. با پذیرش اتفاق این لحظه بدون قید و شرط، قبل از
قضاوت، فضا باز میشه. اون فضای گشوده شده باطن شماست، همون خداوند هست که جدیه. اما
اتفاق این لحظه که درون این فضاست، شوخیه، بازیه و شما هم به بازی می‌پردازید. با اهمیت
ندادن به اتفاق این لحظه شما اجازه میدید که خداوند از طریق شما شادی رو تجربه کنه.
این موضوع خیلی مهمه که اتفاق این لحظه که به وسیله ذهن دیده میشه، مرجع یا رفرانس فکر
و عمل شما واقع نشه. که بیشتر اوقات یا همیشه برای من‌های ذهنی اینطوریه. من ذهنی از
اتفاق این لحظه زندگی میخواد. اگه مطابق میلش نباشه، مقاومت می‌کنه. قربانی اتفاق میشه.
از جنس اتفاق میشه. نمیتونه فضا باز کنه. اتفاق براش بازی نیست. اگه شما بازی رو جدی
نگیرید، هر جور باشه خوشاینده. مثل بازی فوتبال. بازی همینطور که گشوده میشه عالیه.

پس اتفاق این لحظه رو قضا یعنی قضاوت خداوند تعیین می‌کنه و شما فضاگشایی می‌کنید، بازیه
برای شما. جدی نیست. بهترین استفاده از اتفاق این لحظه که برای بیدار شدن ما از خواب
ذهن اتفاق میافته در واقع این حالته. و همینطور اتفاق برکت پیدا می‌کنه از فضای گشوده شده.
اتفاق این لحظه کلیده به شرط اینکه شما فضا گشایی کنید.

.مولوی، دیوان شمس، غزل شمارهٔ ۳۰۱۳
[.poem]
....
جمله عشّاق را یار بدین علم کشت
تا نکند هان و هان، جهل تو طنّازیی
....

همه عاشقان رو خداوند با همین علم کشته. با این آگاهی کشته که اتفاق این لحظه بازیه و
فضاگشایی جدیه (و شما حواستون رو میدید به اون، نه به اتفاق).عاشقان مثل مولانا با
آگاهی به این موضوع و به کار بستن لحظه به لحظه اون، نسبت به من ذهنیشون مرده‌اند.

پس فرمول خیلی ساده هست. یک اینکه آخر زمانه، یعنی موقعی هست که شما باید در این لحظه ابدی
مستقر بشید. چه چیزی نمیذاره؟ هیاهوی بیهوده ذهن. فکرهایی که از این همانیدگی به اون
همانیدگی میپرن و در ما تولید میشن و دردهای حاصل از آن. گرد و خاکی که اونجا هست. اگر این
همهمه بخوابه که باید بخوابه (اگه اجازه بدین، زندگی میخوابونه)، شما طرب و شادی بی سبب
زندگی رو که او از طریق شما تجربه میکنه، تجربه میکنید و خواهید دید که چه چیزی جدیه،
چه چیزی بازیه.

اگه اتفاق این لحظه بازیه، شما اتفاق این لحظه رو عامل فکر کردن و عمل کردن نمیدونید.
همین کلید، زندگی شما رو عوض میکنه. شما لزومی نداره که زندگیتون مطابق اتفاقات که شما هم
هیچ کنترلی روشون ندارید رخ بده. این لحظه با فضاگشایی، ما میتونیم یه عادت رو تغییر بدیم.
یه جور دیگه عمل کنیم. ما معمولا چه جوری عمل می‌کنیم؟ ما معمولا مقاومت می‌کنیم به اتفاق
این لحظه و مثلا خشمگین میشیم یا دردی در ما به وجود میاد (یا دردهای کهنه بالا میان) و
اون درد انگیزه تصمیم ما میشه، انگیزه شناسایی ما میشه، انتخاب ما میشه، فکر و عمل ما
میشه. این درست نیست. انگیزه شما باید از فضای گشوده شده بیاد. از همین "او" بیاد. یعنی از
زندگی بیاد. او به شما میگه که چه فکری باید بکنید، چه عملی باید بکنید. چه چیزی رو باید
ادامه بدید. چه چیزی رو باید قطع بکنید. وگرنه وضعیت این لحظه اگه تعیین بکنه وضعیت
لحظه بعد رو، پس شما دایما قربانی اتفاقات و وضعیت‌ها هستین.

.مولوی، دیوان شمس، غزل شمارهٔ ۷۱
[.poem]
....
اگرنه عشق شمس الدین بدی در روز و شب ما را
فراغت ها کجا بودی ز دام و از سبب ما را؟!
....

در ما عشق شمس الدین یا عشق خداوند وجود داره یعنی ما میخواهیم به سوی خداوند بریم، به
سوی زندگی بریم چون از جنس او هستیم. پس این کشش ما به بیرون، این مصنوعیه. میگه اگر در
هر لحظه (روز و شب - البته درستش اینه که بگیم این لحظه چون فقط این لحظه ست که وجود
داره) عشق زندگی ما رو نمی‌کشید، اگه ما فضاگشایی نمی‌کردیم، آسایش از این دام من ذهنی،
از این سبب‌ ها کی ما داشتیم؟ آیا اتفاق این لحظه سبب هست برای شما؟ یا فضای گشوده شده
سببه؟ دام، همین من ذهنیست که ما همانیده شدیم. اون با سبب کار میکنه. سبب اتفاق این
لحظه ست برای اون. آیا شما به عنوان من ذهنی اتفاق این لحظه رو سبب می‌بینید و بر اساس
اون فکر و عمل می‌کنید؟ این یه راهه. یه راهه دیگه اینه که بگید اتفاق این لحظه سبب
نیست. حال من رو تعیین نمی‌کنه. و عاملی هم نیست که سبب بشه من تصمیم بگیرم و عمل بکنم.
بلکه فضا‌گشایی میکنم و این فضای گشوده شده هست که سببه. فضای گشوده شده خود زندگیست.
بنابراین شما الان تشخیض میدید که در یک دام هستید. این دام همانیدگیست و داشتید اتفاق
این لحظه رو سبب حساب می‌کردید. برای همین در برابرش مقاومت می‌کردید. برای همین زندگی
شما لحظه به لحظه داره به وسیله من ذهنی تعیین میشه و تغییر زیادی درش نیست. چرا؟ برای
اینکه همین بت من ذهنی یک تابش مخربی داره.

.مولوی، دیوان شمس، غزل شمارهٔ ۷۱
[.poem]
....
بتِ شهوت برآوردی، دمار از ما ز تابِ خود
اگر از تابش عشقش، نبودی تاب و تب، ما را
....

تابش من ذهنی مخربه. دمار از روزگار ما درمیاره و تنها چیزی که به ما کمک میکنه،
تابش عشق زندگیست که با فضاگشایی میاد و در این تابش دو تا چیز هست. یکی خود نوره که
روشن میکنه ما رو به صورت ناظر، ذهنمون رو ببینیم که با چی هم هویتیم و چه دردهایی
داریم. و یک تبی هم داره، گرمایی داره. یعنی وقتی فضاگشایی می‌کنید، گرمای لطف
خداونده، گرمای عشقه به‌علاوه قدرت شناساییش (تاب و تب). این تاب و تب جلوی تابش
مخرب من ذهنی رو می‌گیره و به ما آسایش میده از این حالت که من ذهنی ما رو مجبور
کرده تو دام بمونیم، برای اینکه اتفاق این لحظه رو سبب می‌بینیم. اتفاق سبب نیست که
من زندگیم رو براساس اون بسازم.

دو بیت درباره قانون جبران معنوی:

.مولوی، دیوان شمس، غزل شمارهٔ ۲۹۸۱
[.poem]
....
زان مزدِ کار می‌نرسد مر تو را که تو
پیوسته نیستی تو درین کار، گه گهی
....

.مولوی، دیوان شمس، غزل شمارهٔ ۲۴۶۵
[.poem]
....
ور دو سه روز چشم را بند کنی بِاتَّقوا
چشمه چشم حس را بحر در عیان کنی
....

اتقوا یعنی مواظب باش، پرهیز کن (از همانیدگی‌ها). نه از طریق همانیدگی ببین، نه از
طریق همانیدگی‌های جدید. وقتی می‌بینید توجه شما داره میرسه به سمت و سویی. به سمت
کسی یا چیزی. این خطرناکه. اتقوا یعنی توجه خودتون رو رو خودتون نگه دارید. اتقوا
یعنی مواظب باش اتفاق این لحظه رو جدی نگیری. بلکه فضاگشایی رو جدی بگیر. اگه
دیدی یه همانیدگی از بیرون اومد، شد مرکزت، جارو کن بریز دور.

در عیان یعنی عدم، خود زندگی. اگه قرار باشه زندگی از طریق ما زندگی رو تجربه
کنه که ما هم تجربه کنیم پس ما باید از جنس اون بشیم در این لحظه. پس ما در
این لحظه مواظبیم اتفاق این لحظه توجه ما رو ندزده. اتفاق این لحظه به صورت
یه آدم میاد، به صورت یه حرف میاد. به صورت یه فکری که از گذشته تو سر ما
می‌پریده میاد. هرچی که در ذهن ما می‌پره در این لحظه، ما پرهیز می‌کنیم از جدی
گرفتن یا مقابله کردن در مقابل آن. هر چی باشه، ما فضا رو باز میکنیم که
ببینیم این فضای گشوده شده، این دری که خرده، شادیه، عشقه، فر ایزدیه، این چی
میخواد به ما بده؟

.مولوی، مثنوی، دفتر دوم، بیت ۱۰۵۷
[.poem]
....
گر بِرویَد، ور بریزد صد گیاه
عاقبت بَررویَد آن کِشتهٔ اله

کِشتِ نو کارید بر کِشتِ نخست
این دوم فانی است و آن اوّل دُرُست

کِشتِ اوّل کامل و بُگزیده است
تخمِ ثانی فاسد و پوسیده است
....

ما قبل از ورود به این جهان، با خود زندگی در روز الست همانیده شده‌ایم و اون
کشت اول بوده. یعنی خداوند ما رو فرستاده در اینجا به خودش زنده بشیم و این
کشت‌های بعدی که به صورت همانیدگی اومده، اینا ظاهره، اینا بازیه ولی به اشتباه
جدی گرفته‌ایم. اینا هی رشد میکنن، میریزن، هی رشد میکنن، میریزن تا ما بفهمیم
اونی که رشد میکنه و نمیریزه کدومه.

هر چیزی که ما براساس منیت میسازیم. با یه چیزی همانیده هستیم مثل بدنمون، مثل
دانشمون، مثل شرکتمون، کارمون، نقشمون به صورت پدر، مادر. اینا کشت دومن. ما
یه موقع پدر میشیم، مادر میشیم، بعد بچه هامون بزرگ میشن میرن، اون نقش میریزه.
میگه اینا مهم نیستن، خواهند ریخت. عاقبت باید همون "کشت اله" که همون خودشه در
ما رشد کنه. پس شما کمک کنید خودش رشد کنه. همکاری کنید، اون داره این کشت‌های
ثانویه رو افسرده میکنه، پژمرده میکنه میذاره کنار. شما اینا رو نذارید
رو کشت اول رو بپوشونه. فضاگشایی پس یعنی کشت اول. فضابندی، بلند شدن به عنوان
من ذهنی، یعنی کشت دوم.

.مولوی، مثنوی، دفتر اوّل، بیت ۲۶۷۰
[.poem]
....
حکمِ حق گُسترد بهر ما بِساط
که بگویید از طریقِ اِنبساط
....

حکم حق (اتفاق این لحظه) برای اینه که ما فضا‌گشایی کنیم. شما فضابندی می‌کنید،
واکنش نشون میدید، خشمگین میشید، ناراحت میشید، میرنجید. اینها انبساط نیست. اگر منبسط نمیشید
لحظه به لحظه دارید حکم خدا رو زیر پا میذارید. انتظار نداشته باشید که در این صورت پیشرفت کنید.

.مولوی، مثنوی، دفتر پنجم، بیت ۱۰۶۷
[.poem]
....
که درونِ سینه شرحت داده‌ایم
شرح اَندر سینه‌ات بِنهاده‌ایم
....

این جواب کسیست که میپرسه آیا همش باید فضا‌گشایی کنیم؟ بله. صدر سرا در مرکز توست.
فضا رو باز میکنی و از خاصیت فضاگشایی خداوند استفاده میکنی. فضا رو میبندی،
استفاده نمیکنی. توانایی فضاگشایی رو در مرکزت "ما" گذاشته‌ایم.

.مولوی، مثنوی، دفتر پنجم، بیت ۱۰۷۱
[.poem]
....
که اَلَمْ نَشْرَح نه شرحت هست باز؟
چون شدی تو شرح‌جو و کُدیه‌ساز؟

کُدیه‌ساز: گدایی کننده، تکدّی کننده
....

سوره انشراح به طور کلی میگه که سینه تو بازه. چون در سینه تو "ما" هستیم. "ما"
هم بینهایت فضا‌گشایی هستیم. صدر تو "ما" هستیم. ولی ما من ذهنی رو گذاشته‌ایم
مرکزمون. در نتیجه مرتب میگیم توضیح بده فضا‌گشایی چه جوریه؟ مرتب گدایی (کدیه
ساز) می‌کنیم. ما می‌تونیم این علم فضاگشایی رو و اینکه باید نسبت به من ذهنی کوچیک
بشیم رو، علم "ناظر بودن" رو، علم اینکه خداوند از طریق ما میخواد طرب کنه رو، علم
اینکه اتفاق این لحظه بازیه رو و فقط این فضای گشوده شده و فضا‌گشایی مهمه رو و این
فضاگشایی جدیه رو و بقیه پدیده‌ها و اتفاقات بازیه رو در "عمل یاد بگیریم". نه به
صورت من ذهنی دنبال توضیح بگردیم.

.مولوی، مثنوی، دفتر سوم، بیت ۱۶۳۹
[.poem]
....
هر زمان دل را دگر میلی دهم
هر نَفَس بر دل دگر داغی نَهَم

کُلُّ اَصْباحٍ لَنا شَأْنٌ جدید
کُلُّ شَیءٍ عَنْ مُرادی لا یَحید
....

زندگی در این لحظه در کار جدیده. این کار جدید رو هم به صورت اتفاق این لحظه به شما
ارائه میکنه. یه لحظه من تو رو می‌کشم، همانیده می‌کنم با یه چیزی، بعد داغ این رو بر
دلت می‌ذارم که بفهمی که تو با همانیدگی نباید ببینی و اون رو نباید بذاری مرکزت. یعنی
یه چیزی میارم به تو نشون میدم، تو باهاش همانیده میشی و بعد داغش رو بر دلت میذارم که
بفهمی غیر از من چیز دیگه‌ای نمیتونه مرکزت باشه.

در هر بامداد کاری تازه داریم، و هیچ کاری از حیطه مشیت من خارج نمی شود.
خداوند میگه من در هر لحظه (در این لحظه) در کار جدیدی هستم. روی تو دارم کار میکنم
و هیچ چیز، هیچ جنبه‌ای از تو از حیطه مشیت من خارج نمیشه. این لحظه اتفاقی برای تو
که جدیده پیش میارم و تو اون رو باید از من بدونی و باید در اطرافش فضاگشایی کنی و
هیچ کار تو از حیطه مشیت من خارج نیست.

'''

== یفعل الله ما یشاء

audio::/media/audio/873/yafalo_allaho_ma_yasha.mp3[controls]

.مولوی، مثنوی، دفتر دوم، بیت ۱۶۱۹
[.poem]
....
حاکم است و یَفْعَلُ الله مایَشا
او ز عینِ دَرد انگیزد دوا
....

.قرآن کریم، سوره آل عمران(۳)، آیه ۴۰
[.poem]
....
قَالَ رَبِّ أَنَّىٰ يَكُونُ لِي غُلَامٌ وَقَدْ بَلَغَنِيَ الْكِبَرُ وَامْرَأَتِي عَاقِرٌ ۖ قَالَ كَذَٰلِكَ اللَّهُ يَفْعَلُ مَا يَشَاءُ.

گفت: اى پروردگار من، چگونه مرا پسرى باشد، در حالى كه به پيرى رسيده‌ام و زنم نازاست؟ گفت: بدان سان كه خدا هر چه بخواهد مى كند.
....

.قرآن کریم، سوره ابراهیم(۱۴)، آیه ۲۷
[.poem]
....
يُثَبِّتُ اللَّهُ الَّذِينَ آمَنُوا بِالْقَوْلِ الثَّابِتِ فِي الْحَيَاةِ الدُّنْيَا وَفِي الْآخِرَةِ ۖ وَيُضِلُّ اللَّهُ الظَّالِمِينَ ۚ وَيَفْعَلُ اللَّهُ مَا يَشَاءُ

خدا مؤمنان را به سبب اعتقاد استوارشان در دنيا و آخرت پايدار مى‌دارد. و ظالمان را گمراه مى‌سازد و هر چه خواهد همان مى‌كند.
....

.قرآن کریم، سوره حج(۲۲)، آیه ۱۸
[.poem]
....
أَلَمْ تَرَ أَنَّ اللَّهَ يَسْجُدُ لَهُ مَنْ فِي السَّمَاوَاتِ وَمَنْ فِي الْأَرْضِ وَالشَّمْسُ وَالْقَمَرُ وَالنُّجُومُ وَالْجِبَالُ وَالشَّجَرُ وَالدَّوَابُّ وَكَثِيرٌ مِنَ النَّاسِ ۖ وَكَثِيرٌ حَقَّ عَلَيْهِ الْعَذَابُ ۗ وَمَنْ يُهِنِ اللَّهُ فَمَا لَهُ مِنْ مُكْرِمٍ ۚ إِنَّ اللَّهَ يَفْعَلُ مَا يَشَاءُ

آيا نديده‌اى كه هر كس در آسمانها و هر كس كه در زمين است و آفتاب و ماه و ستارگان و كوهها و درختان و جنبندگان و بسيارى از مردم خدا را سجده مى‌كنند؟ و بر بسيارى عذاب محقق شده و هر كه را خدا خوار سازد، هيچ كس گراميش نمى‌دارد. زيرا خدا هر چه بخواهد همان مى‌كند.
....

.مولوی، مثنوی، دفتر دوم، بیت ۱۶۲۵
[.poem]
....
چار طبع و علّتِ اُولی نیَم
در تصرّف دایماً من باقیَم

کارِ من بی علّت است و مستقیم
هست تقدیرم نه علّت، ای سَقیم

عادتِ خود را بگردانم به وقت
این غبار از پیش، بنشانم به وقت
....

.مولوی، مثنوی، دفتر ششم، بیت ۲۷۵۹
[.poem]
....
این عجب نَبْوَد که کور افتد به چاه
بُوالْعَجَب افتادنِ بینایِ راه

این قضا را گونه گون تصریفهاست
چشمْ‌بندش یَفْعَلُ‌الله مایَشاست

تصریف: تغییر
....

.مولوی، دیوان شمس، غزل شمارهٔ ۱۸
[.poem]
....
گفتم که « ز آتشهایِ دل، بر روی مَفرَشهای دل
می غَلْت در سودایِ دل تا بحرِ یَفْعَل ما یَشا»؟
....

.مولوی، دیوان شمس، غزل شمارهٔ ۲۸
[.poem]
....
زین رنگ ها مُفْرَد شود، در خُنبِ عیسی در رَوَد
در «صِبْغَةَ الله» رُو نهد تا «یَفْعَلُ اللَه مایَشا»

خنب عیسی: یکی از معجزات عیسی(ع) که اگر جامه صد رنگ را
در خم می انداختند، سفید و سیاه بر می آمد.
....

.قرآن کریم، سوره بقره(۲)، آیه ۱۳۸
[.poem]
....
صِبْغَةَ اللَّهِ ۖ وَمَنْ أَحْسَنُ مِنَ اللَّهِ صِبْغَةً ۖ وَنَحْنُ لَهُ عَابِدُونَ

رنگ خدا [را بگیرید و به رنگ خدایی درآیید.] و چه کسی نکو رنگتر از خداوند است؟! [ مسلماً هیچکس ] و ماییم پرستندگان او
....
