= برنامه ۹۶
:toc:
:toc-title!:
:nofooter:

.مولوی، دیوان شمس، غزل شماره ۶۳۶
[.poem]
....
بمیرید بمیرید در این عشق بمیرید
در این عشق چو مردید همه روح پذیرید

بمیرید بمیرید و زین مرگ مترسید
کز این خاک برآیید سماوات بگیرید

بمیرید بمیرید و زین نفس ببرید
که این نفس چو بندست و شما همچو اسیرید

یکی تیشه بگیرید پی حفره زندان
چو زندان بشکستید همه شاه و امیرید

بمیرید بمیرید به پیش شه زیبا
بر شاه چو مردید همه شاه و شهیرید

بمیرید بمیرید و زین ابر برآیید
چو زین ابر برآیید همه بدر منیرید
....

بدر منیر ماه شب چهارده هست. کامل و نورانی. میگه شما اگر از این ابر بالا بیایید. گاهی
ابر، جلوی این بدر منیر رو گرفته. یعنی وجود ما، حضور ما، زندگی ما که الان در شما می‌تپه،
این بدر منیره. نور دادن رو بلده. ذهن همش نگران اینه که حالا چی می‌شه؟ چه کار باید
بکنیم. شما همین این لحظه رو بپذیر و آگاهی به این داشته باش که همینطوری به این تسلیم و
این پذیرش این لحظه که همیشه در اون هستی ادامه بدی و فکرهات رو هم جدی نگیری، گذشته رو
هم ببخش و این شعور رو و این آگاهی رو همیشه نگه دار. همواره آگاه باش در این لحظه، بدر
منیر خودش رو نشون میده. این ابر پرده پندار ماست. هم‌هویت شدگی با فکرهای ماست که ما
جذبشون شده‌ایم و این شده زندان ما. باید خودمون رو بکشیم و از این ابر بیایم بالا. نوری
که ما از خودمون میتابونیم کامل نیست. از پشت این ابر سو سو میاد. این در حالیست که زندگی
کامله ولی در ما کامل حس نمیشه. مولانا خودش راهنمایی میکنه حالا. خموشید! خموشید!

.مولوی، دیوان شمس، غزل شماره ۶۳۶
[.poem]
....
خموشید خموشید خموشی دم مرگست
هم از زندگیست اینک ز خاموش نفیرید
....

نفیریدن یعنی خروش کردن. بیان خروشان زندگی در شما موقعی که به سکوت و سکون درونی میرسید.
یعنی موقعی که ذهن ساکت میشه. یعنی موقعی که فکرهای خودت رو جدی نگیری. وقتی فکرهای خودت
رو جدی نمی‌گیری، فکرهای دیگران رو هم جدی نمی‌گیری و هر فکری شما رو جذب نمی‌کنه و مقدار
زیادی هوش حضور در شما ایجاد میشه. هوش حضور ساکته. برای اینکه اصولا تسلسل فکری، یعنی
توجه کامل به پارازیت‌های بیرون. معادل اونها در ما فکره. هر سر و صدایی در بیرون می‌شنوید
در شما فکر تولید می‌کنه. به محض اینکه در بیرون روی سکوت تمرکز کنید، در شما سکون به وجود
میاد. معادل سکوت در بیرون، سکون در درون ماست. خاموشی دم مرگ این من ذهنیه. لحظه مرگشه.
خروش شما باید از خاموشی باشه. از سکون باشه. از اونجا بخروشید.

.مولوی، دیوان شمس، غزل شماره ۲۸۶۲
[.poem]
....
همچو آیینه شَوی خامش و گویا تو اگر
همه دل گردی و بر گفتِ زبان نَستیزی
....

مرگ عکس تولد هست، نه عکس زندگی. ما باید بگیم مرگ و تولد. نه مرگ و زندگی. زندگی جاودانه
هست. زندگی مرگ نمی‌شناسه. شما اگه برید جنگل می‌بینید یه سری درخت‌ها خیلی تنومندن. یک سری
درخت‌ها هم افتادن دارن خشک میشن. یک سری خشک شدن زیر پا. ظاهرا مرگ و زندگی رو با هم
می‌بینید. ولی این یک توهمه. خواهید دید اون تنه درخت که به نظر ذهن ما مرده هست خودش داره
زندگی ایجاد می‌کنه. خودش زنده هست. پس تغییر شکل وجود داره، مرگ وجود نداره. مرگ برای
من ذهنی بسیار خطرناکه. زندگی مرگ نمی‌شناسه. زندگی جاودانه هست. شما نباید از مرگ بترسید.

.مولوی، دیوان شمس، غزل شماره ۱۷۵۰
[.poem]
....
تلخی نکند شیرین ذقنم
خالی نکند از می دهنم

عریان کندم هر صبحدمی
گوید که بیا من جامه کنم

در خانه جهد مهلت ندهد
او بس نکند پس من چه کنم

از ساغر او گیج است سرم
از دیدن او جان است تنم

تنگ است بر او هر هفت فلک
چون می رود او در پیرهنم

از شیره او من شیردلم
در عربده اش شیرین سخنم

می گفت که تو در چنگ منی
من ساختمت چونت نزنم

من چنگ توام بر هر رگ من
تو زخمه زنی من تن تننم

حاصل تو ز من دل برنکنی
دل نیست مرا من خود چه کنم
....

اشتباه فکر کرده ای که تو تو هستی، من من هستم. تو من هستم. من میخوام تو رو بزنم. چون تو
رو ساختم که بزنم (بنوازم). ما پاسخ میدیم: من ساز توام. به هر رگ من که تو زخمه میزنی،
من نواخته میشم (تن تننم). آیا میشه ما به این مقام برسیم؟ من اطمینان دارم که تو ازم دل نمیکنی.
از کجا مطمئن شدم؟ برای اینکه تو دل من شده‌ای. دل من الان اون عنصره بی نام و نشان شده.
تو شدی الان دل من. پس من الان دل ندارم. و چون دل ندارم، نمیتونم دل بکنم.
یعنی من هم دیگه از تو دل نمیکنم. یعنی زنده شدم به حضور تو.
