= برنامه ۹۹۷
:toc:
:toc-title!:
:nofooter:

== خروب

audio::/media/audio/997/kharoob.mp3[controls]

.مولوی، مثنوی، دفتر چهارم، بیت ۱۳۸۳
[.poem]
....
مسجدست آن دل، که جسمش ساجدست
یارِ بَد خَرُّوبِ هر جا مسجدست

یارِ بَد چون رُست در تو مِهرِ او
هین ازو بگریز و کم کن گفت‌وگو

برکَن از بیخش، که گر سَر برزند
مر تو را و مسجدت را برکَنَد

عاشقا، خَرّوبِ تو آمد کژی
همچو طفلان، سویِ کژ چون می‌غژی؟

خَرُّوب: گیاه خَرنُوب که بوته‌ای بیابانی و مرتفع و خاردار است و در هر بنایی بروید آن را ویران می‌کند.
می‌غژی: فعل مضارع از غژیدن، به معنی خزیدن بر شکم مانند حرکت خزندگان و اطفال.
....

.مولوی، مثنوی، دفتر چهارم، بیت ۱۳۷۷
[.poem]
....
گفت: اندر تو چه خاصیّت بُوَد؟
گفت: من رُستَم، مکان ویران شود

رُستَن: روییدن
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۸۵
[.poem]
....
چون چنین وسواس دیدی، زود زود
با خدا گَرد و، درآ اندر سجود
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۸۷
[.poem]
....
آن زمان کِت امتحان مطلوب شد
مسجدِ دینِ تو، پُر خَرُّوب شد
....

.مولوی، مثنوی، دفتر پنجم، بیت ۵۵۰
[.poem]
....
چون زِ زنده مُرده بیرون می‌کُنَد
نَفْسِ زنده سویِ مرگی می‌تَنَد
....

== آینده لازم نیست امتداد گذشته باشه

audio::/media/audio/997/ayande_lazem_nist_emtedad_gozashte_bashe.mp3[controls]

.مولوی، دیوان شمس، غزل شمارهٔ ۱۶۱۱
[.poem]
....
ز درم راه نباشد، ز سرِ بام و دریچه
سَتَرَ اللهُ عَلَیْنٰا چه عَلالایِ تو دارم

سَتَرَ اللهُ عَلَیْنٰا: خداوند بر ما پوشانید
عَلالا: بانگ و فریاد، هیاهو، سروصدا
....

نذارید من ذهنیتون مانع سازی بکنه از اینکه گذشته من اینطور بوده و در گذشته
این کارهای بد رو کردم و این دردها رو ایجاد کردم و امکان رهایی وجود نداره.
نه. میگه خداوند اینها رو پوشانید. چنان پوشانید مثل اینکه اینها رو شما اصلا انجام ندادید.
زندگی رحمت اندر رحمته و این رحمت بستگی به کارهای گذشته شما نداره. اگر از در راه نیست،
من از طریق بام و دریچه میرم به بالای بام و علالای تو رو میکنم. فضا رو باز میکنم تا از طریق تو
حرف بزنم. درسته که ذهنم اجازه نمیده و هی به من تلقین میکنه که تو این کار رو کردی، اون کار
رو کردی، گذشته تو اینطوری بوده. ما باید از گذشته و ماجرا بیرون بپریم. شما نباید از چیزهایی
که ذهنتون نشون میده مانع ذهنی درست کنید و فضا رو باز نکنید یا جلوی پیشرفت خودتون رو بگیرید.

.مولوی، دیوان شمس، غزل شمارهٔ ۵۸۲
[.poem]
....
خُنُک جانی که بر بامَش همی چوبَک زَنَد امشب
شود همچون سَحَر خندان، عَطایِ بی ‌عدد بیند

چوبَک زدن: پاسبانی کردن، نگهبانی کردن
....

.مولوی، دیوان شمس، غزل شمارهٔ ۷۷۱
[.poem]
....
دل تو مثالِ بام است و، حواسْ ناودان‌ها
تو ز بام آب می‌خور که چو ناودان نماند

جامِ مُباح آمد، هین نوش کُن
بازرَه از غابر و از ماجَرا

مُباح: حلال، جامِ مُباح: شرابِ حلال
غابر: گذشته

خفته از احوال دنیا روز و شب
چون قلم در پنجه تقلیب رب

تقلیب: برگردانیدن، واژگونه کردن

ای عاشق جریده، بر عاشقان گزیده
بگذر ز آفریده، بنگر در آفریدن

جریده: یگانه، تنها

هر لحظه و هر ساعت یک شیؤە نو آرد
شیرینتر و نادرتر زآن شیؤە پیشینش

بر گذشته حسرت آوردن خطاست
باز نآید رفته، یاِد آن هباست

هبا: مخفف هباء به معنی گرد و غبار پراکنده. در اینجا به معنی بیهوده است
....

== شکر کافیه

audio::/media/audio/997/shokr_kafie.mp3[controls]

.مولوی، دیوان شمس، غزل شمارهٔ ۲۵۷
[.poem]
....
صورتِ اقبالِ شکَرریز گفت:
شُکر چو کم نیست، شکایت چرا؟

اقبال: بخت، كنايه از تجلّی خداوند

بادْ تُند است و چراغم اَبْتری
زو بگیرانم چراغِ دیگری

اَبْتَر: ناقص و به دردنخور

لذّتِ بی‌کرانه‌ای‌ست، عشق شده‌ست نام او
قاعده خود شکایت است، ورنه جفا چرا بُوَد؟
....

.مولوی، مثنوی، دفتر چهارم، بیت ۳۵۱۷
[.poem]
....
کافیَم، بدْهم تو را من جمله خیر
بی‌سبب، بی‌واسطهٔ یاریِ غیر

کافیَم بی‌نان تو را سیری دهم
بی‌سپاه و لشکرت میری دهم

بی‌بهارت نرگس و نسرین دهم
بی‌کتاب و اوستا تلقین دهم

کافیَم بی‌داروَت درمان کنم
گور را و چاه را میدان کنم
....

== هر گونه غم در جهان بیجاست و توهم ذهنه

audio::/media/audio/997/har_goone_gham_dar_jahan_bijast_va_tohame_zehne.mp3[controls]

.مولوی، مثنوی، دفتر پنجم، بیت ۱۴۶۳
[.poem]
....
مشتریِّ ماست اللهُ‌اشْتَریٰ
از غمِ هر مشتری هین برتر آ

کسی که فرموده است: خداوند می‌خرد، مشتری ماست.
به هوش باش، از غم مشتریانِ فاقد اعتبار بالاتر بیا.
....

== من چیز ذهنی رو نمیارم به مرکزم

audio::/media/audio/997/man_chize_zehni_ro_nemiaram_be_markazam.mp3[controls]

.مولوی، مثنوی، دفتر سوم، بیت ۱۳۵۹
[.poem]
....
ننگرم کس را و گر هم بنگرم
او بهانه باشد و، تو مَنْظَرم

عاشقِ صُنعِ تواَم در شُکر و صبر
عاشقِ مصنوع کی باشم چو گَبر؟

عاشقِ صُنعِ خدا با فَر بوَد
عاشقِ مصنوعِ او کافر بُوَد

مَنْظَر: جای نگریستن و نظر انداختن
شُکر و صبر: در اینجا کنایه از نعمت و بلاست.
گبر: کافر
صُنع: آفرینش
مصنوع: آفریده، مخلوق
....

.مولوی، مثنوی، دفتر چهارم، بیت ۲۰۰۶
[.poem]
....
قُلْ تَعالَوْا گفت از جذبِ کَرَم
تا ریاضتْتان دهم، من رایِضَم

رایِض: تربیت کنندهٔ اسب و ستور
....

== نهی

audio::/media/audio/997/nahi.mp3[controls]

.مولوی، مثنوی، دفتر ششم، بیت ۳۶۵۸
[.poem]
....
رغبتی زین منع در دلْشان بِرُست
که بباید سِرِّ آن را باز جُست

کیست کز ممنوع گردد مُمْتَنع؟
چونکه اَلْانسان حَریصٌ ما مُنِع

«كدام آدمی است که از امور ممنوعه خویشتن‌داری کند؟
در حالی که انسان از هر چیز منع شود نسبت به همان چیز حریص و آزمند گردد.»

«اَلْانسانُ حَریصٌ عَلیٰ مٰا مُنِعَ.»
«آدمی از هر آنچه منع شود، بدآن حرص می‌ورزد»

نهی، بر اهلِ تُقی تبغیض شد
نهی، بر اهلِ هَوا تحریض شد

مُمْتَنِع: امتناع‌کننده، کسی که از امری یا کاری باز‌ایستد و سرپیچی کند
تُقی: پرهیزگاری
تَبغیض: دشمنی ایجاد کردن میان دو کس، انگیختن بغض و نفرت
تَحریض: برانگیختن

پس، ازین یُغْوی بِهِ قَوْماً کَثیر
هم ازین یَهْدی بِهِ قَلْباً خَبیر

«پس بواسطه نهی، گروه بسیاری از مردم گمراه می‌شوند.
و نیز بواسطه همان نهی، دل آگاهان به هدایت می‌رسند.»
....

.قرآن کریم، سورهٔ بقره (۲)، آیهٔ ۲۶
[.poem]
....
«إِنَّ اللهَ لَا يَسْتَحْيِي أَنْ يَضْرِبَ مَثَلًا مَا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا الَّذِينَ آمَنُوا فَيَعْلَمُونَ
أَنَّهُ الْحَقُّ مِنْ رَبِّهِمْ ۖ وَأَمَّا الَّذِينَ كَفَرُوا فَيَقُولُونَ مَاذَا أَرَادَ اللهُ بِهَٰذَا مَثَلًا ۘ
يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِ إِلَّا الْفَاسِقِينَ»

«خدا ابايى ندارد كه به پشه و كمتر از آن مثل بزند. آنان كه ايمان آورده‌اند مى‌دانند
كه آن مثل درست و از جانب پروردگار آنهاست.
و امّا كافران مى‌گويند كه خدا از اين مثل چه مى‌خواسته است؟
بسيارى را بدان گمراه مى‌كند و بسيارى را هدايت. امّا تنها فاسقان را گمراه مى كند.»
....
