name: asciidoctor

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate HTML
        run: ./build.sh

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ganje_hozour
          path: "build/*.html"
